### ISSUE TITLE
Impossible to pass non-UTF-8 strings from vim to Python 3

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#1053]
When a vim variable has a value that is not a valid UTF-8 string, `:py3 vim.eval('variable')` raises UnicodeDecodeError.

This is causing plugins such as UltiSnips to [crash](https://github.com/SirVer/ultisnips/issues/690#issuecomment-246121159) when they try to process a list of mappings that involve `<A-@>`, since Vim thinks `<A-@>` is byte 0xC0.  Here's what happens in the plugin:
- it runs `vim.command('redir => _tmp_smaps | smap | redir END')` to get the mappings
- it tries to parse `vim.eval('_tmp_smaps').splitlines()` to see what select-mode mappings there are

Now I've the following mapping in my .vimrc

```
map! <Esc>@ <A-@>
```

(I've many more, but this one seems to be the one causing the problem)

When I run `smap`, vim shows this mapping as
![ekrano nuotrauka is 2016-09-10 22-09-29](https://cloud.githubusercontent.com/assets/159967/18412920/4aa7e4ee-77a3-11e6-9d3d-dd550905ff50.png)

but when I do

```
:redir => tmp | smap <Esc>@ | redir END
:echo tmp
```

I see

![ekrano nuotrauka is 2016-09-10 22-11-24](https://cloud.githubusercontent.com/assets/159967/18412930/93bfb8e6-77a3-11e6-821a-3d5ecf096937.png)

and I can reproduce the crash with

```
:py3 import vim; vim.eval('tmp')
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 18: invalid start byte
```

**Comment by bfredl** [comment]
Here is another test case

```
:0put =printf('%c',0xFF)
:py3 print(repr(vim.current.buffer[0]))
:py3 vim.current.buffer[0] += "x"
:py3 print(vim.eval("getbufline('', 1)"))
```

apparently the first `:py3` is ok, it uses `surrogatescape`, but not the other two. Probably  `:python3` should use `surrogatescape` always, and both when decoding and encoding. (This is what neovim's `:python3` implementation does, BTW)

**Comment by bfredl** [comment]
Maybe like this:

``` diff
diff --git a/src/if_py_both.h b/src/if_py_both.h
index c44fc93..19f8584 100644
--- a/src/if_py_both.h
+++ b/src/if_py_both.h
@@ -134,7 +134,7 @@ StringToChars(PyObject *obj, PyObject **todecref)
     {
        PyObject        *bytes;

-       if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
+       if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, CODEC_ERROR_HANDLER)))
            return NULL;

        if(PyBytes_AsStringAndSize(bytes, (char **) &str, NULL) == -1
@@ -4117,7 +4117,7 @@ StringToLine(PyObject *obj)
     }
     else if (PyUnicode_Check(obj))
     {
-       if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
+       if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, CODEC_ERROR_HANDLER)))
            return NULL;

        if (PyBytes_AsStringAndSize(bytes, &str, &len) == -1
@@ -6197,7 +6197,7 @@ _ConvertFromPyObject(PyObject *obj, typval_T *tv, PyObject *lookup_dict)
        PyObject        *bytes;
        char_u  *str;

-       bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL);
+       bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, CODEC_ERROR_HANDLER);
        if (bytes == NULL)
            return -1;

diff --git a/src/if_python.c b/src/if_python.c
index 622634d..edb6400 100644
--- a/src/if_python.c
+++ b/src/if_python.c
@@ -90,6 +90,9 @@ struct PyMethodDef { Py_ssize_t a; };
 # define PySequenceMethods Py_ssize_t
 #endif

+/* The "surrogateescape" error handler is new in Python 3.1 */
+#define CODEC_ERROR_HANDLER NULL
+
 #if defined(PY_VERSION_HEX) && PY_VERSION_HEX >= 0x02070000
 # define PY_USE_CAPSULE
 #endif
diff --git a/src/if_python3.c b/src/if_python3.c
index 53a1313..5d9c058 100644
--- a/src/if_python3.c
+++ b/src/if_python3.c
@@ -96,7 +96,7 @@
 # define PyString_Check(obj) PyUnicode_Check(obj)
 #endif
 #define PyString_FromString(repr) \
-    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, NULL)
+    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, CODEC_ERROR_HANDLER)
 #define PyString_FromFormat PyUnicode_FromFormat
 #ifndef PyInt_Check
 # define PyInt_Check(obj) PyLong_Check(obj)

```

**Comment by nuko8** [comment]
To incorporate @bfredl 's patch into our build system,  it looks like we need an additional patch:

``` diff
diff --git a/src/if_python.c b/src/if_python.c
index edb6400..ffad23e 100644
--- a/src/if_python.c
+++ b/src/if_python.c
@@ -91,7 +91,9 @@ struct PyMethodDef { Py_ssize_t a; };
 #endif

 /* The "surrogateescape" error handler is new in Python 3.1 */
-#define CODEC_ERROR_HANDLER NULL
+#if defined(PY_VERSION_HEX) && PY_VERSION_HEX < 0x03010000
+# define CODEC_ERROR_HANDLER NULL
+#endif

 #if defined(PY_VERSION_HEX) && PY_VERSION_HEX >= 0x02070000
 # define PY_USE_CAPSULE
```

With those patches, I confirm that the resulting vim works well with the examples @bfredl mentioned above.

But I don't think I am a good python tester.  It would be far better if someone else could confirm that, ideally, with other examples.

**Comment by bfredl** [comment]
Hmm, but ain't `PY_VERSION_HEX < 0x03010000` always true when you are in `if_python.c` ? If the version hex is >= 0x03000000, `if_python3.c` should be used...

**Comment by vim-ml** [comment]
I would suggest something like below, but I have no tests.

commit 615351832d75df3dfbc3f22694e675583e0b325d
Author: ZyX kp-pav@yandex.ru
Date:   Tue Aug 16 21:42:24 2016 +0300

```
Use surrogateescape when appropriate
```

diff --git a/src/if_py_both.h b/src/if_py_both.h
index 35ad5d0..6709300 100644
--- a/src/if_py_both.h
+++ b/src/if_py_both.h
@@ -134,7 +134,8 @@ StringToChars(PyObject _obj, PyObject *_todecref)
     {
  PyObject *bytes;
- if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
- if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT,
- ERRORS_ENCODE_ARG)))
   return NULL;
  
  if(PyBytes_AsStringAndSize(bytes, (char **) &str, NULL) == -1
  @@ -4117,7 +4118,8 @@ StringToLine(PyObject *obj)
   }
   else if (PyUnicode_Check(obj))
   {
- if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
- if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT,
- ERRORS_ENCODE_ARG)))
   return NULL;
  
  if (PyBytes_AsStringAndSize(bytes, &str, &len) == -1
  @@ -6197,7 +6199,7 @@ _ConvertFromPyObject(PyObject *obj, typval_T
  *tv, PyObject *lookup_dict)
  PyObject *bytes;
  char_u *str;
- bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL);
- bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, ERRORS_ENCODE_ARG);
  if (bytes == NULL)
     return -1;

diff --git a/src/if_python.c b/src/if_python.c
index 622634d..1cafe34 100644
--- a/src/if_python.c
+++ b/src/if_python.c
@@ -70,6 +70,9 @@
 # undef PY_SSIZE_T_CLEAN
 #endif

+#define ERRORS_DECODE_ARG NULL
+#define ERRORS_ENCODE_ARG ERRORS_DECODE_ARG
+
 #if defined(MACOS) && !defined(MACOS_X_UNIX)
 # include "macglue.h"
 # include <CodeFragments.h>
diff --git a/src/if_python3.c b/src/if_python3.c
index 10984cd..9085c3c 100644
--- a/src/if_python3.c
+++ b/src/if_python3.c
@@ -91,12 +91,15 @@
 /\* Python 3 does not support CObjects, always use Capsules */
 #define PY_USE_CAPSULE

+#define ERRORS_DECODE_ARG CODEC_ERROR_HANDLER
+#define ERRORS_ENCODE_ARG ERRORS_DECODE_ARG
+
 #define PyInt Py_ssize_t
 #ifndef PyString_Check
 # define PyString_Check(obj) PyUnicode_Check(obj)
 #endif
 #define PyString_FromString(repr) \
-    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, NULL)
-    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, ERRORS_DECODE_ARG)
  #define PyString_FromFormat PyUnicode_FromFormat
  #ifndef PyInt_Check
  # define PyInt_Check(obj) PyLong_Check(obj)
  @@ -969,8 +972,8 @@ DoPyCommand(const char _cmd, rangeinitializer
  init_range, runner run, void *arg)
   /_ PyRun_SimpleString expects a UTF-8 string. Wrong encoding may cause
  - SyntaxError (unicode error). */
    cmdstr = PyUnicode_Decode(cmd, strlen(cmd),
- (char *)ENC_OPT, CODEC_ERROR_HANDLER);
-    cmdbytes = PyUnicode_AsEncodedString(cmdstr, "utf-8", CODEC_ERROR_HANDLER);
- (char *)ENC_OPT, ERRORS_DECODE_ARG);
-    cmdbytes = PyUnicode_AsEncodedString(cmdstr, "utf-8", ERRORS_ENCODE_ARG);
   Py_XDECREF(cmdstr);
  
   run(PyBytes_AsString(cmdbytes), arg, &pygilstate);
  @@ -1642,7 +1645,7 @@ LineToString(const char *str)
   }
   *p = '\0';
-    result = PyUnicode_Decode(tmp, len, (char *)ENC_OPT, CODEC_ERROR_HANDLER);
-    result = PyUnicode_Decode(tmp, len, (char *)ENC_OPT, ERRORS_DECODE_ARG);
  
   vim_free(tmp);
   return result;

commit 615351832d75df3dfbc3f22694e675583e0b325d
Author: ZyX kp-pav@yandex.ru
Date:   Tue Aug 16 21:42:24 2016 +0300

```
Use surrogateescape when appropriate
```

diff --git a/src/if_py_both.h b/src/if_py_both.h
index 35ad5d0..6709300 100644
--- a/src/if_py_both.h
+++ b/src/if_py_both.h
@@ -134,7 +134,8 @@ StringToChars(PyObject _obj, PyObject *_todecref)
     {
    PyObject    *bytes;
-   if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
-   if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT,
- ```
        ERRORS_ENCODE_ARG)))
  return NULL;
  ```
  
  if(PyBytes_AsStringAndSize(bytes, (char **) &str, NULL) == -1
  @@ -4117,7 +4118,8 @@ StringToLine(PyObject *obj)
   }
   else if (PyUnicode_Check(obj))
   {
-   if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
-   if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT,
- ```
        ERRORS_ENCODE_ARG)))
  return NULL;
  ```
  
  if (PyBytes_AsStringAndSize(bytes, &str, &len) == -1
  @@ -6197,7 +6199,7 @@ _ConvertFromPyObject(PyObject *obj, typval_T *tv, PyObject *lookup_dict)
  PyObject    *bytes;
  char_u  *str;
-   bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL);
-   bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, ERRORS_ENCODE_ARG);
  if (bytes == NULL)
      return -1;

diff --git a/src/if_python.c b/src/if_python.c
index 622634d..1cafe34 100644
--- a/src/if_python.c
+++ b/src/if_python.c
@@ -70,6 +70,9 @@
 # undef PY_SSIZE_T_CLEAN
 #endif

+#define ERRORS_DECODE_ARG NULL
+#define ERRORS_ENCODE_ARG ERRORS_DECODE_ARG
+
 #if defined(MACOS) && !defined(MACOS_X_UNIX)
 # include "macglue.h"
 # include <CodeFragments.h>
diff --git a/src/if_python3.c b/src/if_python3.c
index 10984cd..9085c3c 100644
--- a/src/if_python3.c
+++ b/src/if_python3.c
@@ -91,12 +91,15 @@
 /\* Python 3 does not support CObjects, always use Capsules */
 #define PY_USE_CAPSULE

+#define ERRORS_DECODE_ARG CODEC_ERROR_HANDLER
+#define ERRORS_ENCODE_ARG ERRORS_DECODE_ARG
+
 #define PyInt Py_ssize_t
 #ifndef PyString_Check
 # define PyString_Check(obj) PyUnicode_Check(obj)
 #endif
 #define PyString_FromString(repr) \
-    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, NULL)
-    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, ERRORS_DECODE_ARG)
  #define PyString_FromFormat PyUnicode_FromFormat
  #ifndef PyInt_Check
  # define PyInt_Check(obj) PyLong_Check(obj)
  @@ -969,8 +972,8 @@ DoPyCommand(const char _cmd, rangeinitializer init_range, runner run, void *arg)
   /_ PyRun_SimpleString expects a UTF-8 string. Wrong encoding may cause
  - SyntaxError (unicode error). */
    cmdstr = PyUnicode_Decode(cmd, strlen(cmd),
-                   (char *)ENC_OPT, CODEC_ERROR_HANDLER);
-    cmdbytes = PyUnicode_AsEncodedString(cmdstr, "utf-8", CODEC_ERROR_HANDLER);
-                   (char *)ENC_OPT, ERRORS_DECODE_ARG);
-    cmdbytes = PyUnicode_AsEncodedString(cmdstr, "utf-8", ERRORS_ENCODE_ARG);
   Py_XDECREF(cmdstr);
  
   run(PyBytes_AsString(cmdbytes), arg, &pygilstate);
  @@ -1642,7 +1645,7 @@ LineToString(const char *str)
   }
   *p = '\0';
-    result = PyUnicode_Decode(tmp, len, (char *)ENC_OPT, CODEC_ERROR_HANDLER);
-    result = PyUnicode_Decode(tmp, len, (char *)ENC_OPT, ERRORS_DECODE_ARG);
  
   vim_free(tmp);
   return result;

**Comment by ZyX-I** [comment]
```Patch
commit 615351832d75df3dfbc3f22694e675583e0b325d
Author: ZyX <kp-pav@yandex.ru>
Date:   Tue Aug 16 21:42:24 2016 +0300

    Use surrogateescape when appropriate

diff --git a/src/if_py_both.h b/src/if_py_both.h
index 35ad5d0..6709300 100644
--- a/src/if_py_both.h
+++ b/src/if_py_both.h
@@ -134,7 +134,8 @@ StringToChars(PyObject *obj, PyObject **todecref)
     {
 	PyObject	*bytes;
 
-	if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
+	if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT,
+			ERRORS_ENCODE_ARG)))
 	    return NULL;
 
 	if(PyBytes_AsStringAndSize(bytes, (char **) &str, NULL) == -1
@@ -4117,7 +4118,8 @@ StringToLine(PyObject *obj)
     }
     else if (PyUnicode_Check(obj))
     {
-	if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
+	if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT,
+			ERRORS_ENCODE_ARG)))
 	    return NULL;
 
 	if (PyBytes_AsStringAndSize(bytes, &str, &len) == -1
@@ -6197,7 +6199,7 @@ _ConvertFromPyObject(PyObject *obj, typval_T *tv, PyObject *lookup_dict)
 	PyObject	*bytes;
 	char_u	*str;
 
-	bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL);
+	bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, ERRORS_ENCODE_ARG);
 	if (bytes == NULL)
 	    return -1;
 
diff --git a/src/if_python.c b/src/if_python.c
index 622634d..1cafe34 100644
--- a/src/if_python.c
+++ b/src/if_python.c
@@ -70,6 +70,9 @@
 # undef PY_SSIZE_T_CLEAN
 #endif
 
+#define ERRORS_DECODE_ARG NULL
+#define ERRORS_ENCODE_ARG ERRORS_DECODE_ARG
+
 #if defined(MACOS) && !defined(MACOS_X_UNIX)
 # include "macglue.h"
 # include <CodeFragments.h>
diff --git a/src/if_python3.c b/src/if_python3.c
index 10984cd..9085c3c 100644
--- a/src/if_python3.c
+++ b/src/if_python3.c
@@ -91,12 +91,15 @@
 /* Python 3 does not support CObjects, always use Capsules */
 #define PY_USE_CAPSULE
 
+#define ERRORS_DECODE_ARG CODEC_ERROR_HANDLER
+#define ERRORS_ENCODE_ARG ERRORS_DECODE_ARG
+
 #define PyInt Py_ssize_t
 #ifndef PyString_Check
 # define PyString_Check(obj) PyUnicode_Check(obj)
 #endif
 #define PyString_FromString(repr) \
-    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, NULL)
+    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, ERRORS_DECODE_ARG)
 #define PyString_FromFormat PyUnicode_FromFormat
 #ifndef PyInt_Check
 # define PyInt_Check(obj) PyLong_Check(obj)
@@ -969,8 +972,8 @@ DoPyCommand(const char *cmd, rangeinitializer init_range, runner run, void *arg)
     /* PyRun_SimpleString expects a UTF-8 string. Wrong encoding may cause
      * SyntaxError (unicode error). */
     cmdstr = PyUnicode_Decode(cmd, strlen(cmd),
-					(char *)ENC_OPT, CODEC_ERROR_HANDLER);
-    cmdbytes = PyUnicode_AsEncodedString(cmdstr, "utf-8", CODEC_ERROR_HANDLER);
+					(char *)ENC_OPT, ERRORS_DECODE_ARG);
+    cmdbytes = PyUnicode_AsEncodedString(cmdstr, "utf-8", ERRORS_ENCODE_ARG);
     Py_XDECREF(cmdstr);
 
     run(PyBytes_AsString(cmdbytes), arg, &pygilstate);
@@ -1642,7 +1645,7 @@ LineToString(const char *str)
     }
     *p = '\0';
 
-    result = PyUnicode_Decode(tmp, len, (char *)ENC_OPT, CODEC_ERROR_HANDLER);
+    result = PyUnicode_Decode(tmp, len, (char *)ENC_OPT, ERRORS_DECODE_ARG);
 
     vim_free(tmp);
     return result;
```

**Comment by ZyX-I** [comment]
615351832d75df3dfbc3f22694e675583e0b325d

**Comment by ZyX-I** [comment]
ZyX-I/vim@615351832d75df3dfbc3f22694e675583e0b325d

**Comment by bfredl** [comment]
What is wrong with just using `CODEC_ERROR_HANDLER` directly?

**Comment by vim-ml** [comment]
2016-09-11 19:23 GMT+03:00 Björn Linse vim-dev-github@256bit.org:

> What is wrong with just using CODEC_ERROR_HANDLER directly?

AFAIR this is because Python-2 may need "surrogateescape" argument in
the Python->Vim direction (to make writing cross-Python scripts), but
it definitely does not need it when converting from Vim to Python.
That commit does nothing like this, it is a minimal required change to
fix the issue.

**Comment by bfredl** [comment]
But python2 does not have surrogateescape, in python2 one would represent a byte string as `str` with no problems. The very point of "surrogateescape" is that you use it in _both_ directions, so that a bytestring  can be roundtripped losslessly as a python3 str and then back to a bytestring (but only in that direction).

I'm asking because after your patch `CODEC_ERROR_HANDLER` is then only ever to `#define` another macro. Why not just use it directly as in my patch? If indirection is needed later it could be added later when it's needed.

**Comment by ZyX-I** [comment]
@bfredl Python2 has unicode() strings. And if you want to write python23 scripts you will use `from __future__ import unicode_literals` (thus Python->Vim will receive unicode strings with no non-unicode characters unless explicitly requested), but Vim API will _still_ produce byte strings in Python 2, so using this in “both directions” is impossible. Also my Python2 has `surrogateescape` error handler, though after some investigation it appeared that it was coming from some site package provided for compatibility with Python3 so this idea does not make much sense.

**Comment by lacygoill** [comment]
In case it helps, here is an updated patch from @ZyX-I:
```diff
diff --git a/src/if_py_both.h b/src/if_py_both.h
index 7b748b25e..e657624dd 100644
--- a/src/if_py_both.h
+++ b/src/if_py_both.h
@@ -130,7 +130,8 @@ StringToChars(PyObject *obj, PyObject **todecref)
     {
 	PyObject	*bytes;
 
-	if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
+	if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT,
+			ERRORS_ENCODE_ARG)))
 	    return NULL;
 
 	if(PyBytes_AsStringAndSize(bytes, (char **) &str, NULL) == -1
@@ -4243,7 +4244,8 @@ StringToLine(PyObject *obj)
     }
     else if (PyUnicode_Check(obj))
     {
-	if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL)))
+	if (!(bytes = PyUnicode_AsEncodedString(obj, ENC_OPT,
+			ERRORS_ENCODE_ARG)))
 	    return NULL;
 
 	if (PyBytes_AsStringAndSize(bytes, &str, &len) == -1
@@ -6290,7 +6292,7 @@ _ConvertFromPyObject(PyObject *obj, typval_T *tv, PyObject *lookup_dict)
 	PyObject	*bytes;
 	char_u	*str;
 
-	bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, NULL);
+	bytes = PyUnicode_AsEncodedString(obj, ENC_OPT, ERRORS_ENCODE_ARG);
 	if (bytes == NULL)
 	    return -1;
 
diff --git a/src/if_python.c b/src/if_python.c
index 6338a5b8d..29f7ed560 100644
--- a/src/if_python.c
+++ b/src/if_python.c
@@ -69,6 +69,9 @@
 # undef PY_SSIZE_T_CLEAN
 #endif
 
+#define ERRORS_DECODE_ARG NULL
+#define ERRORS_ENCODE_ARG ERRORS_DECODE_ARG
+
 #undef main // Defined in python.h - aargh
 #undef HAVE_FCNTL_H // Clash with os_win32.h
 
diff --git a/src/if_python3.c b/src/if_python3.c
index a51be2949..ea4fd7dd8 100644
--- a/src/if_python3.c
+++ b/src/if_python3.c
@@ -81,12 +81,15 @@
 // Python 3 does not support CObjects, always use Capsules
 #define PY_USE_CAPSULE
 
+#define ERRORS_DECODE_ARG CODEC_ERROR_HANDLER
+#define ERRORS_ENCODE_ARG ERRORS_DECODE_ARG
+
 #define PyInt Py_ssize_t
 #ifndef PyString_Check
 # define PyString_Check(obj) PyUnicode_Check(obj)
 #endif
 #define PyString_FromString(repr) \
-    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, NULL)
+    PyUnicode_Decode(repr, STRLEN(repr), ENC_OPT, ERRORS_DECODE_ARG)
 #define PyString_FromFormat PyUnicode_FromFormat
 #ifndef PyInt_Check
 # define PyInt_Check(obj) PyLong_Check(obj)
@@ -1088,8 +1091,8 @@ DoPyCommand(const char *cmd, rangeinitializer init_range, runner run, void *arg)
     // PyRun_SimpleString expects a UTF-8 string. Wrong encoding may cause
     // SyntaxError (unicode error).
     cmdstr = PyUnicode_Decode(cmd, strlen(cmd),
-					(char *)ENC_OPT, CODEC_ERROR_HANDLER);
-    cmdbytes = PyUnicode_AsEncodedString(cmdstr, "utf-8", CODEC_ERROR_HANDLER);
+					(char *)ENC_OPT, ERRORS_DECODE_ARG);
+    cmdbytes = PyUnicode_AsEncodedString(cmdstr, "utf-8", ERRORS_ENCODE_ARG);
     Py_XDECREF(cmdstr);
 
     run(PyBytes_AsString(cmdbytes), arg, &pygilstate);
@@ -1745,7 +1748,7 @@ LineToString(const char *str)
     }
     *p = '\0';
 
-    result = PyUnicode_Decode(tmp, len, (char *)ENC_OPT, CODEC_ERROR_HANDLER);
+    result = PyUnicode_Decode(tmp, len, (char *)ENC_OPT, ERRORS_DECODE_ARG);
 
     vim_free(tmp);
     return result;
```
---

As for the question asked in the relevant todo item:

https://github.com/vim/vim/blob/ef2dff52de52c17fe1bd7c06cbb32d8955901f5a/runtime/doc/todo.txt#L1276-L1277

Yes, the patch works.  I tested it against the original example.  Without the patch:

    vim -Nu NONE -S <(cat <<'EOF'
        smap <Esc>@ <A-@>
        py3 vim.command('redir => _tmp_smaps | smap | redir END')
        py3 vim.eval('_tmp_smaps').splitlines()
    EOF
    )

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 18: invalid start byte

With the patch:

    ./src/vim -Nu NONE -S <(cat <<'EOF'
        smap <Esc>@ <A-@>
        py3 vim.command('redir => _tmp_smaps | smap | redir END')
        py3 vim.eval('_tmp_smaps').splitlines()
    EOF
    )

    # no error

---

Note that someone has asked a [question on vi.stackexchange](https://vi.stackexchange.com/questions/28504/unicodedecodeerror-caused-by-the-key-bs) which I *think* has the same cause.  This command:

    :let variable = "\<bs>" | py3 print(vim.eval('variable'))

raises this error:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

I've tried the patch, and unfortunately the error persists; but it changes from `UnicodeDecodeError` to `UnicodeEncodeError`:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 0: surrogates not allowed

**Comment by ZhiyuanLck** [comment]
> Note that someone has asked a [question on vi.stackexchange](https://vi.stackexchange.com/questions/28504/unicodedecodeerror-caused-by-the-key-bs) which I _think_ has the same cause. This command:
> 
> ```
> :let variable = "\<bs>" | py3 print(vim.eval('variable'))
> ```
> 
> raises this error:
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> ```
> 
> I've tried the patch, and unfortunately the error persists; but it changes from `UnicodeDecodeError` to `UnicodeEncodeError`:
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 0: surrogates not allowed
> ```
So it is an unsolved issue now?

**Comment by chrisbra** [comment]
it's probably unsolved until it has been merged successfully.

**Comment by brammool** [comment]
Please check for any remaining encoding/decoding issues.

**Comment by lacygoill** [comment]
> Please check for any remaining encoding/decoding issues.

The patch has fixed the original issue.  But a similar one persists for a string containing `<bs>`.  This command:

    :let variable = "\<bs>" | py3 print(vim.eval('variable'))

Raises:

    UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 0: surrogates not allowed
