### ISSUE TITLE
heap-buffer-overflow with asan build of Vim small

### ISSUE THREAD

**Issue by dpelle** [vim/vim#11135]
### Steps to reproduce

If I build vim-9.0.465 (latest) with asan as follows, I observe a heap-buffer-overflow when running tests: 
```
$ cd vim
$ git diff
diff --git a/src/Makefile b/src/Makefile
index 59c9b64ad..ba141f4e1 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -703,7 +703,7 @@ LINT_OPTIONS = -beprxzF
 # $ export UBSAN_OPTIONS="print_stacktrace=1 log_path=ubsan"
 # $ export LSAN_OPTIONS="suppressions=`pwd`/testdir/lsan-suppress.txt"
 # When running tests output can be found in testdir/ubsan.*
-#SANITIZER_CFLAGS = -g -O0  -fsanitize-recover=all -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer
+SANITIZER_CFLAGS = -g -O0  -fsanitize-recover=all -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer
 
 SANITIZER_LIBS = $(SANITIZER_CFLAGS)

$ ./configure --with-features=small
$ make -j8
$ make test
...snip...
cp test22.ok test.ok
VIMRUNTIME=../../runtime  ../vim -f  -u unix.vim -U NONE --noplugin --not-a-term -s dotest.in test22.in --cmd 'au SwapExists * let v:swapchoice = "e"' | LC_ALL=C LANG=C LANGUAGE=C awk '/Executing Test_/{match($0, "Executing Test_[^\\)]*\\)"); print substr($0, RSTART, RLENGTH) "\r"; fflush()}'
=================================================================
==892==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61b000000060 at pc 0x55c7bef7b597 bp 0x7fffc1f57a30 sp 0x7fffc1f57a28
WRITE of size 8 at 0x61b000000060 thread T0
    #0 0x55c7bef7b596 in getsourceline /home/dope/sb/vim/src/scriptfile.c:2235:19
    #1 0x55c7bea42ef1 in do_cmdline /home/dope/sb/vim/src/ex_docmd.c:873:46
    #2 0x55c7bef7a8c4 in do_source_ext /home/dope/sb/vim/src/scriptfile.c:1664:5
    #3 0x55c7bef78b40 in do_source /home/dope/sb/vim/src/scriptfile.c:1808:12
    #4 0x55c7bf1a85d4 in source_startup_scripts /home/dope/sb/vim/src/main.c:3202:10
    #5 0x55c7bf19c263 in main /home/dope/sb/vim/src/main.c:420:5
    #6 0x7f5ef28a4c86 in __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310
    #7 0x55c7be7c85e9 in _start (/home/dope/sb/vim/src/vim+0x4365e9) (BuildId: f575f01a3073005a024bc8932a0c5db7e607b00e)

0x61b000000060 is located 32 bytes to the left of 1600-byte region [0x61b000000080,0x61b0000006c0)
allocated by thread T0 here:
    #0 0x55c7be84d5d6 in __interceptor_realloc (/home/dope/sb/vim/src/vim+0x4bb5d6) (BuildId: f575f01a3073005a024bc8932a0c5db7e607b00e)
    #1 0x55c7be88872a in ga_grow_inner /home/dope/sb/vim/src/alloc.c:755:10
    #2 0x55c7be8880d3 in ga_grow /home/dope/sb/vim/src/alloc.c:720:9
    #3 0x55c7bef72e18 in estack_init /home/dope/sb/vim/src/scriptfile.c:36:9
    #4 0x55c7bf19c290 in common_init /home/dope/sb/vim/src/main.c:899:5
    #5 0x55c7bf19baa2 in main /home/dope/sb/vim/src/main.c:185:5
    #6 0x7f5ef28a4c86 in __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/dope/sb/vim/src/scriptfile.c:2235:19 in getsourceline
Shadow bytes around the buggy address:
  0x0c367fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c367fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c367fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c367fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c367fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c367fff8000: fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa
  0x0c367fff8010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c367fff8020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c367fff8030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c367fff8040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c367fff8050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==892==ABORTING
```

### Expected behaviour

No asan error

### Version of Vim

vim-9.0.465

### Environment

xubuntu-18.04.6
vim small

**Comment by brammool** [comment]
> ### Steps to reproduce
> 
> If I build vim-9.0.465 (latest) with asan as follows, I observe a
> heap-buffer-overflow when running tests: 

Must have been happening for a very long time.  When build without the
+eval feature the execution stack is popped but not pushed.  There are
checks for this only when build with the +eval feature...

-- 
hundred-and-one symptoms of being an internet addict:
79. All of your most erotic dreams have a scrollbar at the right side.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
