### ISSUE TITLE
Unexpected line break in command line when nested function definitions are autoloaded

### ISSUE THREAD

**Issue by h-east** [vim/vim#11773]
### Steps to reproduce

- Prepare following files:

~/.vim/pack/my/start/sample/plugin/sample.vim
```vim
vim9script
augroup SAMPLE
	autocmd!
	autocmd CmdlineEnter * sample#Init()
augroup END
```

~/.vim/pack/my/start/sample/autoload/sample.vim
```vim
vim9script
export def Init(): void
	cnoremap <expr>" <SID>Quote('"')
enddef
def Quote(str: string): string
	def InPair(): number
		return 0
	enddef
	return str
enddef
```

---

- How to repro.
1. Start Vim
```bash
$ vim -Nu NORC
```
2. Type double-quote after colon
`:"`

- Actual behavior
`"` is displayed after a line break.  (See image below)
![image](https://user-images.githubusercontent.com/518808/210195221-92fb3da6-b161-49fa-af16-295a061ccae8.png)

- Remarks
1. This behavior only occurs the first time.  (when the autoload mechanism is triggered) 
2. It doesn't happen if you write `defcompile` at the end of the `Init()` function.

### Expected behaviour

`:"` appears in the command line.

### Version of Vim

Vim 9.0.1128

### Environment

On Fedora 32 via PuTTY 0.73

### Logs and stack traces

```shell
Back trace


#11 0x0000000000706ed0 in msg_putchar (c=10) at message.c:1518
#12 0x00000000006653aa in define_function
    (eap=0x7ffdc108fe30, name_arg=0x1fd0ec0 "<lambda>2", lines_to_free=0x7ffdc10
901c0, in_class=0) at userfunc.c:4892
#13 0x00000000006730b5 in compile_nested_function
    (eap=0x7ffdc108fe30, cctx=0x7ffdc1090030, lines_to_free=0x7ffdc10901c0)
    at vim9compile.c:1004
#14 0x0000000000678774 in compile_def_function
    (ufunc=0x20229a0, check_return_type=0, compile_type=CT_NONE, outer_cctx=0x0)
 at vim9compile.c:3421
#15 0x00000000006878ae in call_def_function
    (ufunc=0x20229a0, argc_arg=1, argv=0x7ffdc1090d90, flags=0, partial=0x0, obj
ect=0x0, funccal=0x1fcd560, rettv=0x7ffdc1091840) at vim9execute.c:5684
#16 0x0000000000660ef3 in call_user_func
    (fp=0x20229a0, argcount=1, argvars=0x7ffdc1090d90, rettv=0x7ffdc1091840, fun
cexe=0x7ffdc1090f40, selfdict=0x0) at userfunc.c:2771
#17 0x0000000000661f3d in call_user_func_check
    (fp=0x20229a0, argcount=1, argvars=0x7ffdc1090d90, rettv=0x7ffdc1091840, fun
cexe=0x7ffdc1090f40, selfdict=0x0) at userfunc.c:3189
#18 0x0000000000662d1e in call_func
	    (funcname=0x20207b0 "\200\375R15_Quote('\"')", len=11, rettv=0x7ffdc1091840,
 argcount_in=1, argvars_in=0x7ffdc1090d90, funcexe=0x7ffdc1090f40)
    at userfunc.c:3745
#19 0x000000000065f61c in get_func_tv
    (name=0x20207b0 "\200\375R15_Quote('\"')", len=11, rettv=0x7ffdc1091840, arg
=0x7ffdc1091710, evalarg=0x7ffdc10917b0, funcexe=0x7ffdc1090f40)
    at userfunc.c:1923
#20 0x000000000046d005 in eval_func
    (arg=0x7ffdc1091710, evalarg=0x7ffdc10917b0, name=0x2036ca0 "\200\375R15_Quo
te('\"')", name_len=11, rettv=0x7ffdc1091840, flags=1, basetv=0x0)
    at eval.c:2335
#21 0x00000000004708fd in eval9
    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0, want_stri
ng=0) at eval.c:4239
#22 0x000000000046fc19 in eval8
    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0, want_stri
ng=0) at eval.c:3799
#23 0x000000000046f690 in eval7
	    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0, want_stri
ng=0) at eval.c:3603
#24 0x000000000046ef29 in eval6
    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0)
    at eval.c:3382
#25 0x000000000046ec08 in eval5
    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0)
    at eval.c:3271
#26 0x000000000046e728 in eval4
    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0)
    at eval.c:3122
#27 0x000000000046e313 in eval3
    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0)
    at eval.c:2983
#28 0x000000000046df14 in eval2
    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0)
    at eval.c:2857
#29 0x000000000046d90f in eval1
	    (arg=0x7ffdc1091710, rettv=0x7ffdc1091840, evalarg=0x7ffdc10917b0)
    at eval.c:2703
#30 0x000000000046d6ad in eval0_retarg
    (arg=0x2036ca0 "\200\375R15_Quote('\"')", rettv=0x7ffdc1091840, eap=0x0, eva
larg=0x7ffdc10917b0, retarg=0x0) at eval.c:2614
#31 0x000000000046d512 in eval0
    (arg=0x2036ca0 "\200\375R15_Quote('\"')", rettv=0x7ffdc1091840, eap=0x0, eva
larg=0x7ffdc10917b0) at eval.c:2548
#32 0x0000000000469591 in eval_to_string_eap
    (arg=0x2036ca0 "\200\375R15_Quote('\"')", convert=0, eap=0x0, use_simple_fun
ction=0) at eval.c:629
#33 0x000000000046960d in eval_to_string
    (arg=0x2036ca0 "\200\375R15_Quote('\"')", convert=0, use_simple_function=0)
    at eval.c:648
#34 0x000000000050d7a9 in eval_map_expr (mp=0x2038950, c=0) at map.c:1809
#35 0x00000000004dbcb2 in handle_mapping
    (keylenp=0x7ffdc1091a48, timedout=0x7ffdc1091a50, mapdepth=0x7ffdc1091a4c)
    at getchar.c:2961
#36 0x00000000004dc122 in vgetorpeek (advance=1) at getchar.c:3232
#37 0x00000000004d9d47 in vgetc () at getchar.c:1739
#38 0x00000000004da4b3 in safe_vgetc () at getchar.c:1990
#39 0x00000000004b6475 in getcmdline_int
    (firstc=58, count=1, indent=0, clear_ccline=1) at ex_getln.c:1783
#40 0x00000000004b5fc4 in getcmdline
    (firstc=58, count=1, indent=0, do_concat=GETLINE_CONCAT_CONT)
    at ex_getln.c:1551
#41 0x00000000004b835f in getexline
    (c=58, cookie=0x0, indent=0, options=GETLINE_CONCAT_CONT)
    at ex_getln.c:2840
#42 0x000000000049ee39 in do_cmdline (cmdline=0x0, fgetline=
    0x4b831c <getexline>, cookie=0x0, flags=0) at ex_docmd.c:877
#43 0x0000000000545956 in nv_colon (cap=0x7ffdc10926b0) at normal.c:3191
#44 0x0000000000541a51 in normal_cmd (oap=0x7ffdc1092740, toplevel=1)
    at normal.c:939
#45 0x00000000006ff3ef in main_loop (cmdwin=0, noexmode=0) at main.c:1535
#46 0x00000000006fe70f in vim_main2 () at main.c:887
#47 0x00000000006fde26 in main (argc=4, argv=0x7ffdc1092958) at main.c:433
```

---

Interim investigation results:
- It seems that `:def` nesting is necessary for reproduction conditions.
- Here are the actual line breaks.
  `msg_putchar('\n');` of `define_function()` in userfunc.c
  But, I can't relate this behavior to your comment `// don't overwrite the function name`.

In which situations is this line break required?

```c
[Part of define_function() in userfunc.c]

    /*
     * Read the body of the function, until "}", ":endfunction" or ":enddef" is
     * found.
     */
    if (KeyTyped)
    {
	// Check if the function already exists, don't let the user type the
	// whole function before telling him it doesn't work!  For a script we
	// need to skip the body to be able to find what follows.
	if (!eap->skip && !eap->forceit)
	{
	    if (fudi.fd_dict != NULL && fudi.fd_newkey == NULL)
		emsg(_(e_dictionary_entry_already_exists));
	    else if (name != NULL && find_func(name, is_global) != NULL)
		emsg_funcname(e_function_str_already_exists_add_bang_to_replace, name);
	}

	if (!eap->skip && did_emsg)
	    goto erret;

	msg_putchar('\n');	    // don't overwrite the function name
	cmdline_row = msg_row;
    }
```

**Comment by h-east** [comment]
Thanks for the fix!
