### ISSUE TITLE
heap-buffer-overflow when recovering from swap file with corrupted db_line_count

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12276]
### Steps to reproduce

Test case:
```diff
diff --git a/src/testdir/test_recover.vim b/src/testdir/test_recover.vim
index 395eb06ff..b9a14b1bf 100644
--- a/src/testdir/test_recover.vim
+++ b/src/testdir/test_recover.vim
@@ -285,6 +285,20 @@ func Test_recover_corrupted_swap_file()
         \ '???END'], getline(1, '$'))
   bw!
 
+  " set the number of lines in the data block to a large value
+  let b = copy(save_b)
+  if system_64bit
+    let b[8208:8215] = 0z00FFFFFF.FFFFFF00
+  else
+    let b[8208:8211] = 0z00FFFF00
+  endif
+  call writefile(b, sn)
+  call assert_fails('recover Xfile1', 'E312:')
+  call assert_equal('Xfile1', @%)
+  call assert_equal(['??? from here until ???END lines may have been inserted/deleted',
+        \ '???END'], getline(1, '$'))
+  bw!
+
   " use an invalid text start for the lines in a data block
   let b = copy(save_b)
   if system_64bit
```
Test crashes with heap-buffer-overflow

### Expected behaviour

Test does not crash

### Version of Vim

9.0.1464

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

### Logs and stack traces

```
=================================================================
==1570321==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000128100 at pc 0x55e4316005ee bp 0x7ffc62f88260 sp 0x7ffc62f88250
READ of size 4 at 0x621000128100 thread T0
    #0 0x55e4316005ed in ml_recover **/src/memline.c:1647
    #1 0x55e4313d33e4 in ex_recover **/src/ex_docmd.c:6711
    #2 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #3 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #4 0x55e4313949f9 in do_cmdline_cmd **/src/ex_docmd.c:587
    #5 0x55e431b942cb in f_assert_fails **/src/testing.c:619
    #6 0x55e4312f3c66 in call_internal_func **/src/evalfunc.c:3094
    #7 0x55e431c5801a in call_func **/src/userfunc.c:3800
    #8 0x55e431c45051 in get_func_tv **/src/userfunc.c:1935
    #9 0x55e431c6d425 in ex_call_inner **/src/userfunc.c:5911
    #10 0x55e431c70269 in ex_call **/src/userfunc.c:6239
    #11 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #12 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #13 0x55e431c51890 in call_user_func **/src/userfunc.c:3048
    #14 0x55e431c53823 in call_user_func_check **/src/userfunc.c:3220
    #15 0x55e431c57e5b in call_func **/src/userfunc.c:3782
    #16 0x55e431c45051 in get_func_tv **/src/userfunc.c:1935
    #17 0x55e431c6d425 in ex_call_inner **/src/userfunc.c:5911
    #18 0x55e431c70269 in ex_call **/src/userfunc.c:6239
    #19 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #20 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #21 0x55e4312de5cf in ex_execute **/src/eval.c:7303
    #22 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #23 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #24 0x55e431c51890 in call_user_func **/src/userfunc.c:3048
    #25 0x55e431c53823 in call_user_func_check **/src/userfunc.c:3220
    #26 0x55e431c57e5b in call_func **/src/userfunc.c:3782
    #27 0x55e431c45051 in get_func_tv **/src/userfunc.c:1935
    #28 0x55e431c6d425 in ex_call_inner **/src/userfunc.c:5911
    #29 0x55e431c70269 in ex_call **/src/userfunc.c:6239
    #30 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #31 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #32 0x55e431978cf0 in do_source_ext **/src/scriptfile.c:1760
    #33 0x55e43197ac6c in do_source **/src/scriptfile.c:1906
    #34 0x55e4319752a3 in cmd_source **/src/scriptfile.c:1251
    #35 0x55e431975470 in ex_source **/src/scriptfile.c:1277
    #36 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #37 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #38 0x55e4313949f9 in do_cmdline_cmd **/src/ex_docmd.c:587
    #39 0x55e431f9f33a in exe_commands **/src/main.c:3150
    #40 0x55e431f905df in vim_main2 **/src/main.c:782
    #41 0x55e431f8f929 in main **/src/main.c:433
    #42 0x7fad0883c78f  (/usr/lib/libc.so.6+0x2378f)
    #43 0x7fad0883c849 in __libc_start_main (/usr/lib/libc.so.6+0x23849)
    #44 0x55e4310bf114 in _start (**/src/vim+0x1398114)

0x621000128100 is located 0 bytes to the right of 4096-byte region [0x621000127100,0x621000128100)
allocated by thread T0 here:
    #0 0x7fad0a2bfa89 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x55e4310bf5e3 in lalloc **/src/alloc.c:246
    #2 0x55e4310bf396 in alloc **/src/alloc.c:151
    #3 0x55e431fa7cf7 in mf_alloc_bhdr **/src/memfile.c:885
    #4 0x55e431fa47fe in mf_get **/src/memfile.c:434
    #5 0x55e4315fec3d in ml_recover **/src/memline.c:1512
    #6 0x55e4313d33e4 in ex_recover **/src/ex_docmd.c:6711
    #7 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #8 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #9 0x55e4313949f9 in do_cmdline_cmd **/src/ex_docmd.c:587
    #10 0x55e431b942cb in f_assert_fails **/src/testing.c:619
    #11 0x55e4312f3c66 in call_internal_func **/src/evalfunc.c:3094
    #12 0x55e431c5801a in call_func **/src/userfunc.c:3800
    #13 0x55e431c45051 in get_func_tv **/src/userfunc.c:1935
    #14 0x55e431c6d425 in ex_call_inner **/src/userfunc.c:5911
    #15 0x55e431c70269 in ex_call **/src/userfunc.c:6239
    #16 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #17 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #18 0x55e431c51890 in call_user_func **/src/userfunc.c:3048
    #19 0x55e431c53823 in call_user_func_check **/src/userfunc.c:3220
    #20 0x55e431c57e5b in call_func **/src/userfunc.c:3782
    #21 0x55e431c45051 in get_func_tv **/src/userfunc.c:1935
    #22 0x55e431c6d425 in ex_call_inner **/src/userfunc.c:5911
    #23 0x55e431c70269 in ex_call **/src/userfunc.c:6239
    #24 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #25 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #26 0x55e4312de5cf in ex_execute **/src/eval.c:7303
    #27 0x55e4313a3e4d in do_one_cmd **/src/ex_docmd.c:2580
    #28 0x55e431396f25 in do_cmdline **/src/ex_docmd.c:993
    #29 0x55e431c51890 in call_user_func **/src/userfunc.c:3048

SUMMARY: AddressSanitizer: heap-buffer-overflow **/src/memline.c:1647 in ml_recover
Shadow bytes around the buggy address:
  0x0c428001cfd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c428001cfe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c428001cff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c428001d000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c428001d010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c428001d020:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c428001d030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c428001d040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c428001d050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c428001d060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c428001d070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1570321==ABORTING
```

**Comment by zeertzjq** [comment]
Still present on version 9.0.1486
