### ISSUE TITLE
Buffer content is invisible after certain join operation

### ISSUE THREAD

**Issue by zeertzjq** [vim/vim#12368]
### Steps to reproduce

1. Run `vim --clean`
2. Source the following file:
```vim
set nocompatible
31vsplit
6new
setlocal scrolloff=5
call setline(1, ['a'] + repeat([repeat('b', 25)], 81) + repeat([''], 20))
normal! j100gJ
```
3. Buffer content is invisible but it is visible after pressing Ctrl-L

### Expected behaviour

Buffer content is visible

### Version of Vim

9.0.1536

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

**Comment by zeertzjq** [comment]
Bisect to [patch 9.0.1121](https://github.com/vim/vim/commit/db4d88c2adfe8f8122341ac9d6cae27ef78451c8)

**Comment by luukvbaal** [comment]
Running that repro with gdb reveals that skipcol is correctly set in `curs_columns()` but is reset again in `scroll_cursor_halway()`. The assumption that it should be reset there if skipcol doesn't change skipcol seems incorrect. I think it should only be done if 'smoothscroll' is enabled. I'll propose a patch.

```
Old value = 0
New value = 1922
0x00005555556dc1bf in curs_columns (may_scroll=1) at move.c:1351
1351                curwin->w_skipcol = n * width2;
(gdb) bt
#0  0x00005555556dc1bf in curs_columns (may_scroll=1) at move.c:1351
#1  0x00005555556daea0 in validate_cursor () at move.c:829
#2  0x00005555556da747 in update_topline () at move.c:523
#3  0x00005555558cad86 in main_loop (cmdwin=0, noexmode=0) at main.c:1370
#4  0x00005555558ca39a in vim_main2 () at main.c:887
#5  0x00005555558c9a1f in main (argc=5, argv=0x7fffffffd308) at main.c:433

Old value = 1922
New value = 0
reset_skipcol () at move.c:255
255         redraw_later(UPD_SOME_VALID);
(gdb) bt
#0  reset_skipcol () at move.c:255
#1  0x00005555556df5d3 in scroll_cursor_halfway (atend=0, prefer_above=0)
    at move.c:2896
#2  0x00005555556da3d6 in update_topline () at move.c:396
#3  0x00005555555ed9d8 in win_update (wp=0x555555a2e710) at drawscreen.c:2743
#4  0x00005555555e78d0 in update_screen (type_arg=0) at drawscreen.c:324
#5  0x00005555558cae91 in main_loop (cmdwin=0, noexmode=0) at main.c:1427
#6  0x00005555558ca39a in vim_main2 () at main.c:887
#7  0x00005555558c9a1f in main (argc=5, argv=0x7fffffffd308) at main.c:433
```
