### ISSUE TITLE
Crash syncing swapfile in new buffer after saving a buffer with 'cryptmethod' set

### ISSUE THREAD

**Issue by jamessan** [vim/vim#12585]
### Steps to reproduce

1. `:set cryptmethod=xchacha20`
2. `:set key=foobar`
3. Enter some text
4. `:w foo.txt`
5. `:new`
6. Enter some text
7. Exit insert mode and wait 'updatetime' so swap file is created

### Expected behaviour

No crash

### Version of Vim

9..0.1640

### Environment

Debian sid

### Logs and stack traces

```shell
#0  0x0000000000000000 in  ()
#1  0x0000562ca72d3f70 in crypt_encode (state=state@entry=0x562ca8234e60, from=from@entry=0x562ca81f724a "lkjdf", len=len@entry=6, to=<optimized out>, last=last@entry=0) at crypt.c:723
#2  0x0000562ca7382ae8 in ml_encrypt_data (mfp=mfp@entry=0x562ca81b3130, data=data@entry=0x562ca81f6250 "ad", offset=offset@entry=8192, size=size@entry=4096) at memline.c:5495
#3  0x0000562ca74f014e in mf_write_block (mfp=mfp@entry=0x562ca81b3130, hp=0x562ca81b3650, offset=offset@entry=8192, size=size@entry=4096) at memfile.c:1091
#4  0x0000562ca74f0643 in mf_write (mfp=mfp@entry=0x562ca81b3130, hp=hp@entry=0x562ca81b3650) at memfile.c:1032
#5  0x0000562ca74f0e6d in mf_sync (mfp=0x562ca81b3130, flags=4) at memfile.c:558
#6  0x0000562ca737f681 in ml_sync_all (check_file=check_file@entry=0, check_char=check_char@entry=0) at memline.c:2521
#7  0x0000562ca7388e7f in preserve_exit () at misc1.c:2265
#8  0x0000562ca73b70a1 in deathtrap (sigarg=11) at os_unix.c:1229
#9  0x00007f2a44912f90 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000000000 in  ()
#11 0x0000562ca72d3f70 in crypt_encode (state=state@entry=0x562ca81ac630, from=from@entry=0x562ca8238a98 "foo bar", len=len@entry=8, to=<optimized out>, last=last@entry=0) at crypt.c:723
#12 0x0000562ca7382ae8 in ml_encrypt_data (mfp=mfp@entry=0x562ca8232b20, data=data@entry=0x562ca8237aa0 "ad", offset=offset@entry=8192, size=size@entry=4096) at memline.c:5495
#13 0x0000562ca74f014e in mf_write_block (mfp=mfp@entry=0x562ca8232b20, hp=0x562ca82347a0, offset=offset@entry=8192, size=size@entry=4096) at memfile.c:1091
#14 0x0000562ca74f0643 in mf_write (mfp=mfp@entry=0x562ca8232b20, hp=hp@entry=0x562ca82347a0) at memfile.c:1032
#15 0x0000562ca74f0e6d in mf_sync (mfp=0x562ca8232b20, flags=2) at memfile.c:558
#16 0x0000562ca737f681 in ml_sync_all (check_file=check_file@entry=1, check_char=check_char@entry=1) at memline.c:2521
#17 0x0000562ca7347550 in updatescript (c=c@entry=0) at getchar.c:1642
#18 0x0000562ca734879d in before_blocking () at getchar.c:1619
#19 0x0000562ca7469e97 in inchar_loop
    (buf=buf@entry=0x562ca75c9d9a <typebuf_init+58> "", maxlen=maxlen@entry=68, wtime=wtime@entry=-1, tb_change_cnt=tb_change_cnt@entry=136, wait_func=wait_func@entry=0x562ca73b58d3 <WaitForChar>, resize_func=resize_func@entry=0x562ca73b5806 <resize_func>) at ui.c:355
#20 0x0000562ca73b6bbb in mch_inchar (buf=buf@entry=0x562ca75c9d9a <typebuf_init+58> "", maxlen=maxlen@entry=68, wtime=wtime@entry=-1, tb_change_cnt=tb_change_cnt@entry=136) at os_unix.c:466
#21 0x0000562ca74698dd in ui_inchar (buf=buf@entry=0x562ca75c9d9a <typebuf_init+58> "", maxlen=maxlen@entry=68, wtime=wtime@entry=-1, tb_change_cnt=tb_change_cnt@entry=136) at ui.c:232
#22 0x0000562ca7348e0e in inchar (buf=0x562ca75c9d9a <typebuf_init+58> "", maxlen=206, wait_time=-1) at getchar.c:3803
#23 0x0000562ca734a624 in vgetorpeek (advance=advance@entry=1) at getchar.c:3583
#24 0x0000562ca734a931 in vgetc () at getchar.c:1774
#25 0x0000562ca734ae9f in safe_vgetc () at getchar.c:2025
#26 0x0000562ca739d0ed in normal_cmd (oap=oap@entry=0x7ffc6da24b00, toplevel=toplevel@entry=1) at normal.c:751
#27 0x0000562ca74ece13 in main_loop (cmdwin=cmdwin@entry=0, noexmode=noexmode@entry=0) at main.c:1562
#28 0x0000562ca74ee0db in vim_main2 () at main.c:895
#29 0x0000562ca74efd54 in main (argc=2, argv=0x7ffc6da24cf8) at main.c:441
```

**Comment by chrisbra** [comment]
I have created #12591 to fix this. It basically adds some safety checks to guard against this.
