### ISSUE TITLE
E315: ml_get: Invalid lnum when deleting many lines till the end of the file

### ISSUE THREAD

**Issue by oldherl** [vim/vim#13568]
### Steps to reproduce

1. Open the attached [box.txt](https://github.com/vim/vim/files/13454484/box.txt)
2. `V/prepare`[Enter][Up]`d249GV`[PageDown][PageDown][PageDown]...until it reaches the end of the file, then `d`
3. Note that the screen is now blank, the remaining 248 lines of texts are all above the visible area
4. Press [PageUp]
5. Get this error:
> E340: Internal error; if you can reproduce please report a bug                                      
> E315: ml_get: Invalid lnum: 600
> Press ENTER or type command to continue

Note that I can't reproduce it with `vim --clean`, but if I empty my vimrc and run `vim`, it always reproduces.

### Expected behaviour

Should not get this error

### Version of Vim

9.0.2121

### Environment

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 22 2023 21:16:40)
Included patches: 1-2121
Compiled by Arch Linux

Running in konsole, TERM=xterm-256color

**Comment by zeertzjq** [comment]
With empty vimrc there may still be plugin in 'runtimepath' that are run.

**Comment by lilydjwg** [comment]
Yes, one of them is `matchparen` which appeared (autocmd CursorMoved* & TextChanged) during my attempt to debug.

**Comment by chrisbra** [comment]
I can reproduce it using `vim -u NONE -N -c ':source $VIMPLUGIN/plugin/matchparen.vim' box.txt`

I got the following stack trace:
```
(gdb) bt
#0  siemsg (
    s=0x555555939820 <e_ml_get_invalid_lnum_nr> "E315: ml_get: Invalid lnum: %ld") at message.c:856
#1  0x00005555556a5a65 in ml_get_buf (buf=0x55555595f720, lnum=600,
    will_change=0) at memline.c:2702
#2  0x00005555556b0d6c in plines_win_nofold (wp=0x55555595cf70, lnum=600)
    at misc1.c:410
#3  0x00005555556b0d16 in plines_win_nofill (wp=0x55555595cf70, lnum=600,
    limit_winheight=1) at misc1.c:391
#4  0x00005555556b0c8a in plines_nofill (lnum=600) at misc1.c:361
#5  0x00005555556c3edd in get_scroll_overlap (lp=0x7fffffffda90, dir=1)
    at move.c:3353
#6  0x00005555556c3aa4 in onepage (dir=-1, count=1) at move.c:3202
#7  0x00005555556c7ec1 in nv_page (cap=0x7fffffffdb40) at normal.c:2069
#8  0x00005555556c613f in normal_cmd (oap=0x7fffffffdbe0, toplevel=1)
    at normal.c:949
#9  0x0000555555882f34 in main_loop (cmdwin=0, noexmode=0) at main.c:1562
#10 0x000055555588227b in vim_main2 () at main.c:895
#11 0x0000555555881a1a in main (argc=4, argv=0x7fffffffde18) at main.c:441
(gdb)
```

looks like `curwin->w_topline` has become invalid. Not sure where to validate it first.

**Comment by chrisbra** [comment]
this seems to fix it:
```patch
diff --git a/src/window.c b/src/window.c
index 55ce31c88..296af65e7 100644
--- a/src/window.c
+++ b/src/window.c
@@ -7442,11 +7442,17 @@ reset_lnums(void)
            // Restore the value if the autocommand didn't change it and it was
            // set.
            if (EQUAL_POS(wp->w_save_cursor.w_cursor_corr, wp->w_cursor)
-                                 && wp->w_save_cursor.w_cursor_save.lnum != 0)
+                                 && wp->w_save_cursor.w_cursor_save.lnum != 0
+                                 && wp->w_save_cursor.w_cursor_save.lnum <=
+                                    wp->w_buffer->b_ml.ml_line_count)
                wp->w_cursor = wp->w_save_cursor.w_cursor_save;
            if (wp->w_save_cursor.w_topline_corr == wp->w_topline
-                                     && wp->w_save_cursor.w_topline_save != 0)
+                                 && wp->w_save_cursor.w_topline_save != 0
+                                 && wp->w_save_cursor.w_topline_save <=
+                                    wp->w_buffer->b_ml.ml_line_count)
                wp->w_topline = wp->w_save_cursor.w_topline_save;
+           if (wp->w_save_cursor.w_topline_save > wp->w_buffer->b_ml.ml_line_count)
+               wp->w_valid &= ~VALID_TOPLINE;
        }
 }
```

**Comment by chrisbra** [comment]
can you please verify with PR #13578

**Comment by lilydjwg** [comment]
I can verify that pr fixes the issue.

**Comment by oldherl** [comment]
Yes, that fixes the issue.
