### ISSUE TITLE
`autocmd_get()` segmentation fault

### ISSUE THREAD

**Issue by noscript** [vim/vim#14937]
### Steps to reproduce

1. Create `~/bug.vim`:
```vim
vim9script

def S_on_BufWritePre()
  var acmd = {
    group: 'MyGroup',
    event: 'User',
    pattern: 'MyPattern',
  }

  acmd.cmd = 'echo'
  autocmd_add([acmd])

  unlet acmd.cmd
  autocmd_delete([acmd])

  autocmd_get(acmd) # segfaults
enddef

autocmd BufWritePre <buffer> S_on_BufWritePre()
```
3. Run Vim: `vim -g -f --clean +'so ~/bug.vim' ~/bug.vim`
4. Write the buffer to disk: `:w`

### Expected behaviour

Does not crash.

### Version of Vim

9.1.0470

### Environment

OS: Debian 12
Terminal: GUI

### Logs and stack traces

```shell
Thread 1 "vim" received signal SIGSEGV, Segmentation fault.
0x00007ffff6d2262b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6d2262b in  () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005555555a5230 in f_autocmd_get (argvars=0x7fffffff9bb0, rettv=0x55555638bcd0) at autocmd.c:3397
#2  0x000055555560bbcd in call_internal_func_by_idx (idx=28, argvars=0x7fffffff9bb0, rettv=0x55555638bcd0) at evalfunc.c:3267
#3  0x0000555555833c83 in call_bfunc (func_idx=28, argcount=1, ectx=0x7fffffffad40) at vim9execute.c:1335
#4  0x000055555583b10f in exec_instructions (ectx=0x7fffffffad40) at vim9execute.c:4399
#5  0x0000555555840f4a in call_def_function (ufunc=0x5555563079b0, argc_arg=0, argv=0x7fffffffb7c0, flags=0, partial=0x0, object=0x0, funccal=0x55555638ad70, rettv=0x7fffffffc1b0) at vim9execute.c:6346
#6  0x00005555558105aa in call_user_func (fp=0x5555563079b0, argcount=0, argvars=0x7fffffffb7c0, rettv=0x7fffffffc1b0, funcexe=0x7fffffffb970, selfdict=0x0) at userfunc.c:2891
#7  0x000055555581167e in call_user_func_check (fp=0x5555563079b0, argcount=0, argvars=0x7fffffffb7c0, rettv=0x7fffffffc1b0, funcexe=0x7fffffffb970, selfdict=0x0) at userfunc.c:3324
#8  0x0000555555812666 in call_func (funcname=0x555556383c30 "S_on_BufWritePre()", len=16, rettv=0x7fffffffc1b0, argcount_in=0, argvars_in=0x7fffffffb7c0, funcexe=0x7fffffffb970) at userfunc.c:3948
#9  0x000055555580ec7f in get_func_tv (name=0x555556383c30 "S_on_BufWritePre()", len=16, rettv=0x7fffffffc1b0, arg=0x7fffffffc088, evalarg=0x7fffffffc120, funcexe=0x7fffffffb970) at userfunc.c:2038
#10 0x00005555555fef61 in eval_func (arg=0x7fffffffc088, evalarg=0x7fffffffc120, name=0x555556383f40 "S_on_BufWritePre()", name_len=16, rettv=0x7fffffffc1b0, flags=1, basetv=0x0) at eval.c:3021
#11 0x0000555555602616 in eval9_var_func_name (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120, evaluate=1, name_start=0x7fffffffbac0) at eval.c:4845
#12 0x0000555555602a74 in eval9 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120, want_string=0) at eval.c:5052
#13 0x0000555555601c11 in eval8 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120, want_string=0) at eval.c:4546
#14 0x0000555555601848 in eval7 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120, want_string=0) at eval.c:4445
#15 0x0000555555601217 in eval6 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120) at eval.c:4205
#16 0x0000555555600c59 in eval5 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120) at eval.c:3999
#17 0x0000555555600678 in eval4 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120) at eval.c:3816
#18 0x0000555555600263 in eval3 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120) at eval.c:3677
#19 0x00005555555ffe64 in eval2 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120) at eval.c:3551
#20 0x00005555555ff85a in eval1 (arg=0x7fffffffc088, rettv=0x7fffffffc1b0, evalarg=0x7fffffffc120) at eval.c:3397
#21 0x00005555555ff608 in eval0_retarg (arg=0x555556383f40 "S_on_BufWritePre()", rettv=0x7fffffffc1b0, eap=0x7fffffffc310, evalarg=0x7fffffffc120, retarg=0x0) at eval.c:3306
#22 0x00005555555ff47a in eval0 (arg=0x555556383f40 "S_on_BufWritePre()", rettv=0x7fffffffc1b0, eap=0x7fffffffc310, evalarg=0x7fffffffc120) at eval.c:3241
#23 0x0000555555646e2f in ex_eval (eap=0x7fffffffc310) at ex_eval.c:993
#24 0x000055555563751f in do_one_cmd (cmdlinep=0x7fffffffcb38, flags=7, cstack=0x7fffffffc500, fgetline=0x5555555a3d88 <getnextac>, cookie=0x7fffffffcc90) at ex_docmd.c:2620
#25 0x000055555563456b in do_cmdline (cmdline=0x0, fgetline=0x5555555a3d88 <getnextac>, cookie=0x7fffffffcc90, flags=7) at ex_docmd.c:1032
#26 0x00005555555a3556 in apply_autocmds_group (event=EVENT_BUFWRITEPRE, fname=0x555556270280 "~/bug.vim", fname_io=0x5555559c18e0 "~/bug.vim", force=0, group=-3, buf=0x5555559bbef0, eap=0x7fffffffd570) at autocmd.c:2403
#27 0x00005555555a2b21 in apply_autocmds_exarg (event=EVENT_BUFWRITEPRE, fname=0x5555559c18e0 "~/bug.vim", fname_io=0x5555559c18e0 "~/bug.vim", force=0, buf=0x5555559bbef0, eap=0x7fffffffd570) at autocmd.c:1883
#28 0x000055555586e13d in buf_write (buf=0x5555559bbef0, fname=0x5555559c18e0 "~/bug.vim", sfname=0x5555559c18e0 "~/bug.vim", start=1, end=19, eap=0x7fffffffd570, append=0, forceit=0, reset_changed=1, filtering=0) at bufwrite.c:855
#29 0x000055555562b3c4 in do_write (eap=0x7fffffffd570) at ex_cmds.c:2093
#30 0x000055555562ad83 in ex_write (eap=0x7fffffffd570) at ex_cmds.c:1890
#31 0x000055555563751f in do_one_cmd (cmdlinep=0x7fffffffdd98, flags=0, cstack=0x7fffffffd760, fgetline=0x55555564eda4 <getexline>, cookie=0x0) at ex_docmd.c:2620
#32 0x000055555563456b in do_cmdline (cmdline=0x0, fgetline=0x55555564eda4 <getexline>, cookie=0x0, flags=0) at ex_docmd.c:1032
#33 0x00005555556e2cba in nv_colon (cap=0x7fffffffdec0) at normal.c:3166
#34 0x00005555556dedc6 in normal_cmd (oap=0x7fffffffdf60, toplevel=1) at normal.c:949
#35 0x00005555558bf72b in main_loop (cmdwin=0, noexmode=0) at main.c:1562
#36 0x00005555558be9e7 in vim_main2 () at main.c:895
#37 0x00005555558be06c in main (argc=6, argv=0x7fffffffe198) at main.c:441
```

**Comment by noscript** [comment]
Thank you!
