### ISSUE TITLE
Error while importing socket python module

### ISSUE THREAD

**Issue by abdelmaged** [vim/vim#15214]
### Steps to reproduce

vim --cmd "py3 import socket"

### Expected behaviour

No error when importing the module

### Version of Vim

9.1 Included patches: 1-558

### Environment

OS: Centos 7.9
Python: 3.12.4

### Logs and stack traces

```shell
pip_system_certs: ERROR: could not register module: module _opcode uses unknown slot ID 3
Error detected while processing pre-vimrc command line:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/bin/python/3.12.4/lib/python3.12/socket.py", line 52, in <module>
    import _socket
ImportError: ~/bin/python/3.12.4/lib/python3.12/lib-dynload/_socket.cpython-312-x86_64-linux-gnu.so: undefined symbol: PyErr_GetRaisedException                                                     Press ENTER or type command to continue
```

**Comment by chrisbra** [comment]
how did you compile Vim/Python? This seems to be an error on the python side, according to [here](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_GetRaisedException) this is part of python3.12, stable API.

**Comment by abdelmaged** [comment]
I've installed python with following configurations:
```
'--prefix=~/bin/python/3.12.4' '--with-openssl=~/lib/openssl-3.0.0' '--with-openssl-rpath=auto' '--enable-shared'
```

And installed vim with following configurations:
```
env LDFLAGS="-rdynamic" ./configure --prefix=~/bin/vim/9.1.0558 --enable-python3interp=yes
```

**Comment by chrisbra** [comment]
I don't know, but I wonder if you have a general python problem, also regarding #15212

BTW: I would try to compile using `--with-python3-stable-abi=3.12`.

**Comment by abdelmaged** [comment]
I've just tried changing python version to 3.10.14, and no error was produced when importing socket or traceback python modules.
It seems to me that vim is incompatible with newer python versions like 3.12.4

**Comment by chrisbra** [comment]
I checked on a Fedora system which comes with Vim 9.1.452 with python 3.12.4 and both issues did not occur.

**Comment by abdelmaged** [comment]
What was the build for configurations for vim/python ?

I just tried as well with Vim 9.1.0452 and python 3.12.4, got same error from socket module, and different error when importing traceback 
```
pip_system_certs: ERROR: could not register module: module _opcode uses unknown slot ID 3
```

**Comment by chrisbra** [comment]
That's a default Fedora install, I don't know how this was build. Well, for Vim, I can provide the compile flags:
```
:version
VIM - Vi IMproved 9.1 (2024 Jan 02 kompiliert am May 31 2024 00:00:00)
Inklusive der Patches: 1-452
Verändert von <bugzilla@redhat.com>
Übersetzt von <bugzilla@redhat.com>
Riesige Version ohne GUI. Ein- (+) oder ausschließlich (-) der Eigenschaften:
+acl               +cmdline_hist      +ex_extra          +jumplist          +mouse_dec         +perl/dyn          +sodium            +textobjects       +wildmenu
+arabic            +cmdline_info      +extra_search      +keymap            +mouse_gpm         +persistent_undo   -sound             +textprop          +windows
+autocmd           +comments          -farsi             +lambda            -mouse_jsbterm     +popupwin          +spell             +timers            +writebackup
+autochdir         +conceal           +file_in_path      +langmap           +mouse_netterm     +postscript        +startuptime       +title             -X11
-autoservername    +cryptv            +find_in_path      +libcall           +mouse_sgr         +printer           +statusline        -toolbar           +xattr
-balloon_eval      +cscope            +float             +linebreak         -mouse_sysmouse    +profile           -sun_workshop      +user_commands     -xfontset
+balloon_eval_term +cursorbind        +folding           +lispindent        +mouse_urxvt       -python            +syntax            +vartabs           -xim
-browse            +cursorshape       -footer            +listcmds          +mouse_xterm       +python3/dyn       +tag_binary        +vertsplit         -xpm
++builtin_terms    +dialog_con        +fork()            +localmap          +multi_byte        +quickfix          -tag_old_static    +vim9script        -xsmp
+byte_offset       +diff              +gettext           +lua/dyn           +multi_lang        +reltime           -tag_any_white     +viminfo           -xterm_clipboard
+channel           +digraphs          -hangul_input      +menu              -mzscheme          +rightleft         -tcl               +virtualedit       -xterm_save
+cindent           -dnd               +iconv             +mksession         +netbeans_intg     +ruby/dyn          +termguicolors     +visual
-clientserver      -ebcdic            +insert_expand     +modify_fname      +num64             +scrollbind        +terminal          +visualextra
-clipboard         +emacs_tags        +ipv6              +mouse             +packages          +signs             +terminfo          +vreplace
+cmdline_compl     +eval              +job               -mouseshape        +path_extra        +smartindent       +termresponse      +wildignore
          System-vimrc-Datei: "/etc/vimrc"
        Benutzer-vimrc-Datei: "$HOME/.vimrc"
 zweite Benutzer-vimrc-Datei: "~/.vim/vimrc"
 dritte Benutzer-vimrc-Datei: "~/.config/vim/vimrc"
         Benutzer-exrc-Datei: "$HOME/.exrc"
      defaults Datei: "$VIMRUNTIME/defaults.vim"
     Voreinstellung für $VIM: "/usr/share/vim"
Übersetzt: gcc -c -I. -Iproto -DHAVE_CONFIG_H -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-
D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchro
nous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DSYS_VIMRC_FILE=/etc/vimrc -D_RE
ENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linken: gcc -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,-z,now -Wl,--build-id=sha1 -Wl,-z,relro -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl
,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -specs=/us
r/lib/rpm/redhat/redhat-package-notes -L/usr/local/lib -o vim -lm -lselinux -lncurses -lsodium -lacl -lattr -lgpm
```

Build log is here: https://kojipkgs.fedoraproject.org//packages/vim/9.1.544/1.fc39/data/logs/i686/build.log

**Comment by abdelmaged** [comment]
I tried to build vim following configuration instead:
```
 ./configure --prefix=~/bin/vim/9.1.0558 --enable-python3interp=dynamic
```
Difference is setting `--enable-python3interp` to `dynamic` instead of `yes` like it was configured in Fedora build.log

This resolved the two issues when importing the python modules.

**Comment by chrisbra** [comment]
not sure if there is anything wrong here or actionable. Let me close it, since nobody else reported this problem.
