### ISSUE TITLE
Error while importing tracback python module

### ISSUE THREAD

**Issue by abdelmaged** [vim/vim#15212]
### Steps to reproduce

vim --cmd "py3 import traceback" 

### Expected behaviour

No error to import traceback

### Version of Vim

9.1 Included patches: 1-558

### Environment

OS: Centos 7.9
Python: 3.12.4

### Logs and stack traces

```shell
Error detected while processing pre-vimrc command line:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/bin/python/3.12.4/lib/python3.12/traceback.py", line 745
    f'Ignored error getting __notes__: {_safe_string(e, '__notes__', repr)}']
                                                         ^^^^^^^^^
SyntaxError: f-string: unmatched '('
Press ENTER or type command to continue
```

**Comment by chrisbra** [comment]
Works for me using Python3.11

**Comment by chrisbra** [comment]
not reproducible
