### ISSUE TITLE
double free detected

### ISSUE THREAD

**Issue by SuyueGuo** [vim/vim#15403]
### Steps to reproduce

1. compile vim with ASAN
```
CFLAGS="-fsanitize=address -g" CXXFLAGS="-fsanitize=address -g" LDFLAGS="-fsanitize=address" ./configure --with-features=huge --enable-gui=none

export ASAN_OPTIONS=abort_on_error=1:detect_leaks=1:malloc_context_size=25:symbolize=1:log_path=./asan.log

make
```

2. exec with following command
```
/home/vim-debug/src/vim -u NONE -X -Z -e -s -S crash_case -c ':qa!'
```

following is the crash_case tar file, please extract crash_case from the tar file:
[crash_case.tar.gz](https://github.com/user-attachments/files/16441523/crash_case.tar.gz)

```
tar -xzvf crash_case.tar.gz
```

### Expected behaviour

the program should exit normally 

### Version of Vim

:version VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jul 31 2024 11:53:37) Included patches: 1-636 Compiled by root@zyq004 Huge version without GUI.  Features included (+) or not (-): +acl               +cindent           +cursorshape       +file_in_path      +job               +menu              +mouse_urxvt       +popupwin          +signs             -tag_any_white     +user_commands     +windows +arabic            +clientserver      +dialog_con        +find_in_path      +jumplist          +mksession         +mouse_xterm       +postscript        +smartindent       -tcl               +vartabs           +writebackup +autocmd           +clipboard         +diff              +float             +keymap            +modify_fname      +multi_byte        +printer           -sodium            +termguicolors     +vertsplit         +X11 +autochdir         +cmdline_compl     +digraphs          +folding           +lambda            +mouse             +multi_lang        +profile           -sound             +terminal          +vim9script        +xattr -autoservername    +cmdline_hist      -dnd               -footer            +langmap           -mouseshape        -mzscheme          -python            +spell             +terminfo          +viminfo           +xfontset -balloon_eval      +cmdline_info      -ebcdic            +fork()            +libcall           +mouse_dec         +netbeans_intg     -python3           +startuptime       +termresponse      +virtualedit       -xim +balloon_eval_term +comments          +emacs_tags        +gettext           +linebreak         -mouse_gpm         +num64             +quickfix          +statusline        +textobjects       +visual            -xpm -browse            +conceal           +eval              -hangul_input      +lispindent        -mouse_jsbterm     +packages          +reltime           -sun_workshop      +textprop          +visualextra       +xsmp_interact ++builtin_terms    +cryptv            +ex_extra          +iconv             +listcmds          +mouse_netterm     +path_extra        +rightleft         +syntax            +timers            +vreplace          +xterm_clipboard +byte_offset       +cscope            +extra_search      +insert_expand     +localmap          +mouse_sgr         -perl              -ruby              +tag_binary        +title             +wildignore        -xterm_save +channel           +cursorbind        -farsi             +ipv6              -lua               -mouse_sysmouse    +persistent_undo   +scrollbind        -tag_old_static    -toolbar           +wildmenu    system vimrc file: "$VIM/vimrc"      user vimrc file: "$HOME/.vimrc"  2nd user vimrc file: "~/.vim/vimrc"  3rd user vimrc file: "~/.config/vim/vimrc"       user exrc file: "$HOME/.exrc"        defaults file: "$VIMRUNTIME/defaults.vim"   fall-back for $VIM: "/usr/local/share/vim" Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -fsanitize=address -g -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 Linking: gcc -fsanitize=address -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux

### Environment

OS: Ubuntu 22.04
terminal: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
$TERM: xterm
shell: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Logs and stack traces

```shell
=================================================================
==23432==ERROR: AddressSanitizer: attempting double-free on 0x602000018f10 in thread T0:
    #0 0x7fe79f043537 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127
    #1 0x55acf467eea7 in vim_free /home/vim-debug/src/alloc.c:616
    #2 0x55acf48275ca in dialog_changed /home/vim-debug/src/ex_cmds2.c:202
    #3 0x55acf46a28e8 in do_buffer_ext /home/vim-debug/src/buffer.c:1452
    #4 0x55acf46a3e16 in do_buffer /home/vim-debug/src/buffer.c:1690
    #5 0x55acf46a3f23 in do_bufdel /home/vim-debug/src/buffer.c:1724
    #6 0x55acf484c337 in ex_bunload /home/vim-debug/src/ex_docmd.c:5714
    #7 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #8 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #9 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #10 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #11 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #12 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #13 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #14 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #15 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #16 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #17 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #18 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #19 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #20 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #21 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #22 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #23 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #24 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #25 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #26 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #27 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #28 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #29 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #30 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #31 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #32 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #33 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #34 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #35 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #36 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #37 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #38 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #39 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #40 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #41 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #42 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #43 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #44 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #45 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #46 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #47 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #48 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #49 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #50 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #51 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #52 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #53 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #54 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #55 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #56 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #57 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #58 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #59 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #60 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #61 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #62 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #63 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #64 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #65 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #66 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #67 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #68 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #69 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #70 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #71 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #72 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #73 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #74 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #75 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #76 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #77 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #78 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #79 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #80 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #81 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #82 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #83 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #84 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #85 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #86 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #87 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #88 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #89 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #90 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #91 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #92 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #93 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #94 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #95 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #96 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #97 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #98 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #99 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #100 0x55acf4b8a256 in do_source /home/vim-debug/src/scriptfile.c:1952
    #101 0x55acf4b86b47 in cmd_source /home/vim-debug/src/scriptfile.c:1298
    #102 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #103 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #104 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #105 0x55acf482c8e4 in do_cmdline_cmd /home/vim-debug/src/ex_docmd.c:622
    #106 0x55acf4eae8b4 in exe_commands /home/vim-debug/src/main.c:3173
    #107 0x55acf4ea7264 in vim_main2 /home/vim-debug/src/main.c:790
    #108 0x55acf4ea6aa5 in main /home/vim-debug/src/main.c:441
    #109 0x7fe79ea72d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #110 0x7fe79ea72e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #111 0x55acf467e764 in _start (/home/vim-debug/src/vim+0x164764)

0x602000018f10 is located 0 bytes inside of 9-byte region [0x602000018f10,0x602000018f19)
freed by thread T0 here:
    #0 0x7fe79f043537 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127
    #1 0x55acf467eea7 in vim_free /home/vim-debug/src/alloc.c:616
    #2 0x55acf48274ac in dialog_changed /home/vim-debug/src/ex_cmds2.c:200
    #3 0x55acf46a28e8 in do_buffer_ext /home/vim-debug/src/buffer.c:1452
    #4 0x55acf46a3e16 in do_buffer /home/vim-debug/src/buffer.c:1690
    #5 0x55acf46a3f23 in do_bufdel /home/vim-debug/src/buffer.c:1724
    #6 0x55acf484c337 in ex_bunload /home/vim-debug/src/ex_docmd.c:5714
    #7 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #8 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #9 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #10 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #11 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #12 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #13 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #14 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #15 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #16 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #17 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #18 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #19 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #20 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #21 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #22 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #23 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #24 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806

previously allocated by thread T0 here:
    #0 0x7fe79f043887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55acf467ebad in lalloc /home/vim-debug/src/alloc.c:246
    #2 0x55acf467e99b in alloc /home/vim-debug/src/alloc.c:151
    #3 0x55acf4c20281 in vim_strsave /home/vim-debug/src/strings.c:27
    #4 0x55acf46ae27d in buf_set_name /home/vim-debug/src/buffer.c:3617
    #5 0x55acf482739e in dialog_changed /home/vim-debug/src/ex_cmds2.c:188
    #6 0x55acf46a28e8 in do_buffer_ext /home/vim-debug/src/buffer.c:1452
    #7 0x55acf46a3e16 in do_buffer /home/vim-debug/src/buffer.c:1690
    #8 0x55acf46a3f23 in do_bufdel /home/vim-debug/src/buffer.c:1724
    #9 0x55acf484c337 in ex_bunload /home/vim-debug/src/ex_docmd.c:5714
    #10 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #11 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #12 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #13 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #14 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #15 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #16 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #17 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #18 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #19 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324
    #20 0x55acf483770e in do_one_cmd /home/vim-debug/src/ex_docmd.c:2616
    #21 0x55acf482e543 in do_cmdline /home/vim-debug/src/ex_docmd.c:1028
    #22 0x55acf4b88faf in do_source_ext /home/vim-debug/src/scriptfile.c:1806
    #23 0x55acf4b86983 in cmd_source /home/vim-debug/src/scriptfile.c:1281
    #24 0x55acf4b86bbe in ex_source /home/vim-debug/src/scriptfile.c:1324

SUMMARY: AddressSanitizer: double-free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127 in __interceptor_free
==23432==ABORTING
```

**Comment by chrisbra** [comment]
Thanks, I see the issue. Can you please verify that the following patch fixes it?
```diff
diff --git a/src/ex_cmds2.c b/src/ex_cmds2.c
index ce30b8d39..94df2c101 100644
--- a/src/ex_cmds2.c
+++ b/src/ex_cmds2.c
@@ -197,7 +197,8 @@ dialog_changed(
        // restore to empty when write failed
        if (empty_bufname)
        {
-           VIM_CLEAR(buf->b_fname);
+           if (buf->b_fname != buf->b_sfname)
+               VIM_CLEAR(buf->b_fname);
            VIM_CLEAR(buf->b_ffname);
            VIM_CLEAR(buf->b_sfname);
            unchanged(buf, TRUE, FALSE);
```

**Comment by SuyueGuo** [comment]
Thanks for the patch, I re-compile Vim with it and the program can exit normally now!
