### ISSUE TITLE
signed integer overflow in get_address()

### ISSUE THREAD

**Issue by geeknik** [vim/vim#2248]
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -S test031 ':qa!'

```
ex_docmd.c:4678:12: runtime error: signed integer overflow: 8 + 9223372036854775807 cannot be represented in type 'long'
    #0 0x80e3e6 in get_address /root/vim/src/ex_docmd.c:4678:12
    #1 0x7ca190 in do_one_cmd /root/vim/src/ex_docmd.c:2114:9
    #2 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #3 0x7ae076 in do_source /root/vim/src/ex_cmds2.c:4355:5
    #4 0x7ab31c in cmd_source /root/vim/src/ex_cmds2.c:3968:14
    #5 0x7ab31c in ex_source /root/vim/src/ex_cmds2.c:3943
    #6 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #7 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #8 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
    #9 0x13f138f in vim_main2 /root/vim/src/main.c:799
    #10 0x13e5d3d in main /root/vim/src/main.c:415:12
    #11 0x7f7a3bf793f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #12 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ex_docmd.c:4678:12 
```

[test031.gz](https://github.com/vim/vim/files/1418719/test031.gz)

**Comment by brammool** [comment]
Should be taken care of by Patch 8.2.3659
