### ISSUE TITLE
signed integer overflow in do_sub()

### ISSUE THREAD

**Issue by geeknik** [vim/vim#2249]
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -S test014 ':qa!'

```
ex_cmds.c:5031:13: runtime error: signed integer overflow: 9223372036854775807 + 8 cannot be represented in type 'long'
    #0 0x75208f in do_sub /root/vim/src/ex_cmds.c:5031:13
    #1 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #2 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #3 0x7ae076 in do_source /root/vim/src/ex_cmds2.c:4355:5
    #4 0x7ab31c in cmd_source /root/vim/src/ex_cmds2.c:3968:14
    #5 0x7ab31c in ex_source /root/vim/src/ex_cmds2.c:3943
    #6 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #7 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #8 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
    #9 0x13f138f in vim_main2 /root/vim/src/main.c:799
    #10 0x13e5d3d in main /root/vim/src/main.c:415:12
    #11 0x7fa9296b13f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #12 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ex_cmds.c:5031:13
```
[test014.gz](https://github.com/vim/vim/files/1418738/test014.gz)

**Comment by lacygoill** [comment]
Fixed in patch [8.1.0953](https://github.com/vim/vim/releases/tag/v8.1.0953).

**Comment by lacygoill** [comment]
A relevant todo item can be removed (and another similar one):
```diff
diff --git a/runtime/doc/todo.txt b/runtime/doc/todo.txt
index 1772aa1e9..65eca83c5 100644
--- a/runtime/doc/todo.txt
+++ b/runtime/doc/todo.txt
@@ -846,9 +846,7 @@ window for the buffer.
 Win32 key codes are messy.  Mike Williams tried to fix that, but now old
 mappings no longer work.  Create a new terminal for the better solution?
 
-Compiler warnings (geeknik, 2017 Oct 26):
-- signed integer overflow in do_sub() (#2249)
-- signed integer overflow in get_address() (#2248)
+Compiler warning (geeknik, 2017 Oct 26):
 - undefined left shift in get_string_tv() (#2250)
 
 Add Native language protocol server (LSP) support. (Yegappan Lakshmanan, 2018
```

**Comment by brammool** [comment]
I'll remove those lines from the todo list, thanks.
