### ISSUE TITLE
signed integer overflow in nfa_regatom()

### ISSUE THREAD

**Issue by geeknik** [vim/vim#2251]
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -S test022 ':qa!'

```
regexp_nfa.c:1610:14: runtime error: signed integer overflow: 700000000 * 10 cannot be represented in type 'int'
    #0 0xe464b0 in nfa_regatom /root/vim/src/./regexp_nfa.c:1610:14
    #1 0xe3b5b5 in nfa_regpiece /root/vim/src/./regexp_nfa.c:2055:11
    #2 0xe3b5b5 in nfa_regconcat /root/vim/src/./regexp_nfa.c:2296
    #3 0xe3ac67 in nfa_regbranch /root/vim/src/./regexp_nfa.c:2330:9
    #4 0xe3a114 in nfa_reg /root/vim/src/./regexp_nfa.c:2390:9
    #5 0xe2ff45 in re2post /root/vim/src/./regexp_nfa.c:2805:9
    #6 0xe2ff45 in nfa_regcomp /root/vim/src/./regexp_nfa.c:7257
    #7 0xdcc271 in vim_regcomp /root/vim/src/regexp.c:8153:16
    #8 0xf66486 in search_regcomp /root/vim/src/search.c:223:25
    #9 0x754919 in ex_global /root/vim/src/ex_cmds.c:6000:9
    #10 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #11 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #12 0x7ae076 in do_source /root/vim/src/ex_cmds2.c:4355:5
    #13 0x7ab31c in cmd_source /root/vim/src/ex_cmds2.c:3968:14
    #14 0x7ab31c in ex_source /root/vim/src/ex_cmds2.c:3943
    #15 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #16 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #17 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
    #18 0x13f138f in vim_main2 /root/vim/src/main.c:799
    #19 0x13e5d3d in main /root/vim/src/main.c:415:12
    #20 0x7f67ec2ef3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #21 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior regexp_nfa.c:1610:14
```
[test022.gz](https://github.com/vim/vim/files/1418759/test022.gz)

**Comment by chrisbra** [comment]
How about the following patch:
```patch
diff --git a/src/regexp_nfa.c b/src/regexp_nfa.c
index 23ae51695..c78f3ab89 100644
--- a/src/regexp_nfa.c
+++ b/src/regexp_nfa.c
@@ -1601,15 +1601,15 @@ nfa_regatom(void)

                default:
                    {
-                       int     n = 0;
+                       long    n = 0;
                        int     cmp = c;

                        if (c == '<' || c == '>')
-                           c = getchr();
+                           c = (long)getchr();
                        while (VIM_ISDIGIT(c))
                        {
                            n = n * 10 + (c - '0');
-                           c = getchr();
+                           c = (long)getchr();
                        }
                        if (c == 'l' || c == 'c' || c == 'v')
                        {
@@ -1629,7 +1629,7 @@ nfa_regatom(void)
                                /* \%{n}v  \%{n}<v  \%{n}>v  */
                                EMIT(cmp == '<' ? NFA_VCOL_LT :
                                     cmp == '>' ? NFA_VCOL_GT : NFA_VCOL);
-                           EMIT(n);
+                           EMIT((int)n);
                            break;
                        }
                        else if (c == '\'' && n == 0)
```

**Comment by brammool** [comment]
Can someone confirm this solves the problem?

**Comment by dpelle** [comment]
@brammool  wrote:

> Can someone confirm this solves the problem?

I can reproduce the ubsan error with vim-8.0.1442
and the error no longer happens after applying the
patch from Christian Brabandt.

However, satisfying ubsan is only masking the issue, as a
long value will end up being truncated when casting the
long value into an int valur in: EMIT((int)n);

Maybe we should report an error instead when n is too large?
