### ISSUE TITLE
undefined left shift in readfile()

### ISSUE THREAD

**Issue by geeknik** [vim/vim#2253]
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -c 'call search(getline("."))' -c ':qa!' test000

```
fileio.c:1959:20: runtime error: left shift of 156 by 24 places cannot be represented in type 'int'
    #0 0x8e04f2 in readfile /root/vim/src/fileio.c:1959:20
    #1 0x4eec0e in open_buffer /root/vim/src/buffer.c:236:11
    #2 0x13ee8c7 in create_windows /root/vim/src/main.c:2732:9
    #3 0x13ee8c7 in vim_main2 /root/vim/src/main.c:724
    #4 0x13e5d3d in main /root/vim/src/main.c:415:12
    #5 0x7ffa1a2de3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #6 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior fileio.c:1959:20 
```
[test000.gz](https://github.com/vim/vim/files/1418784/test000.gz)

**Comment by dpelle** [comment]
This patch fixes the undefined behavior:

```
diff --git a/src/fileio.c b/src/fileio.c
index 5755156..d8f11d7 100644
--- a/src/fileio.c
+++ b/src/fileio.c
@@ -1956,17 +1956,17 @@ retry:
                    {
                        if (fio_flags & FIO_ENDIAN_L)
                        {
-                           u8c = (*--p << 24);
-                           u8c += (*--p << 16);
-                           u8c += (*--p << 8);
+                           u8c = (unsigned)*--p << 24u;
+                           u8c += (unsigned)*--p << 16u;
+                           u8c += (unsigned)*--p << 8u;
                            u8c += *--p;
                        }
                        else    /* big endian */
                        {
                            u8c = *--p;
-                           u8c += (*--p << 8);
-                           u8c += (*--p << 16);
-                           u8c += (*--p << 24);
+                           u8c += (unsigned)*--p << 8;
+                           u8c += (unsigned)*--p << 16;
+                           u8c += (unsigned)*--p << 24;
                        }
                    }
                    else    /* UTF-8 */
```
