### ISSUE TITLE
signed integer overflow in getdecchrs()

### ISSUE THREAD

**Issue by geeknik** [vim/vim#2254]
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -c 'call search(getline("."))' -c ':qa!' test013

```
regexp.c:3315:5: runtime error: signed integer overflow: 500000000 * 10 cannot be represented in type 'int'
    #0 0xde2b44 in getdecchrs /root/vim/src/regexp.c:3315:5
    #1 0xe3b8b1 in nfa_regpiece /root/vim/src/./regexp_nfa.c:2092:11
    #2 0xe3b8b1 in nfa_regconcat /root/vim/src/./regexp_nfa.c:2296
    #3 0xe3ac67 in nfa_regbranch /root/vim/src/./regexp_nfa.c:2330:9
    #4 0xe3a114 in nfa_reg /root/vim/src/./regexp_nfa.c:2390:9
    #5 0xe2ff45 in re2post /root/vim/src/./regexp_nfa.c:2805:9
    #6 0xe2ff45 in nfa_regcomp /root/vim/src/./regexp_nfa.c:7257
    #7 0xdcc271 in vim_regcomp /root/vim/src/regexp.c:8153:16
    #8 0xf66486 in search_regcomp /root/vim/src/search.c:223:25
    #9 0xf69de2 in searchit /root/vim/src/search.c:621:9
    #10 0x70aec6 in search_cmn /root/vim/src/evalfunc.c:9363:17
    #11 0x6d83e1 in f_search /root/vim/src/evalfunc.c:9500:28
    #12 0x68b15b in call_internal_func /root/vim/src/evalfunc.c:1012:5
    #13 0x12341e6 in call_func /root/vim/src/userfunc.c:1446:14
    #14 0x1232b95 in get_func_tv /root/vim/src/userfunc.c:455:8
    #15 0x12575b6 in ex_call /root/vim/src/userfunc.c:3082:6
    #16 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #17 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #18 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
    #19 0x13f138f in vim_main2 /root/vim/src/main.c:799
    #20 0x13e5d3d in main /root/vim/src/main.c:415:12
    #21 0x7f006d6a93f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #22 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior regexp.c:3315:5
```
[test013.gz](https://github.com/vim/vim/files/1418805/test013.gz)

**Comment by chrisbra** [comment]
I think patch https://github.com/vim/vim/releases/tag/v8.0.1254 fixes it.
