### ISSUE TITLE
vim crashes when executing 'cat /dev/urandom' in terminal

### ISSUE THREAD

**Issue by zhykzhykzhyk** [vim/vim#2613]
OS: Ubuntu 16.04.3 LTS
vim version: 8.0.1451

step to reproduce:
```
vim -u NORC "+term cat /dev/urandom"
```

backtrace from core dump
```
#0  0x00007f1bdd4af767 in kill () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000050bca3 in may_core_dump () at os_unix.c:3383
#2  0x000000000050dd30 in may_core_dump () at os_unix.c:3352
#3  mch_exit (r=r@entry=1) at os_unix.c:3349
#4  0x00000000005e01a6 in getout (exitval=1) at main.c:1542
#5  <signal handler called>
#6  0x00007f1bdd4af428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#7  0x00007f1bdd4b102a in __GI_abort () at abort.c:89
#8  0x00007f1bdd4f17ea in __libc_message (do_abort=2, fmt=fmt@entry=0x7f1bdd60aed8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#9  0x00007f1bdd4f89dc in malloc_printerr (ar_ptr=0x7f1bdd83eb20 <main_arena>, ptr=0x143bd80, str=0x7f1bdd607c75 "corrupted size vs. prev_size", action=<optimized out>)
    at malloc.c:5006
#10 malloc_consolidate (av=av@entry=0x7f1bdd83eb20 <main_arena>) at malloc.c:4183
#11 0x00007f1bdd4fbcde in _int_malloc (av=av@entry=0x7f1bdd83eb20 <main_arena>, bytes=bytes@entry=4096) at malloc.c:3450
#12 0x00007f1bdd4fe184 in __GI___libc_malloc (bytes=bytes@entry=4096) at malloc.c:2913
#13 0x00000000004d11a1 in lalloc (size=4096, message=1) at misc2.c:976
#14 0x00000000005d2494 in channel_save (channel=channel@entry=0x12ed770, part=part@entry=PART_OUT, 
    buf=0x12ee2e0 "*S(\360\064䑴;\026\277S\022!\215-\005'h+Z\207@.u0H\034\374:\242_\321\330\367^\350\026\254[A*\021rv\310\323+)\223\200\213\253Zk\262\347\373$\bJ\360\026\331\373HԮG=\021\342?ѝ<\324P(\223\365\235\262W\373B\362\002\254:\213\276\224m\371cS\017\306,w\231\356\rQ\360\322C\371d\241\262V\377\212EF\361\023\311E\002Pa\034\067*Lѹ\221\334Kɿ\235\301|\afb\253l\004\304\066s\237\265\027P\353\253j\244\025q\271\r\nк\230r\355\033\262\316\370U\313\177)\366\235\351.b\002\320\\}\342x\203\\1T\216\201\060\261\253\066{\236DaJ\030"..., len=len@entry=4095, prepend=prepend@entry=0, lead=lead@entry=0x6250b4 "RECV ") at channel.c:1769
#15 0x00000000005d5832 in channel_read (channel=0x12ed770, part=PART_OUT, func=0x6252e6 "channel_select_check") at channel.c:3294
#16 0x00000000005d7a90 in channel_select_check (ret_in=<optimized out>, rfds_in=rfds_in@entry=0x7fff9b7ae5a0, wfds_in=wfds_in@entry=0x7fff9b7ae620) at channel.c:4146
#17 0x0000000000511016 in RealWaitForChar (fd=0, msec=msec@entry=3890, interrupted=interrupted@entry=0x7fff9b7ae82c, check_for_gpm=0x0) at os_unix.c:6212
#18 0x00000000005112a1 in WaitForCharOrMouse (msec=3890, interrupted=0x7fff9b7ae82c, ignore_input=0) at os_unix.c:5859
#19 0x00000000005972df in ui_wait_for_chars_or_timer (wtime=3890, wait_func=0x511240 <WaitForCharOrMouse>, interrupted=0x7fff9b7ae82c, ignore_input=0) at ui.c:243
#20 0x000000000050c244 in WaitForChar (ignore_input=0, interrupted=0x7fff9b7ae82c, msec=3890) at os_unix.c:5793
#21 mch_inchar (buf=0x88c76e <typebuf_init+110> "", maxlen=51, wtime=-1, tb_change_cnt=91) at os_unix.c:489
#22 0x0000000000598fb5 in ui_inchar (buf=buf@entry=0x88c76e <typebuf_init+110> "", maxlen=maxlen@entry=51, wtime=wtime@entry=-1, tb_change_cnt=tb_change_cnt@entry=91)
    at ui.c:191
#23 0x00000000004a1f4f in inchar (buf=0x88c76e <typebuf_init+110> "", maxlen=154, wait_time=-1) at getchar.c:3073
#24 0x00000000004a3f6c in vgetorpeek (advance=advance@entry=1) at getchar.c:2849
#25 0x00000000004a48be in vgetc () at getchar.c:1612
#26 0x0000000000594712 in term_vgetc () at terminal.c:1234
#27 terminal_loop (blocking=blocking@entry=1) at terminal.c:1555
#28 0x00000000005e1142 in main_loop (cmdwin=cmdwin@entry=0, noexmode=noexmode@entry=0) at main.c:1352
#29 0x00000000005e217d in vim_main2 () at main.c:905
#30 0x0000000000410742 in main (argc=<optimized out>, argv=<optimized out>) at main.c:429
```

**Comment by zhykzhykzhyk** [comment]
Output from address sanitizer:
```
Vim: Warning: Output is not to a terminal
=================================================================
==17729==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000355f4 at pc 0x820878 bp 0x7ffe6199a280 sp 0x7ffe6199a270
WRITE of size 4 at 0x6020000355f4 thread T0
    #0 0x820877 in decode_utf8 libvterm/src/encoding.c:52
    #1 0x82eab7 in on_text libvterm/src/state.c:260
    #2 0x82291d in do_string libvterm/src/parser.c:140
    #3 0x82382e in vterm_input_write libvterm/src/parser.c:326
    #4 0x7aa1cc in term_write_job_output terminal.c:659
    #5 0x7aa1cc in write_to_term terminal.c:702
    #6 0x84eb65 in may_invoke_callback channel.c:2649
    #7 0x851c17 in channel_parse_messages channel.c:4229
    #8 0x5e850d in parse_queued_messages misc2.c:6354
    #9 0x675cd1 in mch_inchar os_unix.c:419
    #10 0x7b6811 in ui_inchar ui.c:191
    #11 0x566f27 in inchar getchar.c:3073
    #12 0x56c97b in vgetorpeek getchar.c:2849
    #13 0x56dd0a in vgetc getchar.c:1612
    #14 0x7a571f in term_vgetc terminal.c:1234
    #15 0x7abe8d in terminal_loop terminal.c:1555
    #16 0x8663d2 in main_loop main.c:1352
    #17 0x868116 in vim_main2 main.c:905
    #18 0x86b512 in main main.c:429
    #19 0x7ff98e34682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #20 0x40ece8 in _start (vim+0x40ece8)

0x6020000355f4 is located 0 bytes to the right of 4-byte region [0x6020000355f0,0x6020000355f4)
allocated by thread T0 here:
    #0 0x7ff9910be527 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x57527)
    #1 0x836c78 in default_malloc libvterm/src/vterm.c:18
    #2 0x8372b9 in vterm_allocator_malloc libvterm/src/vterm.c:82
    #3 0x82e90e in on_text libvterm/src/state.c:252
    #4 0x82291d in do_string libvterm/src/parser.c:140
    #5 0x82382e in vterm_input_write libvterm/src/parser.c:326
    #6 0x7aa1cc in term_write_job_output terminal.c:659
    #7 0x7aa1cc in write_to_term terminal.c:702
    #8 0x84eb65 in may_invoke_callback channel.c:2649
    #9 0x851c17 in channel_parse_messages channel.c:4229
    #10 0x5e850d in parse_queued_messages misc2.c:6354
    #11 0x675cd1 in mch_inchar os_unix.c:419
    #12 0x7b6811 in ui_inchar ui.c:191
    #13 0x566f27 in inchar getchar.c:3073
    #14 0x56c97b in vgetorpeek getchar.c:2849
    #15 0x56dd0a in vgetc getchar.c:1612
    #16 0x7a571f in term_vgetc terminal.c:1234
    #17 0x7abe8d in terminal_loop terminal.c:1555
    #18 0x8663d2 in main_loop main.c:1352
    #19 0x868116 in vim_main2 main.c:905
    #20 0x86b512 in main main.c:429
    #21 0x7ff98e34682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow libvterm/src/encoding.c:52 decode_utf8
Shadow bytes around the buggy address:
  0x0c047fffea60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffea70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffea80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffea90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffeaa0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fffeab0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa[04]fa
  0x0c047fffeac0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fffead0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fffeae0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fffeaf0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fffeb00: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==17729==ABORTING
```
