### ISSUE TITLE
undefined symbol: PyUnicode_FromFormat

### ISSUE THREAD

**Issue by PWZER** [vim/vim#2840]
I encountered one such error, but run `python -c 'import socket'` at command-line is ok.
```bash
$ vim --cmd 'py3 import socket'   
# output                                                                                                                                                     
Error detected while processing pre-vimrc command line:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/miniconda/lib/python3.6/socket.py", line 49, in <module>
    import _socket
ImportError: /usr/local/miniconda/lib/python3.6/lib-dynload/_socket.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyUnicode_FromFormat
Press ENTER or type command to continue
```

- VIM version is 8.0.1750.

```bash
$ vim --version

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 24 2018 21:33:38)
Included patches: 1-1750
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       -terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/vim-release/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -ldl     -L/usr/local/miniconda/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lrt -lm
```
- Configure Command

```bash
$ ./configure --with-features=hugeb --enable-cscope --enable-multibyte --enable-python3interp --with-python3-config-dir=/usr/local/miniconda/lib/python3.6/config-3.6m-x86_64-linux-gnu --enable-pythoninterp=OFF --prefix=/usr/local/vim-release --disable-gui
```
- Python version is 3.6.5.

- System Info

```bash
$ uname -a
Linux 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by chrisbra** [comment]
Have you tried using the standard python distribution instead of miniconda?

**Comment by PWZER** [comment]
@chrisbra Yes, I tried it. But the result is the same.

**Comment by shsymoen** [comment]
Any news on this issue?

**Comment by JanSurft** [comment]
I'm encountering the same issue but just within my anaconda environment:

```
$ source activate myenv
(myenv) $ python --version
# output
Python 3.6.5 :: Anaconda custom (64-bit)
(myenv) $ vim --cmd 'py3 import socket'
# output
Error detected while processing pre-vimrc command line:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/.../anaconda3/envs/myenv/lib/python3.6/socket.py", line 49, in <module>
    import _socket
ImportError: /home/.../anaconda3/envs/myenv/lib/python3.6/lib-dynload/_socket.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyUnicode_FromFormat
(myenv) $ python
# python interpreter
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) \n[GCC 7.2.0]'
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
>>> exit()
(myenv) $ source deactivate
```

Now the same commands outside of the environment on my system:

```
# Now outside of the environment
$ python --version
# out
Python 3.6.5
$ vim --cmd 'py3 import socket'
# working fine
$ python
Python 3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.6.5 (default, May 11 2018, 04:00:52) \n[GCC 8.1.0]'
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
>>> exit()
```

So the only difference as I just realized is that its anaconda and a different gcc version.

```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:50:25)
Included patches: 1-22
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl/dyn
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua/dyn           +ruby/dyn          +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       -xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static
```

**Comment by JanSurft** [comment]
On another system where I'm using Python 3.6.4 within the anaconda environment there is no error at all. Running `vim 8.0 (2016 Sep 12)`

**Comment by JanSurft** [comment]
@PWZER Please show the output of `ldd -r /path/to/your/_socket.cpython-36m-x86_64-linux-gnu.so`

**Comment by Page-David** [comment]
I come across the same issue today, and I tried to copy and paste files under `/usr/lib/python3.6/lib-dynload` which the anaconda version goes wrong. It works, but so far I do not know if there is any side effects so remeber to backup these files in  anconda.

**Comment by sajaysurya** [comment]
I came across the same issue today, but only within miniconda environment. The issue happens while using python 3 inside the conda environment, with python 2 there is no problem.
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 15 2018 20:50:07)
Included patches: 1-527
Compiled by Arch Linux
```

**Comment by sajaysurya** [comment]
I did a couple of tests. If the system python and conda python are both 3.7.1 i get this problem. :py3 print(sys.path) has the libraries associated with conda environment. however, if conda python has a different (lower) version, the right libraries are loaded and the issue no longer exists..

is there a way to always have system python libraries in sys.path instead of conda libraries?

**Comment by chrisbra** [comment]
have you tried the python3dll or pythondll option?

**Comment by indexofire** [comment]
conda python 3.7.2 had the same error.

**Comment by baoyuxu** [comment]
Any progress?

**Comment by chrisbra** [comment]
you might configure vim to use a different python dll, I already mentioned this in https://github.com/vim/vim/issues/2840#issuecomment-439835165. Also you could run a self compiled vim that links against the system libraries using the ./conrfigure options.

**Comment by sajaysurya** [comment]
Hi,
I added set pythonthreedll=/usr/lib/libpython3.7m.so.1.0 to .vimrc
However, vim is still using packages from conda..

This could probably be a problem with conda
https://www.reddit.com/r/learnpython/comments/bb7hha/conda_environments_dynamic_linking_vim/

**Comment by piyueh** [comment]
I got a similar issue and solve it based on the suggestion in [#2840 (comment)](https://github.com/vim/vim/issues/2840#issuecomment-439835165). My vim build is 8.1.1186-1 from Arch Linux official repository. When using the system python 3 (v3.7.3, also from Arch Linux official repo), everything works fine. But when using Anaconda environments, no matter it's python 3.6 or python 3.7, I always got the `PyUnicode_FromFormat` error.

Forcing `pythonthreehome` and `pythonthreedll` to be empty solves my problem. For example, I add the following settings to my ***vimrc***:
```
set pythonthreehome=
set pythonthreedll=
```

I tried setting `pythonthreehome` and `pythonthreedll` to the system python, but it didn't work. Vim crashed immediately. Only setting them to empty solves my problem.

**Comment by sajaysurya** [comment]
I'm on arch too using vim 8.1.1186-1; but, setting pythonthreehome as empty didn't work for me.
Instead I did
```
set pythonthreehome=/usr
```
and I didn't touch pythonthreedll. Everything seems to work fine this way.

**Comment by darshkpatel** [comment]
@piyueh Solution of using the following in vimrc
> set pythonthreehome=
> set pythonthreedll=

works for me , i'm using arch , andconda3

**Comment by KeAWang** [comment]
The following worked for me. I'm on arch with miniconda3 and python 3.7.3.
```
set pythonthreehome=/usr
let g:ycm_python_binary_path = 'python'
```
I needed the last line to autocomplete packages installed into my conda environment.

**Comment by chrisbra** [comment]
closing then.

**Comment by xiaoyaoliu** [comment]
I solve the problem by this solution:

`$ export LDFLAGS="-rdynamic"`

before your compile the vim, hopefully this can help others who meet the same issue:-)
