### ISSUE TITLE
Vim cannot import subprocess Python3

### ISSUE THREAD

**Issue by mattrbrousseau** [vim/vim#3008]
Hi there,

I've been trying to use jedi-vim on Arch and ran into this issue while trying to set it up. Whenever I tried to run it, I would run into an error that said 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ImportError: /usr/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise`

I get the same error while trying to import subprocess with python 3 through vim. This does not happen when I run python 3 in any IDE or through the terminal, it seems to only happen in Vim.

If anyone has any suggestions, that would be greatly appreciated

**Comment by xuboying** [comment]
I meet similiar problem recently, if you build your python(static lib mode) by yourself, it might be a linking issue when build vim.

https://github.com/vim/vim/issues/2925#issuecomment-514109918
