### ISSUE TITLE
Error "E315: ml_get" with a statusline and multiple runs of :tabedit

### ISSUE THREAD

**Issue by Raimondi** [vim/vim#3550]
I ran into this error by mistake but I could reproduce it, so here it is.

Save the following lines in testfile:
```vim
" a statusline is needed
set laststatus=2
" two or more lines in the buffer are also needed
put _
" use :call with a range to call a function that executes :tabedit
%call execute('tabedit')
```
Run the following:

    vim -u testfile

Get the following errors:
```
Error detected while processing /.../testfile:
line    3:
E315: ml_get: invalid lnum: 2
E315: ml_get: invalid lnum: 2
E315: ml_get: invalid lnum: 2
E315: ml_get: invalid lnum: 2
E315: ml_get: invalid lnum: 2
Press ENTER or type command to continue
```
vim :version output
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 18 2018 00:21:34)
macOS version
Included patches: 1-483
Compiled by me@my.machine
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               -perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         -python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
-cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               -ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking:
gcc    -o vim        -lm -lncurses  -liconv -framework AppKit
```

**Comment by dpelle** [comment]
I confirm. Building with -DABORT_ON_INTERNAL_ERROR, 
vim aborts at this stack trace:
```
$ gdb --args ./vim --clean -c 'set laststatus=2' -c 'put _' -c '%call execute(":tabedit")'
...
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
...
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff625e801 in __GI_abort () at abort.c:79
#2  0x000055555575faae in iemsgn (s=<optimized out>, n=n@entry=2) at message.c:802
#3  0x00005555556336a8 in ml_get_buf (buf=<optimized out>, lnum=lnum@entry=2, will_change=will_change@entry=0) at memline.c:2500
#4  0x000055555563c722 in plines_win_nofold (wp=wp@entry=0x555555c3d800, lnum=lnum@entry=2) at misc1.c:2174
#5  0x000055555563c802 in plines_win_nofill (wp=0x555555c3d800, lnum=2, winheight=1) at misc1.c:2157
#6  0x000055555563c83f in plines_win (wp=wp@entry=0x555555c3d800, lnum=2, winheight=winheight@entry=1) at misc1.c:2126
#7  0x0000555555652c06 in curs_rows (wp=0x555555c3d800) at move.c:775
#8  curs_columns (may_scroll=1) at move.c:967
#9  0x000055555572a715 in win_new_height (wp=wp@entry=0x555555c3d800, height=65) at window.c:5747
#10 0x000055555572b2b4 in last_status_rec (fr=<optimized out>, statusline=1) at window.c:6055
#11 0x000055555572dcf7 in win_new_tabpage (after=0) at window.c:3684
#12 0x00005555555edbd3 in ex_splitview (eap=0x7fffffffc240) at ex_docmd.c:8400
#13 0x00005555555e9c0f in do_one_cmd (cmdlinep=cmdlinep@entry=0x7fffffffc4f0, sourcing=sourcing@entry=1, cstack=cstack@entry=0x7fffffffc580, fgetline=fgetline@entry=0x0, 
    cookie=cookie@entry=0x0) at ex_docmd.c:2525
#14 0x00005555555eba8d in do_cmdline (cmdline=cmdline@entry=0x555555c34350 ":tabedit", fgetline=fgetline@entry=0x0, cookie=cookie@entry=0x0, flags=flags@entry=11)
    at ex_docmd.c:1036
#15 0x00005555555ed18e in do_cmdline_cmd (cmd=cmd@entry=0x555555c34350 ":tabedit") at ex_docmd.c:637
#16 0x00005555555bd755 in f_execute (argvars=<optimized out>, rettv=0x7fffffffd350) at evalfunc.c:3252
#17 0x00005555555c6029 in call_internal_func (name=name@entry=0x555555c34370 "execute", argcount=argcount@entry=1, argvars=argvars@entry=0x7fffffffd140, 
    rettv=rettv@entry=0x7fffffffd350) at evalfunc.c:1082
#18 0x0000555555722772 in call_func (funcname=funcname@entry=0x555555a089a0 "execute", len=len@entry=7, rettv=rettv@entry=0x7fffffffd350, argcount_in=argcount_in@entry=1, 
    argvars_in=argvars_in@entry=0x7fffffffd140, argv_func=argv_func@entry=0x0, firstline=1, lastline=2, doesrange=0x7fffffffd33c, evaluate=<optimized out>, partial=0x0, 
    selfdict_in=0x0) at userfunc.c:1507
#19 0x000055555572382c in get_func_tv (name=name@entry=0x555555a089a0 "execute", len=7, rettv=rettv@entry=0x7fffffffd350, arg=arg@entry=0x7fffffffd340, 
    firstline=firstline@entry=1, lastline=lastline@entry=2, doesrange=0x7fffffffd33c, evaluate=1, partial=0x0, selfdict=0x0) at userfunc.c:455
#20 0x0000555555726421 in ex_call (eap=0x7fffffffd460) at userfunc.c:3157
#21 0x00005555555e9c0f in do_one_cmd (cmdlinep=cmdlinep@entry=0x7fffffffd710, sourcing=sourcing@entry=1, cstack=cstack@entry=0x7fffffffd7a0, fgetline=fgetline@entry=0x0, 
    cookie=cookie@entry=0x0) at ex_docmd.c:2525
#22 0x00005555555eba8d in do_cmdline (cmdline=<optimized out>, fgetline=0x0, cookie=0x0, flags=11) at ex_docmd.c:1036
#23 0x0000555555756275 in exe_commands (parmp=0x5555559f38c0 <params>) at main.c:2959
#24 vim_main2 () at main.c:814
#25 0x000055555557e82d in main (argc=<optimized out>, argv=<optimized out>) at main.c:441
```

**Comment by chrisbra** [comment]
Fixed by https://github.com/vim/vim/releases/tag/v8.1.0511
