### ISSUE TITLE
reStructuredText: Odd Behaviour of CTRL-A/X on a digit following dot `.`

### ISSUE THREAD

**Issue by e-kwsm** [vim/vim#3599]
* `vim --version`: 8.1.513
* OS: Debian 9.5

# How to Reproduce
1. `vim -u NONE -c'filetype plugin on|setf rst'`
2. input `1.2`
3. `CTRL-A` on `2` gives `13.`, `14.`, ...
  the digit is incremented but swapped with `.`

This doesn't happen when multiple digits follow `.`.

![peek 2018-11-06 19-03](https://user-images.githubusercontent.com/11627708/48057254-e7164180-e1f6-11e8-9b60-f3103a9d4ad2.gif)

The problem disappears if the following line is commented out:
https://github.com/vim/vim/blob/d0721058f494143186f66a60151c9634031a8c96/runtime/autoload/RstFold.vim#L24

**Comment by k-takata** [comment]
Could you contact the plugin maintainer?

**Comment by chrisbra** [comment]
I think this is actually a Vim bug.

When the Vim function `RstFold#GetRstFold` is actually run, the Vim buffer looks like this:

`1.` 
e.g. the 2 has already been removed by the `op_addsub()` function, but the new (incremented) digit has not been entered yet. gdb backtrace at the time the `s:CacheRstFold()` function is run looks like this:

```(gdb) bt
#0  0x00007ffff4c23167 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x00005555556e6421 in mch_suspend () at os_unix.c:1352
#2  0x0000555555796460 in ui_suspend () at ui.c:309
#3  0x000055555562df7f in ex_stop (eap=0x7fffffffbb70) at ex_docmd.c:7833
#4  0x0000555555624056 in do_one_cmd (cmdlinep=0x7fffffffc208, sourcing=1, cstack=0x7fffffffbd60, fgetline=0x55555563e8aa <getexline>, cookie=0x0) at ex_docmd.c:2525
#5  0x0000555555621659 in do_cmdline (cmdline=0x555555d5f240 "stop", fgetline=0x55555563e8aa <getexline>, cookie=0x0, flags=17) at ex_docmd.c:1036
#6  0x0000555555617bd1 in do_debug (cmd=0x555555db60b2 "if !has_key(b:, 'RstFoldCache')") at ex_cmds2.c:328
#7  0x0000555555618022 in dbg_check_breakpoint (eap=0x7fffffffc520) at ex_cmds2.c:495
#8  0x0000555555622cd1 in do_one_cmd (cmdlinep=0x7fffffffcbb8, sourcing=1, cstack=0x7fffffffc710, fgetline=0x5555557a8567 <get_func_line>, cookie=0x55555592f370) at ex_docmd.c:1809
#9  0x0000555555621659 in do_cmdline (cmdline=0x0, fgetline=0x5555557a8567 <get_func_line>, cookie=0x55555592f370, flags=7) at ex_docmd.c:1036
#10 0x00005555557a360c in call_user_func (fp=0x555555af3a50, argcount=0, argvars=0x7fffffffd2c0, rettv=0x7fffffffd890, firstline=1, lastline=1, selfdict=0x0) at userfunc.c:954
#11 0x00005555557a4441 in call_func (funcname=0x555555da2750 "RstFold#GetRstFold()", len=18, rettv=0x7fffffffd890, argcount_in=0, argvars_in=0x7fffffffd2c0, argv_func=0x0, firstline=1, lastline=1, doesrange=0x7fffffffd4a4, evaluate=1, partial=0x0, selfdict_in=0x0)
    at userfunc.c:1488
#12 0x00005555557a2503 in get_func_tv (name=0x555555da2750 "RstFold#GetRstFold()", len=18, rettv=0x7fffffffd890, arg=0x7fffffffd860, firstline=1, lastline=1, doesrange=0x7fffffffd4a4, evaluate=1, partial=0x0, selfdict=0x0) at userfunc.c:455
#13 0x00005555555e6121 in eval7 (arg=0x7fffffffd860, rettv=0x7fffffffd890, evaluate=1, want_string=0) at eval.c:4147
#14 0x00005555555e58ee in eval6 (arg=0x7fffffffd860, rettv=0x7fffffffd890, evaluate=1, want_string=0) at eval.c:3784
#15 0x00005555555e54a5 in eval5 (arg=0x7fffffffd860, rettv=0x7fffffffd890, evaluate=1) at eval.c:3600
#16 0x00005555555e51a5 in eval4 (arg=0x7fffffffd860, rettv=0x7fffffffd890, evaluate=1) at eval.c:3484
#17 0x00005555555e5010 in eval3 (arg=0x7fffffffd860, rettv=0x7fffffffd890, evaluate=1) at eval.c:3404
#18 0x00005555555e4e89 in eval2 (arg=0x7fffffffd860, rettv=0x7fffffffd890, evaluate=1) at eval.c:3336
#19 0x00005555555e4cbe in eval1 (arg=0x7fffffffd860, rettv=0x7fffffffd890, evaluate=1) at eval.c:3264
#20 0x00005555555e4c15 in eval0 (arg=0x555555dac4c0 "RstFold#GetRstFold()", rettv=0x7fffffffd890, nextcmd=0x0, evaluate=1) at eval.c:3224
#21 0x00005555555e084d in eval_foldexpr (arg=0x555555dac4c0 "RstFold#GetRstFold()", cp=0x7fffffffd8e4) at eval.c:1136
#22 0x0000555555660c57 in foldlevelExpr (flp=0x7fffffffd940) at fold.c:3280
#23 0x000055555565e8ae in foldUpdateIEMS (wp=0x5555558be1d0, top=1, bot=1) at fold.c:2229
#24 0x000055555565c23b in foldUpdate (wp=0x5555558be1d0, top=1, bot=1) at fold.c:837
#25 0x00005555556914a2 in changed_common (lnum=1, col=2, lnume=2, xtra=0) at misc1.c:3259
#26 0x0000555555690be5 in changed_bytes (lnum=1, col=2) at misc1.c:2975
#27 0x0000555555690754 in del_bytes (count=1, fixpos_arg=0, use_delcombine=1) at misc1.c:2730
#28 0x000055555569044d in del_chars (count=1, fixpos=0) at misc1.c:2604
#29 0x00005555556903b6 in del_char (fixpos=0) at misc1.c:2579
#30 0x00005555556cea73 in do_addsub (op_type=28, pos=0x7fffffffdd10, length=1, Prenum1=1) at ops.c:6000
#31 0x00005555556cdab9 in op_addsub (oap=0x7fffffffdea0, Prenum1=1, g_cmd=0) at ops.c:5576
#32 0x00005555556b8c43 in nv_addsub (cap=0x7fffffffddb0) at normal.c:4197
#33 0x00005555556b3614 in normal_cmd (oap=0x7fffffffdea0, toplevel=1) at normal.c:1134
#34 0x00005555557faa58 in main_loop (cmdwin=0, noexmode=0) at main.c:1371
#35 0x00005555557fa109 in vim_main2 () at main.c:917
#36 0x00005555557f97d0 in main (argc=2, argv=0x7fffffffe098) at main.c:441
```

So I think in the `op_addsub()` function we should disable foldupdates, (because the text will be changed anyhow and we need another foldupate afterwards):

```patch
diff --git a/src/ops.c b/src/ops.c
index d412d8a99..e609a8ee9 100644
--- a/src/ops.c
+++ b/src/ops.c
@@ -5567,6 +5567,12 @@ op_addsub(
     struct block_def   bd;
     int                        change_cnt = 0;
     linenr_T           amount = Prenum1;
+    // do_addsub might trigger re-evaluation of vim script foldexpression,
+    // while the buffer is not completly updated yet. Skip it and enable it
+    // later before the call to changed_lines()
+ #ifdef FEAT_FOLDING
+    disable_fold_update++;
+ #endif

     if (!VIsual_active)
     {
@@ -5574,6 +5580,9 @@ op_addsub(
        if (u_save_cursor() == FAIL)
            return;
        change_cnt = do_addsub(oap->op_type, &pos, 0, amount);
+ #ifdef FEAT_FOLDING
+       disable_fold_update--;
+ #endif
        if (change_cnt)
            changed_lines(pos.lnum, 0, pos.lnum + 1, 0L);
     }
@@ -5643,6 +5652,9 @@ op_addsub(
            if (g_cmd && one_change)
                amount += Prenum1;
        }
+ #ifdef FEAT_FOLDING
+       disable_fold_update--;
+ #endif
        if (change_cnt)
            changed_lines(oap->start.lnum, 0, oap->end.lnum + 1, 0L);

```

**Comment by e-kwsm** [comment]
Thank you, the patch fixes the behaviour.
