### ISSUE TITLE
heap-buffer-overflow in get_equi_class

### ISSUE THREAD

**Issue by kcwu** [vim/vim#3970]
with vim 9b5c1fcdeae75f82a2083fafbbf75ab220f6ac1e
```
$ LANG=C ./vim.asan -u NONE -i NONE -Z -e -s  -c 's/^/[[=' -c 'echo search(getline(1))' -c 'qa!'
```

```
==22760==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000020354 at pc 0x000000999af1 bp 0x7fffdc2bcec0 sp 0x7fffdc2bceb8
READ of size 1 at 0x602000020354 thread T0
    #0 0x999af0 in get_equi_class /home/kcwu/src/vim/src/regexp.c:737:6
    #1 0x999af0 in skip_anyof /home/kcwu/src/vim/src/regexp.c:1174
    #2 0x9ab73a in nfa_regatom /home/kcwu/src/vim/src/./regexp_nfa.c:1610:13
    #3 0x9a805c in nfa_regpiece /home/kcwu/src/vim/src/./regexp_nfa.c:2007:11
    #4 0x9a805c in nfa_regconcat /home/kcwu/src/vim/src/./regexp_nfa.c:2246
    #5 0x9a627b in nfa_regbranch /home/kcwu/src/vim/src/./regexp_nfa.c:2279:9
    #6 0x9a594d in nfa_reg /home/kcwu/src/vim/src/./regexp_nfa.c:2340:9
    #7 0x99f9eb in re2post /home/kcwu/src/vim/src/./regexp_nfa.c:2759:9
    #8 0x99f9eb in nfa_regcomp /home/kcwu/src/vim/src/./regexp_nfa.c:7249
    #9 0x99ddf7 in vim_regcomp /home/kcwu/src/vim/src/regexp.c:8006:9
    #10 0xa7b8c6 in search_regcomp /home/kcwu/src/vim/src/search.c:212:25
    #11 0xa7d5ea in searchit /home/kcwu/src/vim/src/search.c:658:9
    #12 0x657151 in search_cmn /home/kcwu/src/vim/src/evalfunc.c:10280:17
    #13 0x63e19b in f_search /home/kcwu/src/vim/src/evalfunc.c:10415:28
    #14 0x6142da in call_internal_func /home/kcwu/src/vim/src/evalfunc.c:1117:5
    #15 0xbed519 in call_func /home/kcwu/src/vim/src/userfunc.c:1519:14
    #16 0xbec888 in get_func_tv /home/kcwu/src/vim/src/userfunc.c:453:8
    #17 0x612699 in eval7 /home/kcwu/src/vim/src/eval.c:4405:13
    #18 0x60ee38 in eval6 /home/kcwu/src/vim/src/eval.c:4008:9
    #19 0x60e02c in eval5 /home/kcwu/src/vim/src/eval.c:3804:9
    #20 0x60d796 in eval4 /home/kcwu/src/vim/src/eval.c:3688:9
    #21 0x60d1e9 in eval3 /home/kcwu/src/vim/src/eval.c:3608:9
    #22 0x5e2e96 in eval2 /home/kcwu/src/vim/src/eval.c:3540:9
    #23 0x5e2e96 in eval1 /home/kcwu/src/vim/src/eval.c:3468
    #24 0x5fc057 in ex_echo /home/kcwu/src/vim/src/eval.c:8424:6
    #25 0x6ac459 in do_one_cmd /home/kcwu/src/vim/src/ex_docmd.c:2525:2
    #26 0x6ac459 in do_cmdline /home/kcwu/src/vim/src/ex_docmd.c:1033
    #27 0xd19db5 in exe_commands /home/kcwu/src/vim/src/main.c:2959:2
    #28 0xd19db5 in vim_main2 /home/kcwu/src/vim/src/main.c:809
    #29 0xd15b41 in main /home/kcwu/src/vim/src/main.c:441:12
    #30 0x7f66ab2612b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #31 0x42bc19 in _start (/home/kcwu/src/vim/src/vim.asan+0x42bc19)

0x602000020354 is located 0 bytes to the right of 4-byte region [0x602000020350,0x602000020354)
allocated by thread T0 here:
    #0 0x4f5f37 in __interceptor_malloc (/home/kcwu/src/vim/src/vim.asan+0x4f5f37)
    #1 0x84bbce in lalloc /home/kcwu/src/vim/src/misc2.c:942:21
    #2 0x84c71f in alloc /home/kcwu/src/vim/src/misc2.c:827:13
    #3 0x84c71f in vim_strsave /home/kcwu/src/vim/src/misc2.c:1284
    #4 0x62a0f8 in get_buffer_lines /home/kcwu/src/vim/src/evalfunc.c:4644:25
    #5 0x62a0f8 in f_getline /home/kcwu/src/vim/src/evalfunc.c:5324
    #6 0x6142da in call_internal_func /home/kcwu/src/vim/src/evalfunc.c:1117:5
    #7 0xbed519 in call_func /home/kcwu/src/vim/src/userfunc.c:1519:14
    #8 0xbec888 in get_func_tv /home/kcwu/src/vim/src/userfunc.c:453:8
    #9 0x612699 in eval7 /home/kcwu/src/vim/src/eval.c:4405:13
    #10 0x60ee38 in eval6 /home/kcwu/src/vim/src/eval.c:4008:9
    #11 0x60e02c in eval5 /home/kcwu/src/vim/src/eval.c:3804:9
    #12 0x60d796 in eval4 /home/kcwu/src/vim/src/eval.c:3688:9
    #13 0x60d1e9 in eval3 /home/kcwu/src/vim/src/eval.c:3608:9
    #14 0x5e2e96 in eval2 /home/kcwu/src/vim/src/eval.c:3540:9
    #15 0x5e2e96 in eval1 /home/kcwu/src/vim/src/eval.c:3468
    #16 0xbec44a in get_func_tv /home/kcwu/src/vim/src/userfunc.c:423:6
    #17 0x612699 in eval7 /home/kcwu/src/vim/src/eval.c:4405:13
    #18 0x60ee38 in eval6 /home/kcwu/src/vim/src/eval.c:4008:9
    #19 0x60e02c in eval5 /home/kcwu/src/vim/src/eval.c:3804:9
    #20 0x60d796 in eval4 /home/kcwu/src/vim/src/eval.c:3688:9
    #21 0x60d1e9 in eval3 /home/kcwu/src/vim/src/eval.c:3608:9
    #22 0x5e2e96 in eval2 /home/kcwu/src/vim/src/eval.c:3540:9
    #23 0x5e2e96 in eval1 /home/kcwu/src/vim/src/eval.c:3468
    #24 0x5fc057 in ex_echo /home/kcwu/src/vim/src/eval.c:8424:6
    #25 0x6ac459 in do_one_cmd /home/kcwu/src/vim/src/ex_docmd.c:2525:2
    #26 0x6ac459 in do_cmdline /home/kcwu/src/vim/src/ex_docmd.c:1033
    #27 0xd19db5 in exe_commands /home/kcwu/src/vim/src/main.c:2959:2
    #28 0xd19db5 in vim_main2 /home/kcwu/src/vim/src/main.c:809
    #29 0xd15b41 in main /home/kcwu/src/vim/src/main.c:441:12
    #30 0x7f66ab2612b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/kcwu/src/vim/src/regexp.c:737:6 in get_equi_class
Shadow bytes around the buggy address:
  0x0c047fffc010: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fffc020: fa fa fd fd fa fa fd fd fa fa fd fd fa fa 00 00
  0x0c047fffc030: fa fa 00 00 fa fa 00 00 fa fa 05 fa fa fa fd fa
  0x0c047fffc040: fa fa 04 fa fa fa 02 fa fa fa fd fa fa fa 04 fa
  0x0c047fffc050: fa fa fd fa fa fa 00 00 fa fa 01 fa fa fa 04 fa
=>0x0c047fffc060: fa fa fd fd fa fa fd fa fa fa[04]fa fa fa 07 fa
  0x0c047fffc070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffc080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffc090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffc0a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffc0b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==22760==ABORTING
     
```

found by libfuzzer

**Comment by dpelle** [comment]
This patch fixes it:
```
diff --git a/src/regexp.c b/src/regexp.c
index 836204895..e37c06507 100644
--- a/src/regexp.c
+++ b/src/regexp.c
@@ -1111,7 +1111,7 @@ get_coll_element(char_u **pp)
     int                l = 1;
     char_u     *p = *pp;
 
-    if (p[0] != NUL && p[1] == '.')
+    if (p[0] != NUL && p[1] == '.' && p[2] != NUL)
     {
        if (has_mbyte)
            l = (*mb_ptr2len)(p + 2);
```
Nice that you find all these bugs with libfuzzer.
