### ISSUE TITLE
heap-buffer-overflow in get_coll_element

### ISSUE THREAD

**Issue by kcwu** [vim/vim#3985]
with vim 55c77cf2ea9c15e1ec75d1faf702ec3c9e325271

similar to https://github.com/vim/vim/issues/3970

```
$ LANG=C ./vim.asan -u NONE -i NONE -Z -e -s  -c 's/^/[[.' -c 'echo search(getline(1))' -c 'qa!'
```

```
==211745==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200001d254 at pc 0x000000990759 bp 0x7ffc77019400 sp 0x7ffc770193f8
READ of size 1 at 0x60200001d254 thread T0
    #0 0x990758 in get_coll_element /home/kcwu/src/vim/src/regexp.c:1118:6
    #1 0x990758 in skip_anyof /home/kcwu/src/vim/src/regexp.c:1175
    #2 0x9a23ea in nfa_regatom /home/kcwu/src/vim/src/./regexp_nfa.c:1610:13
    #3 0x99ed0c in nfa_regpiece /home/kcwu/src/vim/src/./regexp_nfa.c:2007:11
    #4 0x99ed0c in nfa_regconcat /home/kcwu/src/vim/src/./regexp_nfa.c:2246
    #5 0x99cf2b in nfa_regbranch /home/kcwu/src/vim/src/./regexp_nfa.c:2279:9
    #6 0x99c5fd in nfa_reg /home/kcwu/src/vim/src/./regexp_nfa.c:2340:9
    #7 0x99669b in re2post /home/kcwu/src/vim/src/./regexp_nfa.c:2759:9
    #8 0x99669b in nfa_regcomp /home/kcwu/src/vim/src/./regexp_nfa.c:7249
    #9 0x994a98 in vim_regcomp /home/kcwu/src/vim/src/regexp.c:8008:9
    #10 0xa725e6 in search_regcomp /home/kcwu/src/vim/src/search.c:212:25
    #11 0xa7430a in searchit /home/kcwu/src/vim/src/search.c:658:9
    #12 0x656b21 in search_cmn /home/kcwu/src/vim/src/evalfunc.c:10277:17
    #13 0x63db6b in f_search /home/kcwu/src/vim/src/evalfunc.c:10412:28
    #14 0x613caa in call_internal_func /home/kcwu/src/vim/src/evalfunc.c:1117:5
    #15 0xbe4e99 in call_func /home/kcwu/src/vim/src/userfunc.c:1519:14
    #16 0xbe4208 in get_func_tv /home/kcwu/src/vim/src/userfunc.c:453:8
    #17 0x612069 in eval7 /home/kcwu/src/vim/src/eval.c:4405:13
    #18 0x60e808 in eval6 /home/kcwu/src/vim/src/eval.c:4008:9
    #19 0x60d9fc in eval5 /home/kcwu/src/vim/src/eval.c:3804:9
    #20 0x60d166 in eval4 /home/kcwu/src/vim/src/eval.c:3688:9
    #21 0x60cbb9 in eval3 /home/kcwu/src/vim/src/eval.c:3608:9
    #22 0x5e2866 in eval2 /home/kcwu/src/vim/src/eval.c:3540:9
    #23 0x5e2866 in eval1 /home/kcwu/src/vim/src/eval.c:3468
    #24 0x5fba27 in ex_echo /home/kcwu/src/vim/src/eval.c:8424:6
    #25 0x6abbd9 in do_one_cmd /home/kcwu/src/vim/src/ex_docmd.c:2525:2
    #26 0x6abbd9 in do_cmdline /home/kcwu/src/vim/src/ex_docmd.c:1033
    #27 0xd11375 in exe_commands /home/kcwu/src/vim/src/main.c:2943:2
    #28 0xd11375 in vim_main2 /home/kcwu/src/vim/src/main.c:798
    #29 0xd0d201 in main /home/kcwu/src/vim/src/main.c:441:12
    #30 0x7fce7a0482b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #31 0x42bc19 in _start (/home/kcwu/src/vim/src/vim.asan+0x42bc19)

0x60200001d254 is located 0 bytes to the right of 4-byte region [0x60200001d250,0x60200001d254)
allocated by thread T0 here:
    #0 0x4f5f37 in __interceptor_malloc (/home/kcwu/src/vim/src/vim.asan+0x4f5f37)
    #1 0x8429ee in lalloc /home/kcwu/src/vim/src/misc2.c:942:21
    #2 0x84353f in alloc /home/kcwu/src/vim/src/misc2.c:827:13
    #3 0x84353f in vim_strsave /home/kcwu/src/vim/src/misc2.c:1284
    #4 0x629ac8 in get_buffer_lines /home/kcwu/src/vim/src/evalfunc.c:4644:25
    #5 0x629ac8 in f_getline /home/kcwu/src/vim/src/evalfunc.c:5324
    #6 0x613caa in call_internal_func /home/kcwu/src/vim/src/evalfunc.c:1117:5
    #7 0xbe4e99 in call_func /home/kcwu/src/vim/src/userfunc.c:1519:14
    #8 0xbe4208 in get_func_tv /home/kcwu/src/vim/src/userfunc.c:453:8
    #9 0x612069 in eval7 /home/kcwu/src/vim/src/eval.c:4405:13
    #10 0x60e808 in eval6 /home/kcwu/src/vim/src/eval.c:4008:9
    #11 0x60d9fc in eval5 /home/kcwu/src/vim/src/eval.c:3804:9
    #12 0x60d166 in eval4 /home/kcwu/src/vim/src/eval.c:3688:9
    #13 0x60cbb9 in eval3 /home/kcwu/src/vim/src/eval.c:3608:9
    #14 0x5e2866 in eval2 /home/kcwu/src/vim/src/eval.c:3540:9
    #15 0x5e2866 in eval1 /home/kcwu/src/vim/src/eval.c:3468
    #16 0xbe3dca in get_func_tv /home/kcwu/src/vim/src/userfunc.c:423:6
    #17 0x612069 in eval7 /home/kcwu/src/vim/src/eval.c:4405:13
    #18 0x60e808 in eval6 /home/kcwu/src/vim/src/eval.c:4008:9
    #19 0x60d9fc in eval5 /home/kcwu/src/vim/src/eval.c:3804:9
    #20 0x60d166 in eval4 /home/kcwu/src/vim/src/eval.c:3688:9
    #21 0x60cbb9 in eval3 /home/kcwu/src/vim/src/eval.c:3608:9
    #22 0x5e2866 in eval2 /home/kcwu/src/vim/src/eval.c:3540:9
    #23 0x5e2866 in eval1 /home/kcwu/src/vim/src/eval.c:3468
    #24 0x5fba27 in ex_echo /home/kcwu/src/vim/src/eval.c:8424:6
    #25 0x6abbd9 in do_one_cmd /home/kcwu/src/vim/src/ex_docmd.c:2525:2
    #26 0x6abbd9 in do_cmdline /home/kcwu/src/vim/src/ex_docmd.c:1033
    #27 0xd11375 in exe_commands /home/kcwu/src/vim/src/main.c:2943:2
    #28 0xd11375 in vim_main2 /home/kcwu/src/vim/src/main.c:798
    #29 0xd0d201 in main /home/kcwu/src/vim/src/main.c:441:12
    #30 0x7fce7a0482b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/kcwu/src/vim/src/regexp.c:1118:6 in get_coll_element
Shadow bytes around the buggy address:
  0x0c047fffb9f0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fffba00: fa fa 00 fa fa fa fd fa fa fa 01 fa fa fa 00 00
  0x0c047fffba10: fa fa 00 00 fa fa 00 00 fa fa 05 fa fa fa fd fa
  0x0c047fffba20: fa fa 04 fa fa fa 02 fa fa fa fd fa fa fa 04 fa
  0x0c047fffba30: fa fa fd fa fa fa 00 00 fa fa 01 fa fa fa 04 fa
=>0x0c047fffba40: fa fa fd fd fa fa fd fa fa fa[04]fa fa fa 07 fa
  0x0c047fffba50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffba60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffba70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffba80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffba90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==211745==ABORTING
```

found by libfuzzer

**Comment by dpelle** [comment]
This patch fixes it:
```
diff --git a/src/regexp.c b/src/regexp.c
index 836204895..e37c06507 100644
--- a/src/regexp.c
+++ b/src/regexp.c
@@ -1111,7 +1111,7 @@ get_coll_element(char_u **pp)
     int                l = 1;
     char_u     *p = *pp;
 
-    if (p[0] != NUL && p[1] == '.')
+    if (p[0] != NUL && p[1] == '.' && p[2] != NUL)
     {
        if (has_mbyte)
            l = (*mb_ptr2len)(p + 2);
```

Nice that you find all these bugs with libfuzzer.
