### ISSUE TITLE
internal error: E877: (NFA regexp) Invalid character class: -1015

### ISSUE THREAD

**Issue by kcwu** [vim/vim#3989]
build latest vim (21edde87426eeeaf46e118a137a7fa0e86ad167e)
with -DABORT_ON_INTERNAL_ERROR
```
$ vim -u NONE -e -c 'call setline(1, "a")' -c 'echo search("[ -*\\n- ]")' -c 'qa!'
Vim: Caught deadly signal ABRTracter class: 4294966281
```
The error message is `E877: (NFA regexp) Invalid character class: -1015`

```
#0  0x00007ffff4896fcf in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff48983fa in __GI_abort () at abort.c:89
#2  0x00000000009d0e25 in siemsg (s=0xde10f0 <e_ill_char_class> "E877: (NFA regexp) Invalid character class: %ld") at message.c:787
#3  0x00000000007a0adf in check_char_class (class=-1015, c=97) at ./regexp_nfa.c:4924
#4  0x0000000000797da3 in nfa_regmatch (prog=0x16dbf10, start=0x16dc078, submatch=0x7fffffff99c0, m=0x7fffffff97d0) at ./regexp_nfa.c:6281
#5  0x0000000000793ec7 in nfa_regtry (prog=0x16dbf10, col=0, tm=0x7fffffffa6a8, timed_out=0x0) at ./regexp_nfa.c:7019
#6  0x0000000000793435 in nfa_regexec_both (line=0x16d8390 "a", startcol=0, tm=0x7fffffffa6a8, timed_out=0x0) at ./regexp_nfa.c:7213
#7  0x0000000000760c5c in nfa_regexec_multi (rmp=0x7fffffffa3d0, win=0x16b9ab0, buf=0x16bbba0, lnum=1, col=0, tm=0x7fffffffa6a8, timed_out=0x0) at ./regexp_nfa.c:7428
#8  0x000000000075f393 in vim_regexec_multi (rmp=0x7fffffffa3d0, win=0x16b9ab0, buf=0x16bbba0, lnum=1, col=0, tm=0x7fffffffa6a8, timed_out=0x0) at regexp.c:8247
#9  0x00000000007f757d in searchit (win=0x16b9ab0, buf=0x16bbba0, pos=0x7fffffffa6e0, end_pos=0x0, dir=1, pat=0x16d8070 "[ -*\\n- ]", count=1, options=1024, pat_use=0, stop_lnum=0, tm=0x7fffffffa6a8, timed_out=0x0) at search.c:751
#10 0x00000000005102cf in search_cmn (argvars=0x7fffffffad10, match_pos=0x0, flagsp=0x7fffffffa74c) at evalfunc.c:10277
#11 0x00000000004f9860 in f_search (argvars=0x7fffffffad10, rettv=0x7fffffffb8f0) at evalfunc.c:10412
#12 0x00000000004db567 in call_internal_func (name=0x16d8090 "search", argcount=1, argvars=0x7fffffffad10, rettv=0x7fffffffb8f0) at evalfunc.c:1117
#13 0x00000000008f846d in call_func (funcname=0x16c0c10 "search(\"[ -*\\\\n- ]\")", len=6, rettv=0x7fffffffb8f0, argcount_in=1, argvars_in=0x7fffffffad10, argv_func=0x0, firstline=1, lastline=1, doesrange=0x7fffffffb0dc, evaluate=1, partial=0x0, selfdict_in=0x0) at userfunc.c:1519
#14 0x00000000008f74e4 in get_func_tv (name=0x16c0c10 "search(\"[ -*\\\\n- ]\")", len=6, rettv=0x7fffffffb8f0, arg=0x7fffffffb900, firstline=1, lastline=1, doesrange=0x7fffffffb0dc, evaluate=1, partial=0x0, selfdict=0x0) at userfunc.c:453
#15 0x00000000004d8eac in eval7 (arg=0x7fffffffb900, rettv=0x7fffffffb8f0, evaluate=1, want_string=0) at eval.c:4405
#16 0x00000000004d76ac in eval6 (arg=0x7fffffffb900, rettv=0x7fffffffb8f0, evaluate=1, want_string=0) at eval.c:4008
#17 0x00000000004d69fb in eval5 (arg=0x7fffffffb900, rettv=0x7fffffffb8f0, evaluate=1) at eval.c:3804
#18 0x00000000004d6269 in eval4 (arg=0x7fffffffb900, rettv=0x7fffffffb8f0, evaluate=1) at eval.c:3688
#19 0x00000000004d5d5b in eval3 (arg=0x7fffffffb900, rettv=0x7fffffffb8f0, evaluate=1) at eval.c:3608
#20 0x00000000004bc0bb in eval2 (arg=0x7fffffffb900, rettv=0x7fffffffb8f0, evaluate=1) at eval.c:3540
#21 0x00000000004b3414 in eval1 (arg=0x7fffffffb900, rettv=0x7fffffffb8f0, evaluate=1) at eval.c:3468
#22 0x00000000004c7fea in ex_echo (eap=0x7fffffffbfe8) at eval.c:8424
#23 0x0000000000552e07 in do_one_cmd (cmdlinep=0x7fffffffc9d8, sourcing=1, cstack=0x7fffffffc520, fgetline=0x0, cookie=0x0) at ex_docmd.c:2525
#24 0x000000000054bcbb in do_cmdline (cmdline=0x7fffffffd24a "echo search(\"[ -*\\\\n- ]\")", fgetline=0x0, cookie=0x0, flags=11) at ex_docmd.c:1033
#25 0x000000000054da84 in do_cmdline_cmd (cmd=0x7fffffffd24a "echo search(\"[ -*\\\\n- ]\")") at ex_docmd.c:634
#26 0x00000000009c3918 in exe_commands (parmp=0x169f950 <params>) at main.c:2943
#27 0x00000000009c1821 in vim_main2 () at main.c:798
#28 0x00000000009bc45e in main (argc=10, argv=0x7fffffffcd78) at main.c:441
```

found by libfuzzer

**Comment by dpelle** [comment]
@kcwu wrote:
```
The error message is E877: (NFA regexp) Invalid character class: -1015
```
Interestingly, I get this error message:
```
E877: (NFA regexp) Invalid character class: 4294966281
```

The incorrect error message is fixed with this patch:
```
diff --git a/src/regexp_nfa.c b/src/regexp_nfa.c
index b83e309f7..626d31962 100644
--- a/src/regexp_nfa.c
+++ b/src/regexp_nfa.c
@@ -245,7 +245,7 @@ static int nfa_classcodes[] = {
 
 static char_u e_nul_found[] = N_("E865: (NFA) Regexp end encountered prematurely");
 static char_u e_misplaced[] = N_("E866: (NFA regexp) Misplaced %c");
-static char_u e_ill_char_class[] = N_("E877: (NFA regexp) Invalid character class: %ld");
+static char_u e_ill_char_class[] = N_("E877: (NFA regexp) Invalid character class: %d");
 
 // Variables only used in nfa_regcomp() and descendants.
 static int nfa_re_flags; // re_flags passed to nfa_regcomp()
```
However, this does not prevent the internal error E877 from 
occurring. I see that character class -1015 is `NFA_RANGE_MAX` 
which is not handled in the switch in `check_char_class()`.
