### ISSUE TITLE
segfault in nfa_regmatch

### ISSUE THREAD

**Issue by kcwu** [vim/vim#4009]
with vim 21edde87426eeeaf46e118a137a7fa0e86ad167e

```
vim -u NONE -i NONE -e -s -c 'call search("\\%Ufffffc23")' -c 'qa!'
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000007964a0 in nfa_regmatch (prog=0x16d0c30, start=0x16d0ca8, submatch=0x7fffffffa250, m=0x7fffffffa060) at ./regexp_nfa.c:5947
5947                    if (state_in_list(nextlist, t->state->out1->out, &t->subs))
(gdb) p t->state->out1
$1 = (nfa_state_T *) 0x0
(gdb) bt
#0  0x00000000007964a0 in nfa_regmatch (prog=0x16ccd10, start=0x16ccd88, submatch=0x7fffffffa270, m=0x7fffffffa080) at ./regexp_nfa.c:5947
#1  0x0000000000793e87 in nfa_regtry (prog=0x16ccd10, col=0, tm=0x7fffffffaf58, timed_out=0x0) at ./regexp_nfa.c:7019
#2  0x00000000007933f5 in nfa_regexec_both (line=0x16cf7af "", startcol=0, tm=0x7fffffffaf58, timed_out=0x0) at ./regexp_nfa.c:7213
#3  0x0000000000760c1c in nfa_regexec_multi (rmp=0x7fffffffac80, win=0x16b9ab0, buf=0x16bbba0, lnum=1, col=0, tm=0x7fffffffaf58, timed_out=0x0) at ./regexp_nfa.c:7428
#4  0x000000000075f353 in vim_regexec_multi (rmp=0x7fffffffac80, win=0x16b9ab0, buf=0x16bbba0, lnum=1, col=0, tm=0x7fffffffaf58, timed_out=0x0) at regexp.c:8247
#5  0x00000000007f753d in searchit (win=0x16b9ab0, buf=0x16bbba0, pos=0x7fffffffaf90, end_pos=0x0, dir=1, pat=0x16cccd0 "\\%Ufffffc23", count=1, options=1024, pat_use=0, stop_lnum=0, tm=0x7fffffffaf58, timed_out=0x0) at search.c:751
#6  0x00000000005102cf in search_cmn (argvars=0x7fffffffb5c0, match_pos=0x0, flagsp=0x7fffffffaffc) at evalfunc.c:10277
#7  0x00000000004f9860 in f_search (argvars=0x7fffffffb5c0, rettv=0x7fffffffb8c0) at evalfunc.c:10412
#8  0x00000000004db567 in call_internal_func (name=0x16cccf0 "search", argcount=1, argvars=0x7fffffffb5c0, rettv=0x7fffffffb8c0) at evalfunc.c:1117
#9  0x00000000008f842d in call_func (funcname=0x16cccb0 "search", len=6, rettv=0x7fffffffb8c0, argcount_in=1, argvars_in=0x7fffffffb5c0, argv_func=0x0, firstline=1, lastline=1, doesrange=0x7fffffffb8b4, evaluate=1, partial=0x0, selfdict_in=0x0) at userfunc.c:1519
#10 0x00000000008f74a4 in get_func_tv (name=0x16cccb0 "search", len=6, rettv=0x7fffffffb8c0, arg=0x7fffffffb8f0, firstline=1, lastline=1, doesrange=0x7fffffffb8b4, evaluate=1, partial=0x0, selfdict=0x0) at userfunc.c:453
#11 0x00000000009037ee in ex_call (eap=0x7fffffffbfe8) at userfunc.c:3183
#12 0x0000000000552e07 in do_one_cmd (cmdlinep=0x7fffffffc9d8, sourcing=1, cstack=0x7fffffffc520, fgetline=0x0, cookie=0x0) at ex_docmd.c:2525
#13 0x000000000054bcbb in do_cmdline (cmdline=0x7fffffffd247 "call search(\"\\\\%Ufffffc23\")", fgetline=0x0, cookie=0x0, flags=11) at ex_docmd.c:1033
#14 0x000000000054da84 in do_cmdline_cmd (cmd=0x7fffffffd247 "call search(\"\\\\%Ufffffc23\")") at ex_docmd.c:634
#15 0x00000000009c38d8 in exe_commands (parmp=0x169f950 <params>) at main.c:2943
#16 0x00000000009c17e1 in vim_main2 () at main.c:798
#17 0x00000000009bc41e in main (argc=11, argv=0x7fffffffcd78) at main.c:441
```

found by libfuzzer

**Comment by kcwu** [comment]
`\\%Ufffffc` variants (add more characters) may lead to `stack-overflow` and `allocation-size-too-big`.
