### ISSUE TITLE
Vim fails with SIGSEGV on xinput disable

### ISSUE THREAD

**Issue by jiwopene** [vim/vim#4184]
When I disable my mouse using `xinput disable "PS/2 Logitech Wheel Mouse"` from i3 window manager, gvim stops with this error:

```
(gvim:27396): Gdk-CRITICAL **: 21:56:31.806: gdk_device_get_n_axes: assertion 'GDK_IS_DEVICE (device)' failed

(gvim:27396): Gdk-CRITICAL **: 21:56:31.806: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)' failed
Vim: Caught deadly signal SEGV
```

i3-wm config line:
```
bindsym $mod+F2 exec xinput disable "PS/2 Logitech Wheel Mouse"
```

Complete `git --version`:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 20 2019 21:17:42)                                                                                                                         [2/148]
Included patches: 1-1298
Modified by Gentoo-8.0.1298
Compiled by portage@chameleon
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-autoservername  +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    -netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
+clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      +toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
-cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     +xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    +xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/vim/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1
.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include
/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpn
g16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -march=native -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: x86_64-pc-linux-gnu-gcc   -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o gvim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -l
gobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl  -lacl -lattr -ldl
```

**Comment by jiwopene** [comment]
The gvim window has to be focused when I disable the mouse.

**Comment by chrisbra** [comment]
can you post a stacktrace?

**Comment by jiwopene** [comment]
```
Thread 1 "gvim" received signal SIGSEGV, Segmentation fault.
0x00007ffff7249fa8 in ?? () from /usr/lib64/libgdk-3.so.0
(gdb) bt
#0  0x00007ffff7249fa8 in ?? () from /usr/lib64/libgdk-3.so.0
#1  0x00007ffff7253f32 in ?? () from /usr/lib64/libgdk-3.so.0
#2  0x00007ffff725390f in ?? () from /usr/lib64/libgdk-3.so.0
#3  0x00007ffff721e169 in gdk_display_get_event ()
   from /usr/lib64/libgdk-3.so.0
#4  0x00007ffff7253662 in ?? () from /usr/lib64/libgdk-3.so.0
#5  0x00007ffff5f8b0ef in g_main_context_dispatch ()
   from /usr/lib64/libglib-2.0.so.0
#6  0x00007ffff5f8b358 in ?? () from /usr/lib64/libglib-2.0.so.0
#7  0x00007ffff5f8b40d in g_main_context_iteration ()
   from /usr/lib64/libglib-2.0.so.0
#8  0x0000555555743fcc in gui_mch_wait_for_chars ()
#9  0x000055555573330b in gui_wait_for_chars_or_timer ()
#10 0x00005555557352c1 in gui_wait_for_chars ()
#11 0x000055555571a83d in ui_inchar ()
#12 0x000055555561d6aa in inchar ()
#13 0x000055555561f0a8 in vgetorpeek.part ()
#14 0x00005555556204ea in vgetc ()
#15 0x00005555556207fa in safe_vgetc ()
#16 0x0000555555668903 in normal_cmd ()
#17 0x0000555555760824 in main_loop ()
#18 0x00005555557619fc in vim_main2 ()
---Type <return> to continue, or q <return> to quit---
#19 0x000055555558ad98 in main ()
```

**Comment by jiwopene** [comment]
Gentoo USE flags:

```
=================================================================
                        Package Settings
=================================================================

app-editors/gvim-8.0.1298::gentoo was built with the following:
USE="acl debug gtk3 nls (-aqua) -cscope -gnome -gtk -lua -luajit -motif -neXt -netbeans -perl -python -racket -ruby (-selinux) -session -tcl" ABI_X86="(64)" PYTHON_SINGLE_TARGET="python3_6 -python2_7 -python3_5" PYTHON_TARGETS="python2_7 python3_6 -python3_5"
CFLAGS="-march=native -O2 -pipe -DDEBUG"
CXXFLAGS="-march=native -O2 -pipe -DDEBUG"


app-editors/vim-8.0.1298::gentoo was built with the following:
USE="X acl debug gpm nls -cscope -lua -luajit -minimal -perl -python -racket -ruby (-selinux) -tcl -terminal -vim-pager" ABI_X86="(64)" PYTHON_SINGLE_TARGET="python3_6 -python2_7 -python3_5" PYTHON_TARGETS="python2_7 python3_6 -python3_5"
CFLAGS="-march=native -O2 -pipe -DDEBUG"
CXXFLAGS="-march=native -O2 -pipe -DDEBUG"
```

**Comment by chrisbra** [comment]
Unfortunately, the stack trace is not really useful without debugging symbols. Can you get the stacktrace with debugging symbols enabled? However it looks like the segfault happens in the gtk library, so I am not sure we can do anything here.

**Comment by jiwopene** [comment]
```
Starting program: /usr/bin/gvim --nofork
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

** (gvim:3218): WARNING **: 17:22:29.237: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[New Thread 0x7fffeb853700 (LWP 3232)]
[New Thread 0x7fffeb052700 (LWP 3233)]
[New Thread 0x7fffea851700 (LWP 3234)]
[New Thread 0x7fffd7fff700 (LWP 3235)]
[Thread 0x7fffea851700 (LWP 3234) exited]

(gvim:3218): Gdk-CRITICAL **: 17:22:31.784: gdk_device_get_n_axes: assertion 'GDK_IS_DEVICE (device)' failed

(gvim:3218): Gdk-CRITICAL **: 17:22:31.784: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)' failed

Thread 1 "gvim" received signal SIGSEGV, Segmentation fault.
0x00007ffff724cbff in gdk_x11_device_manager_xi2_translate_event () from /usr/lib64/libgdk-3.so.0
(gdb) bt
#0  0x00007ffff724cbff in gdk_x11_device_manager_xi2_translate_event () from /usr/lib64/libgdk-3.so.0
#1  0x00007ffff7257100 in _gdk_x11_event_translator_translate () from /usr/lib64/libgdk-3.so.0
#2  0x00007ffff7256cb9 in _gdk_x11_display_queue_events () from /usr/lib64/libgdk-3.so.0
#3  0x00007ffff7220bf1 in gdk_display_get_event () from /usr/lib64/libgdk-3.so.0
#4  0x00007ffff7256842 in gdk_event_source_dispatch () from /usr/lib64/libgdk-3.so.0
#5  0x00007ffff5f8de27 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#6  0x00007ffff5f8e060 in g_main_context_iterate.isra () from /usr/lib64/libglib-2.0.so.0
#7  0x00007ffff5f8e0ed in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#8  0x0000555555740efc in ?? ()
#9  0x000055555573023b in ?? ()
#10 0x00005555557321f1 in ?? ()
#11 0x000055555571778d in ?? ()
#12 0x000055555561d60a in ?? ()
#13 0x000055555561f008 in ?? ()
#14 0x000055555562044a in ?? ()
#15 0x000055555562075a in ?? ()
#16 0x0000555555668863 in ?? ()
#17 0x000055555575d714 in ?? ()
#18 0x000055555575e8ec in ?? ()
#19 0x000055555558acf8 in ?? ()
#20 0x00007ffff4bf4bef in __libc_start_main () from /lib64/libc.so.6
#21 0x000055555558c9ea in ?? ()
```

**Comment by brammool** [comment]
So this happens somewhere deep in the GTK code.  It's unlikely caused by Vim.  You may want to try searching for the error message in gtk context.

**Comment by SyntevoAlex** [comment]
This is a bug in GTK: https://gitlab.gnome.org/GNOME/gtk/issues/855

@jiwopene thanks for your steps, it helped me reproduce the problem.
