### ISSUE TITLE
SIGABRT when changing mintty screen size

### ISSUE THREAD

**Issue by mnishz** [vim/vim#4592]
**Describe the bug**
SIGABRT (double free or corruption) occurs when changing mintty screen size after calling popup_create() with 'pos': 'botright'.

**To Reproduce**
1. Type `Alt + F11` to set mintty screen size to full
1. Run `vim -Nu NONE`
1. Type `:call popup_create('foo', {'line': &lines-5, 'col': &columns-5, 'pos': 'botright'})`
1. Type `Alt + F10` to set mintty screen size to default
1. Type `Alt + F11` to set mintty screen size to full
1. SIGABRT occurs.

**Expected behavior**
No SIGABRT

**Screenshots**
![SIGABRT](https://user-images.githubusercontent.com/20806102/60107559-138cc700-97a2-11e9-9510-639eb6137c5e.gif)
Terminal 1: Vim
Terminal 2: GDB
Some upper and lower lines (like command line) were cut due to capture area restriction.

**Environment (please complete the following information):**
 - Vim version: v8.1.1592
 - OS: Windows 10 1809
 - Terminal: mintty
 - Windows + mintty -> SSH -> Ubuntu 18.04 + Vim

**Additional context**
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ff77c26c801 in __GI_abort () at abort.c:79
#2  0x00007ff77c2b5897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ff77c3e2b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ff77c2bc90a in malloc_printerr (str=str@entry=0x7ff77c3e4890 "double free or corruption (!prev)") at malloc.c:5350
#4  0x00007ff77c2c3e84 in _int_free (have_lock=0x0, p=0x5646b457fb70, av=0x7ff77c617c40 <main_arena>) at malloc.c:4281
#5  __GI___libc_free (mem=0x5646b457fb80) at malloc.c:3124
#6  0x00005646b3054fe4 in vim_free (x=0x5646b457fb80) at misc2.c:1805
#7  0x00005646b30eea79 in free_screenlines () at screen.c:9260
#8  0x00005646b30ee879 in screenalloc (doclear=0x0) at screen.c:9186
#9  0x00005646b30eec66 in screenclear () at screen.c:9280
#10 0x00005646b3148d0e in set_shellsize (width=0x0, height=0x0, mustset=0x0) at term.c:3462
#11 0x00005646b3148bc1 in shell_resized () at term.c:3376
#12 0x00005646b3096d6d in handle_resize () at os_unix.c:396
#13 0x00005646b309c700 in RealWaitForChar (fd=0x0, msec=0xffffffffffffffff, check_for_gpm=0x7ffcdacc5b30, interrupted=0x7ffcdacc5c00) at os_unix.c:6291
#14 0x00005646b309c2d8 in WaitForCharOrMouse (msec=0xffffffffffffffff, interrupted=0x7ffcdacc5c00, ignore_input=0x0) at os_unix.c:6004
#15 0x00005646b315d4ab in ui_wait_for_chars_or_timer (wtime=0xffffffffffffffff, wait_func=0x5646b309c24e <WaitForCharOrMouse>, interrupted=0x7ffcdacc5c00, ignore_input=0x0) at ui.c:475
#16 0x00005646b309c243 in WaitForChar (msec=0xffffffffffffffff, interrupted=0x7ffcdacc5c00, ignore_input=0x0) at os_unix.c:5940
#17 0x00005646b315d329 in inchar_loop (buf=0x5646b3442dd9 <typebuf_init+57> "", maxlen=0x45, wtime=0xffffffffffffffff, tb_change_cnt=0x12, wait_func=0x5646b309c216 <WaitForChar>, resize_func=0x5646b3096cef <resize_func>) at ui.c:383
#18 0x00005646b3096d58 in mch_inchar (buf=0x5646b3442dd9 <typebuf_init+57> "", maxlen=0x45, wtime=0xffffffffffffffff, tb_change_cnt=0x12) at os_unix.c:388
#19 0x00005646b315d116 in ui_inchar (buf=0x5646b3442dd9 <typebuf_init+57> "", maxlen=0x45, wtime=0xffffffffffffffff, tb_change_cnt=0x12) at ui.c:231
#20 0x00005646b3016b62 in inchar (buf=0x5646b3442dd9 <typebuf_init+57> "", maxlen=0xcf, wait_time=0xffffffffffffffff) at getchar.c:3097
#21 0x00005646b3016700 in vgetorpeek (advance=0x1) at getchar.c:2875
#22 0x00005646b3014874 in vgetc () at getchar.c:1602
#23 0x00005646b3014d57 in safe_vgetc () at getchar.c:1821
#24 0x00005646b3062ffb in normal_cmd (oap=0x7ffcdacc6040, toplevel=0x1) at normal.c:596
#25 0x00005646b31ae3bb in main_loop (cmdwin=0x0, noexmode=0x0) at main.c:1370
#26 0x00005646b31adb45 in vim_main2 () at main.c:903
#27 0x00005646b31ad37e in main (argc=0x3, argv=0x7ffcdacc6238) at main.c:444
```

**Comment by mattn** [comment]
Did not reproduce on cmd.exe or gvim.exe.
Probably, it can be reproduced on terminal emulator.

**Comment by mnishz** [comment]
I confirmed that the issue is not recreated with the latest Vim version. Thank you!
