### ISSUE TITLE
vim segfaults in nfa_regtry

### ISSUE THREAD

**Issue by mgedmin** [vim/vim#465]
Lately vim's been segfaulting rather a lot when I try to edit ReStructuredText files.  Here's a stack trace of today's crash:

```
Core was generated by `/home/mg/src/vim/src/vim practices.rst'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9ee7b48597 in kill () at ../sysdeps/unix/syscall-template.S:81
81  ../sysdeps/unix/syscall-template.S: Toks failas ar aplankas neegzistuoja.
(gdb) bt
#0  0x00007f9ee7b48597 in kill () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000055d10d in may_core_dump () at os_unix.c:3389
#2  0x000000000055d0b1 in mch_exit (r=1) at os_unix.c:3355
#3  0x0000000000645cc2 in getout (exitval=1) at main.c:1529
#4  0x00000000005152e5 in preserve_exit () at misc1.c:9622
#5  0x000000000055ae5e in deathtrap (sigarg=11) at os_unix.c:1118
#6  0x00007f9ee8366d10 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007f9ee7bb83df in __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:296
#8  0x0000000000519212 in vim_strnsave (string=0xffffffffe9efdc88 <error: Cannot access memory at address 0xffffffffe9efdc88>, len=376904638)
    at misc2.c:1268
#9  0x0000000000591dd6 in nfa_regtry (prog=0xde18a0, col=0, tm=0x0) at regexp_nfa.c:6961
#10 0x00000000005921ba in nfa_regexec_both (line=0xd8dec3 "   Fix permissions so you won't expose /etc/shadow and other secret files ::", startcol=0, tm=0x0) at regexp_nfa.c:7085
#11 0x0000000000592616 in nfa_regexec_multi (rmp=0x7fff6cf7ce60, win=0x96f4b0, buf=0x970e50, lnum=306, col=0, tm=0x0) at regexp_nfa.c:7298
#12 0x0000000000592a50 in vim_regexec_multi (rmp=0x7fff6cf7ce60, win=0x96f4b0, buf=0x970e50, lnum=306, col=0, tm=0x0) at regexp.c:8276
#13 0x00000000005dfc59 in syn_regexec (rmp=0x7fff6cf7ce60, lnum=306, col=0, st=0xe629f8) at syntax.c:3284
#14 0x00000000005dd547 in syn_current_attr (syncing=0, displaying=1, can_spell=0x0, keep_state=0) at syntax.c:2097
#15 0x00000000005dcd17 in get_syntax_attr (col=0, can_spell=0x0, keep_state=0) at syntax.c:1854
#16 0x000000000059b98f in win_line (wp=0x96f4b0, lnum=306, startrow=1, endrow=34, nochange=1) at screen.c:4402
#17 0x0000000000596355 in win_update (wp=0x96f4b0) at screen.c:2012
#18 0x0000000000593950 in update_screen (type=35) at screen.c:679
#19 0x00000000004b7708 in getcmdline (firstc=47, count=1, indent=0) at ex_getln.c:1858
#20 0x0000000000534fd9 in nv_search (cap=0x7fff6cf7d810) at normal.c:6334
#21 0x000000000052bb81 in normal_cmd (oap=0x7fff6cf7d8a0, toplevel=1) at normal.c:1163
#22 0x0000000000645992 in main_loop (cmdwin=0, noexmode=0) at main.c:1351
#23 0x00000000006452a9 in main (argc=2, argv=0x7fff6cf7dbb8) at main.c:1050
```

**Steps to reproduce**
- git clone https://github.com/mgedmin/vim-bug-465
- cd vim-bug-465
- valgrind vim -u rst.vim --noplugins example.rst +redraw +q
- watch for valgrind errors about "Conditional jump or move depends on uninitialised value(s)"

**Comment by mgedmin** [comment]
I have trouble getting vim to crash reproducibly.  Usually the crashes happen right on startup, and when I restart vim on the same file, it works.

**Comment by dpelle** [comment]
Which version of Vim are you using?
Maybe attaching the rst file that causes the bug could help others to reproduce.

Can you try running vim with valgrind?  Just use something like this:

  $ valgrind --log-file=valgrind.log  --track-origins=yes vim

And look into valgrind.log to see if valgrind finds errors.

You can also try with asan (address sanitizer). To use asan, you need to rebuild vim after uncommenting this line in vim/src/Makefile:

  #SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer

Then run vim normally.

**Comment by mgedmin** [comment]
vim 7.4.908, git hash a16f472edfa028e5574c7c145d02f3821edbc698

Valgrind produces this: https://gist.github.com/3bd0918194e40eb9682e

**Comment by mgedmin** [comment]
Tried again, with `--suppressions=/usr/lib/valgrind/python.supp`, but that didn't suppress anything.

https://github.com/python/cpython/blob/master/Misc/README.valgrind implies that I need to rebuild my Python in order to have it play nice with Valgrind.

Instead, I looked at the (new) valgrind log and manually ignored anything related to Python.  There were only 12 vim errors:

```
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x591D47: nfa_regtry (regexp_nfa.c:6957)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643==    by 0x59394F: update_screen (screen.c:679)
==20643==    by 0x645730: main_loop (main.c:1254)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x591D65: nfa_regtry (regexp_nfa.c:6958)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643==    by 0x59394F: update_screen (screen.c:679)
==20643==    by 0x645730: main_loop (main.c:1254)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x591D81: nfa_regtry (regexp_nfa.c:6959)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643==    by 0x59394F: update_screen (screen.c:679)
==20643==    by 0x645730: main_loop (main.c:1254)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x57365E: reg_getline (regexp.c:3715)
==20643==    by 0x591DB8: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643==    by 0x59394F: update_screen (screen.c:679)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x573672: reg_getline (regexp.c:3717)
==20643==    by 0x591DB8: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643==    by 0x59394F: update_screen (screen.c:679)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x4F4836: ml_get_buf (memline.c:2491)
==20643==    by 0x5736A0: reg_getline (regexp.c:3720)
==20643==    by 0x591DB8: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x4F489D: ml_get_buf (memline.c:2505)
==20643==    by 0x5736A0: reg_getline (regexp.c:3720)
==20643==    by 0x591DB8: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x4F48CA: ml_get_buf (memline.c:2517)
==20643==    by 0x5736A0: reg_getline (regexp.c:3720)
==20643==    by 0x591DB8: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x51908E: lalloc (misc2.c:890)
==20643==    by 0x518FD3: alloc (misc2.c:820)
==20643==    by 0x5191ED: vim_strnsave (misc2.c:1265)
==20643==    by 0x591DD5: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x4C2BB7C: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20643==    by 0x5190C5: lalloc (misc2.c:921)
==20643==    by 0x518FD3: alloc (misc2.c:820)
==20643==    by 0x5191ED: vim_strnsave (misc2.c:1265)
==20643==    by 0x591DD5: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643== 
==20643== Conditional jump or move depends on uninitialised value(s)
==20643==    at 0x4C2F5B7: __strncpy_sse2_unaligned (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20643==    by 0x519211: vim_strnsave (misc2.c:1268)
==20643==    by 0x591DD5: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643== 
==20643== Use of uninitialised value of size 8
==20643==    at 0x51921F: vim_strnsave (misc2.c:1269)
==20643==    by 0x591DD5: nfa_regtry (regexp_nfa.c:6961)
==20643==    by 0x5921B9: nfa_regexec_both (regexp_nfa.c:7085)
==20643==    by 0x592615: nfa_regexec_multi (regexp_nfa.c:7298)
==20643==    by 0x592A4F: vim_regexec_multi (regexp.c:8276)
==20643==    by 0x5DFC58: syn_regexec (syntax.c:3284)
==20643==    by 0x5DD546: syn_current_attr (syntax.c:2097)
==20643==    by 0x5DCB1A: syn_finish_line (syntax.c:1773)
==20643==    by 0x5DA73D: syntax_start (syntax.c:604)
==20643==    by 0x598A15: win_line (screen.c:3090)
==20643==    by 0x596354: win_update (screen.c:2012)
==20643==    by 0x59394F: update_screen (screen.c:679)
```

**Comment by mgedmin** [comment]
I crafted up a [custom valgrind suppressions file for Python](https://github.com/mgedmin/dotfiles/blob/master/python.supp) (looks like the original was tailored for 32-bit builds) and here's a full log of another run without false positives: https://gist.github.com/3a506caeef3e36e2bfee

**Comment by mgedmin** [comment]
Here's a valgrind log with `--track-origins=yes`: https://gist.github.com/f3ac6ab296a6e72b3432

**Comment by mgedmin** [comment]
Here's a publicly-available ReStructuredText file that causes valgrind errors for me: https://github.com/mgedmin/restview/blob/master/README.rst

**Comment by mgedmin** [comment]
I cannot reproduce with `vim -u NONE -U NONE +'syn on' README.rst`, therefore [my vim configuration](https://github.com/mgedmin/dotvim) may be relevant.

I use a custom ReStructuredText syntax file from https://github.com/mrsipan/vim-rst

**Comment by mgedmin** [comment]
`-fsanitize=address` detects some memory leaks in libpython2.7.so.1.0 but is otherwise oblivious.

`-fsanitize=undefined` reports this on startup, before vim switches to the alternate terminal buffer:

```
misc2.c:2109:2: runtime error: null pointer passed as argument 1, which is declared to never be null
```

I don't think it's related to the nfa_regtry crash.

**Comment by dpelle** [comment]
This recent checkin (7.4.887) fixed an uninitialized memory
in regexp_nfa.c. It only initialized end_lnum, I wonder whether
it had to initialize start_lnum too:

```
   $ git show c2b717ebd6719e722dcb5f10e4c74033a53ff7c7
   commit c2b717ebd6719e722dcb5f10e4c74033a53ff7c7
   Author: Bram Moolenaar <Bram@vim.org>
   Date:   Tue Sep 29 15:06:14 2015 +0200

       patch 7.4.887
       Problem:    Using uninitialized memory for regexp with back reference.
                   (Dominique Pelle)
       Solution:   Initialize end_lnum.
```

**Comment by mgedmin** [comment]
No: `start_lnum` is initialized a few lines above that change.

This must be a different code path.

**Comment by mgedmin** [comment]
Instructions for reproducing this: https://github.com/mgedmin/vim-bug-465

**Comment by mgedmin** [comment]
Smallest set of syntax rules that causes uninitialized memory access:

```
set cpo&vim
syn region  rstLiteralBlock
      \ start='\(^\z(\s*\).*\)\@<=::\(\s*$\)\@='
      \ skip='^$' end='^\(\z1\s\+\)\@!'
```

**Comment by mgedmin** [comment]
I've simplified the failing regexp to

```
set cpo&vim
syn region rstLiteralBlock
      \ start='\z(.\)\@<=:'
      \ end='^$'
```

Removing `set cpo&vim` makes the bug go away.
Removing `\@<=` makes the bug go away.
Replacing `\z(\)` with `\(\)` makes the bug go away.

**Comment by mgedmin** [comment]
Bug is present in all vim versions I tried since 7.4.001.  I had trouble trying to build 7.3.001 (something about a missing ruby/config.h).

**Comment by chrisbra** [comment]
Hi Marius!

On Do, 12 Nov 2015, Marius Gedminas wrote:

> I've simplified the failing regexp to
> 
> ```
> set cpo&vim
> syn region rstLiteralBlock
>       \ start='\z(.\)\@<=:'
>       \ end='^$'
> ```
> 
> Removing `set cpo&vim` makes the bug go away.
> Removing `\@<=` makes the bug go away.
> Replacing `\z(\)` with `\(\)` makes the bug go away.

So I assume, :set re=1 also fixes the issue?

Unfortunately I don't know the nfa code good enough to propose a 
solution.

Best,

## Christian

Anzahl mal Qualität gleicht einer Konstante...

**Comment by mgedmin** [comment]
Yes, `set re=1` also makes the bug go away.

**Comment by mgedmin** [comment]
Rebuilt regexp.c with `-DDEBUG`, got a bunch of log files and a bunch of new Valgrind errors (the debug dumping code also apparently accesses uninitialized memory).

Here's what nfa_regexp_dump.log says:

```
-------------------------
>>> NFA engine succeeded !
Regexp: "\z(.\)\@<=:"
Postfix notation (char): "NFA_ANY, NFA_ZOPEN(1), NFA_PREV_ATOM_JUST_BEFORE, CHAR(<FF>), CHAR(:), NFA_CONCAT , NFA_MOPEN(0), "
Postfix notation (int): -917 -936 -979 -1 58 -1014 -957 

( 7) NFA_MOPEN(0) (-957) (id=7) val=0
( 5) +-NFA_START_INVISIBLE_BEFORE (-993) (id=5) val=21
( 2)   +-NFA_ZOPEN(1) (-936) (id=2) val=0
( 1)   | +-NFA_ANY (-917) (id=1) val=0
( 3)   |   +-NFA_ZCLOSE(1) (-926) (id=3) val=0
( 4)   |     +-NFA_END_INVISIBLE (-988) (id=4) val=0
( 6)   |       +-CHAR(:) (58) (id=6) val=0
( 8)   |         +-NFA_MCLOSE(0) (-947) (id=8) val=0
( 0)   |           +-NFA_MATCH  (-1023) (id=0) val=0
( 4)   +-NFA_END_INVISIBLE (-988) (id=4) val=0
```

The `CHAR(<FF>)` looks weird, but it's probably just a misrepresentation of what it actually stands for.

nfa_regexp_debug.log is full of stuff like

```
-------------------
CHAR(c), CHAR(l), 
-------------------
CHAR(c), CHAR(l), 
-------------------
```

and I've no idea what it all means.  The relevant bits appear to be

```
-------------------
NFA_ZOPEN(1), NFA_ANY, 
-------------------
NFA_END_INVISIBLE, NFA_ZOPEN(1), NFA_ANY, 
-------------------
NFA_END_INVISIBLE, NFA_ZOPEN(1), NFA_ANY, 
-------------------
(repeated 18 more times)
-------------------
NFA_END_INVISIBLE, 
-------------------
NFA_START_INVISIBLE_BEFORE, CHAR(:), 
-------------------
NFA_START_INVISIBLE_BEFORE, CHAR(:), 
-------------------
(repeated 22 more times)
-------------------
NFA_MATCH , 
-------------------
NFA_BOL , NFA_EOL , NFA_MATCH , 
-------------------
NFA_START_INVISIBLE_BEFORE, CHAR(:), 
-------------------
NFA_START_INVISIBLE_BEFORE, CHAR(:), 
-------------------
(repeated 49 more times)
```

nfa_regexp_run.log is the longest of the debug files.  It shows three attempts to match `"\z(.\)\@<=:"`
Here's the first attempt: https://gist.github.com/mgedmin/fa16595450ce6746db38

Take a look at the last few lines:

```
(8) char -1023 NFA_MATCH  (start col 23) ... 
*** group 0, start: c=23, l=0, end: c=24, l=0
*** group 0, start: c=0, l=0, end: c=0, l=0
*** group 1, start: c=22, l=0, end: c=23, l=0
```

If I adjust my Valgrind command line to also do `--malloc-fill=cc`, then I see something interesting:

```
(8) char -1023 NFA_MATCH  (start col 23) ... 
*** group 0, start: c=23, l=0, end: c=24, l=0
*** group 0, start: c=-858993460, l=-858993460, end: c=-858993460, l=-858993460
*** group 1, start: c=22, l=0, end: c=23, l=0
```

It looks like the z group 0 is never initialized, but vim tries to store it in re_extmatch_out->matches[0] with vim_strnsave() anyway, and sometimes this causes segfaults.

**Comment by chrisbra** [comment]
This should be fixed, so closing.
