### ISSUE TITLE
Crash by SIGFPE.

### ISSUE THREAD

**Issue by zuoxinyu** [vim/vim#4746]
**Describe the bug**
I'm using the `coc.nvim` as a rust completion plugin. When the completion list is large (about 30+ items) and quickly tape `<C-n>/<C-p>/<TAB>` to retrieve these items it would crash by a SIGFPE signal, randomly. 

**To Reproduce**
1. make a long completion list.
2. quickly retrieve  these

**Expected behavior**
Completion list to work fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/9346419/62052090-6517ee00-b247-11e9-9753-63101b1d5573.png)

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  4 2019 23:02:48)
Included patches: 1-1635
Compiled by Arch Linux
 - OS: Manjaro 18.0.4 Illyria
 - Terminal: konsole

**Additional context**
Here is the full backtrace:
```
#0  0x00007f4f10019a5b in kill () at /usr/lib/libc.so.6
#1  0x000055a0fbc287f2 in mch_exit ()
#2  0x000055a0fbd4882d in getout ()
#3  0x00007f4f101b5d00 in <signal handler called> () at /usr/lib/libpthread.so.0
#4  0x000055a0fbc344f2 in update_popups ()
#5  0x000055a0fbc71e1d in update_screen ()
#6  0x000055a0fbb7e736 in ex_redraw ()
#7  0x000055a0fbb86045 in do_cmdline ()
#8  0x000055a0fbb49a2d in ex_execute ()
#9  0x000055a0fbb86045 in do_cmdline ()
#10 0x000055a0fbcd72d8 in call_func ()
#11 0x000055a0fbcd7b7c in get_func_tv ()
#12 0x000055a0fbb4f02d in  ()
#13 0x000055a0fbb4f794 in  ()
#14 0x000055a0fbb4fa64 in  ()
#15 0x000055a0fbb49074 in  ()
#16 0x000055a0fbb49213 in eval1 ()
#17 0x000055a0fbb49cf0 in eval0 ()
#18 0x000055a0fbcdaeb2 in ex_return ()
#19 0x000055a0fbb86045 in do_cmdline ()
#20 0x000055a0fbcd72d8 in call_func ()
#21 0x000055a0fbcd7d54 in call_callback ()
#22 0x000055a0fbb74b02 in check_due_timer ()
#23 0x000055a0fbcc8da6 in ui_wait_for_chars_or_timer ()
#24 0x000055a0fbc250b6 in  ()
#25 0x000055a0fbccacf1 in inchar_loop ()
#26 0x000055a0fbcca75c in ui_inchar ()
#27 0x000055a0fbbb19b0 in  ()
#28 0x000055a0fbbb32b5 in  ()
#29 0x000055a0fbbb4b18 in vgetc ()
#30 0x000055a0fbbb4da9 in safe_vgetc ()
#31 0x000055a0fbb3c656 in edit ()
#32 0x000055a0fbbf9307 in  ()
#33 0x000055a0fbbf9e56 in  ()
#34 0x000055a0fbc058a9 in normal_cmd ()
#35 0x000055a0fbd4972c in main_loop ()
#36 0x000055a0fbd4aac9 in vim_main2 ()
#37 0x000055a0fbb16b79 in main ()
```

**Comment by brammool** [comment]
Should be fixed by Patch 8.1.1665.  Please reopen if not.
