### ISSUE TITLE
Building vim with Python 3.8 fails when loading python plugins

### ISSUE THREAD

**Issue by antonioshadji** [vim/vim#5509]
**Describe the bug**
After installing Python3.8.1 from source, building vim with python 3.8 succeeds, but loading python plugins fails.  I don't think it is plugin specific as multiple plugins are having an issue loading python libraries.

This error show when editing markdown file with vim-pandoc plugin
```
ImportError: /usr/local/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyTuple_Type
```
This error shows up when activating jedi-vim plugin with `packadd jedi-vim`  I've shown just the first error but it shows for every has function in the all available list. 
```
Error detected while processing function jedi#init_python[4]..<SNR>103_init_python[27]..jedi#setup_python_imports:
line   25:
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/hashlib.py", line 251, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5

```

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Download, build, and install python tag v3.8.1 from github.
2. edit test.py file: 
```python
import sys
print(sys.version)
```
3. Command `:pack-add jedi-vim`  jedi-vim is in `~/.vim/pack/plugins/opt/jedi-vim`
4. Errors show on screen, then vim continues normally until next call to python

**Expected behavior**
Expected vim build with latest python to build and work the same as vim built with system python (3.6.9)

**Environment :**
vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 20 2020 10:36:51)
Included patches: 1-132
Compiled by Antonios Hadjigeorgalis
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
-arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
+autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            +mzscheme          +terminfo
+balloon_eval_term +fork()            -netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     -perl              +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          -rightleft         +wildignore
+cursorbind        +lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             -sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -DMZ_PRECISE_GC -pthread -DMZSCHEME_CONFIGDIR=/usr/local/etc/racket -DINCLUDE_MZSCHEME_BASE -I/usr/local/include/racket       -DMZSCHEME_COLLECTS=/usr/local/share/racket/collects 
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE /usr/local/lib/libracket3m.a -pthread -lffi -lm -ltinfo -lnsl   -ldl  -L/usr/local/lib/x86_64-linux-gnu -lluajit-5.1   -L/usr/local/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm  
```
 - OS:
```
11:05 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
11:06 $ uname -a
Linux hadji 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
 - Terminal: GNOME Terminal, same issue arises with gVim

**Comment by antonioshadji** [comment]
vim configured with:
```
./configure \
  --enable-autoservername \
  --enable-cscope \
  --enable-fail-if-missing \
  --enable-gnome-check \
  --enable-gui=gtk3 \
  --enable-luainterp=yes \
  --enable-multibyte \
  --enable-mzschemeinterp \
  --enable-python3interp=yes \
  --enable-terminal \
  --with-lua-prefix=/usr/local \
  --with-luajit \
  --with-plthome=/usr/local \
  --with-python3-command=/usr/local/bin/python3.8 \
  --disable-rightleft  \
  --disable-arabic     \
  --disable-netbeans
```

**Comment by ichizok** [comment]
Perhaps your vim may have linked the static library (libpython3.8.a).
Please check `ldd /path/to/vim`.

**Comment by antonioshadji** [comment]
@ichizok Yes, it did link the static library.  But when I configure with `--enable-python3interp=dynamic` python3 is unavailable in vim as shown by `has('python3')` returning 0

**Comment by mcepl** [comment]
> ```
> ImportError: /usr/local/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyTuple_Type
> ```

This is a problem in your Python installation. [PyTuple_Type](https://docs.python.org/3/c-api/tuple.html?highlight=pytuple_type#c.PyTuple_Type) is quite essential Python type. If you don't have it, you are … how to say it politely?

> ```
> Error detected while processing function jedi#init_python[4]..<SNR>103_init_python[27]..jedi#setup_python_imports:
> line   25:
> ERROR:root:code for hash md5 was not found.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/hashlib.py", line 251, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/usr/local/lib/python3.8/hashlib.py", line 120, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type md5
> ```

This is either bug in jedi or in your Python again. It doesn't look like anything vim specific.

>     1. Download, build, and install python tag v3.8.1 from github.

Did you run `./python -m test -j3` on your build of Python, and does it pass?

**Comment by mrepper** [comment]
Try adding -rdynamic to LDFLAGS so that libpython.a's symbols are visible to subsequent .so files that get loaded:

```
LDFLAGS="-rdynamic" ./configure \
[...]
```

**Comment by wvangeit** [comment]
@mrepper FYI, the
`LDFLAGS="-rdynamic"`
fixed the issue for me.
Thanks.

**Comment by chrisbra** [comment]
I am closing this, as this seems to be configuration problem.
