### ISSUE TITLE
Segmentation fault when moving terminal buffer to a separate tab and back

### ISSUE THREAD

**Issue by ghost** [vim/vim#6308]
**Describe the bug**
Here is a minimal `vimrc` with a toggle function for zooming in/out any arbitrary buffer. 

```
set nocompatible              " be iMproved, required
filetype plugin indent on     " Load plugins according to detected filetype.
syntax on                     " Enable syntax highlighting.

" ZoomWin
function! s:ZoomWinTabIn() abort
    let l:tabpage = tabpagenr()
    exe 'tab split'
    if l:tabpage != tabpagenr()
        let t:zoomwintab = 1
        let t:zoomwintabnr = l:tabpage
    endif
endfunction

" ZoomWinTabClose
function! s:ZoomWinTabOut() abort
    unlet t:zoomwintab
    let l:tabpage = t:zoomwintabnr
    tabclose
    " switch to zoomin tab
    if tabpagenr() != l:tabpage
        exe 'tabnext '.l:tabpage
    endif
endfunction

" ZoomWinTabToggle
function! s:ZoomWinTabToggle() abort
    if exists('t:zoomwintab')
        call <sid>ZoomWinTabOut()
    else
        call <sid>ZoomWinTabIn()
    endif
endfunction
tnoremap <silent> <F9>  <C-w>:call <sid>ZoomWinTabToggle()<cr>
```

**To Reproduce**
Detailed steps to reproduce the behavior:
1.  Using the above `vimrc`, open vim. 
2.  Open a terminal buffer (`:terminal`). 
3.  Type `ls -al` in the terminal buffer (don't skip this step - must have some text in terminal). 
4.  Press `F9` to 'zoom into' the buffer. 
5.  Press `F9` again to zoom out. This should lead to a segmentation fault crash (sometimes have to press `F9` a few times. Note that this segmentation fault only occurs on terminal buffers. All other buffers zoom in/ out just fine.

**Environment (please complete the following information):**
 - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 31 2020 11:30:11) Included patches: 1-856
 - OS: Ubuntu 18.04
 - Terminal: mintty

**Comment by dpelle** [comment]
I can reproduce it with vim-8.2.1024 on Linux x86_64.

Valgrind report:
```
==20482== Memcheck, a memory error detector
==20482== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20482== Using Valgrind-3.17.0.GIT and LibVEX; rerun with -h for copyright info
==20482== Command: ./vim
==20482== 
==20482== Invalid read of size 1
==20482==    at 0x3D7E9F: on_csi (state.c:1166)
==20482==    by 0x3CF1F0: do_csi (parser.c:36)
==20482==    by 0x3CF98D: vterm_input_write (parser.c:240)
==20482==    by 0x36D09E: term_write_job_output (terminal.c:1075)
==20482==    by 0x36D249: write_to_term (terminal.c:1146)
==20482==    by 0x3FC5E4: may_invoke_callback (channel.c:2964)
==20482==    by 0x3FF4B4: channel_parse_messages (channel.c:4656)
==20482==    by 0x22DFB9: parse_queued_messages (getchar.c:2188)
==20482==    by 0x38850B: inchar_loop (ui.c:290)
==20482==    by 0x2B40C5: mch_inchar (os_unix.c:388)
==20482==    by 0x38844C: ui_inchar (ui.c:224)
==20482==    by 0x22FF72: inchar (getchar.c:3514)
==20482==    by 0x22FB57: vgetorpeek (getchar.c:3293)
==20482==    by 0x22D4D3: vgetc (getchar.c:1687)
==20482==    by 0x36F39A: term_vgetc (terminal.c:2028)
==20482==    by 0x36FE96: terminal_loop (terminal.c:2476)
==20482==    by 0x413476: main_loop (main.c:1499)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482==  Address 0xb0fed08 is 8 bytes before a block of size 92 alloc'd
==20482==    at 0x4C2FECB: malloc (vg_replace_malloc.c:307)
==20482==    by 0x27AB76: lalloc (misc2.c:925)
==20482==    by 0x27AA84: alloc_clear (misc2.c:852)
==20482==    by 0x37384E: vterm_malloc (terminal.c:4349)
==20482==    by 0x3DBA22: vterm_allocator_malloc (vterm.c:97)
==20482==    by 0x3DA8BC: on_resize (state.c:1819)
==20482==    by 0x3DBB06: vterm_set_size (vterm.c:123)
==20482==    by 0x3722FC: term_update_window (terminal.c:3724)
==20482==    by 0x1B5F40: win_update (drawscreen.c:1465)
==20482==    by 0x1B35AD: update_screen (drawscreen.c:310)
==20482==    by 0x413272: main_loop (main.c:1398)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482== 
==20482== Invalid read of size 1
==20482==    at 0x3D4A5D: erase (state.c:59)
==20482==    by 0x3D7F6D: on_csi (state.c:1176)
==20482==    by 0x3CF1F0: do_csi (parser.c:36)
==20482==    by 0x3CF98D: vterm_input_write (parser.c:240)
==20482==    by 0x36D09E: term_write_job_output (terminal.c:1075)
==20482==    by 0x36D249: write_to_term (terminal.c:1146)
==20482==    by 0x3FC5E4: may_invoke_callback (channel.c:2964)
==20482==    by 0x3FF4B4: channel_parse_messages (channel.c:4656)
==20482==    by 0x22DFB9: parse_queued_messages (getchar.c:2188)
==20482==    by 0x38850B: inchar_loop (ui.c:290)
==20482==    by 0x2B40C5: mch_inchar (os_unix.c:388)
==20482==    by 0x38844C: ui_inchar (ui.c:224)
==20482==    by 0x22FF72: inchar (getchar.c:3514)
==20482==    by 0x22FB57: vgetorpeek (getchar.c:3293)
==20482==    by 0x22D4D3: vgetc (getchar.c:1687)
==20482==    by 0x36F39A: term_vgetc (terminal.c:2028)
==20482==    by 0x36FE96: terminal_loop (terminal.c:2476)
==20482==    by 0x413476: main_loop (main.c:1499)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482==  Address 0xb0fed0c is 4 bytes before a block of size 92 alloc'd
==20482==    at 0x4C2FECB: malloc (vg_replace_malloc.c:307)
==20482==    by 0x27AB76: lalloc (misc2.c:925)
==20482==    by 0x27AA84: alloc_clear (misc2.c:852)
==20482==    by 0x37384E: vterm_malloc (terminal.c:4349)
==20482==    by 0x3DBA22: vterm_allocator_malloc (vterm.c:97)
==20482==    by 0x3DA8BC: on_resize (state.c:1819)
==20482==    by 0x3DBB06: vterm_set_size (vterm.c:123)
==20482==    by 0x3722FC: term_update_window (terminal.c:3724)
==20482==    by 0x1B5F40: win_update (drawscreen.c:1465)
==20482==    by 0x1B35AD: update_screen (drawscreen.c:310)
==20482==    by 0x413272: main_loop (main.c:1398)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482== 
==20482== Invalid write of size 1
==20482==    at 0x3D4A63: erase (state.c:59)
==20482==    by 0x3D7F6D: on_csi (state.c:1176)
==20482==    by 0x3CF1F0: do_csi (parser.c:36)
==20482==    by 0x3CF98D: vterm_input_write (parser.c:240)
==20482==    by 0x36D09E: term_write_job_output (terminal.c:1075)
==20482==    by 0x36D249: write_to_term (terminal.c:1146)
==20482==    by 0x3FC5E4: may_invoke_callback (channel.c:2964)
==20482==    by 0x3FF4B4: channel_parse_messages (channel.c:4656)
==20482==    by 0x22DFB9: parse_queued_messages (getchar.c:2188)
==20482==    by 0x38850B: inchar_loop (ui.c:290)
==20482==    by 0x2B40C5: mch_inchar (os_unix.c:388)
==20482==    by 0x38844C: ui_inchar (ui.c:224)
==20482==    by 0x22FF72: inchar (getchar.c:3514)
==20482==    by 0x22FB57: vgetorpeek (getchar.c:3293)
==20482==    by 0x22D4D3: vgetc (getchar.c:1687)
==20482==    by 0x36F39A: term_vgetc (terminal.c:2028)
==20482==    by 0x36FE96: terminal_loop (terminal.c:2476)
==20482==    by 0x413476: main_loop (main.c:1499)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482==  Address 0xb0fed0c is 4 bytes before a block of size 92 alloc'd
==20482==    at 0x4C2FECB: malloc (vg_replace_malloc.c:307)
==20482==    by 0x27AB76: lalloc (misc2.c:925)
==20482==    by 0x27AA84: alloc_clear (misc2.c:852)
==20482==    by 0x37384E: vterm_malloc (terminal.c:4349)
==20482==    by 0x3DBA22: vterm_allocator_malloc (vterm.c:97)
==20482==    by 0x3DA8BC: on_resize (state.c:1819)
==20482==    by 0x3DBB06: vterm_set_size (vterm.c:123)
==20482==    by 0x3722FC: term_update_window (terminal.c:3724)
==20482==    by 0x1B5F40: win_update (drawscreen.c:1465)
==20482==    by 0x1B35AD: update_screen (drawscreen.c:310)
==20482==    by 0x413272: main_loop (main.c:1398)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482== 
==20482== Invalid read of size 4
==20482==    at 0x30824B: screen_line (screen.c:435)
==20482==    by 0x37245D: term_update_window (terminal.c:3751)
==20482==    by 0x1B5F40: win_update (drawscreen.c:1465)
==20482==    by 0x1B35AD: update_screen (drawscreen.c:310)
==20482==    by 0x36D29C: write_to_term (terminal.c:1167)
==20482==    by 0x3FC5E4: may_invoke_callback (channel.c:2964)
==20482==    by 0x3FF4B4: channel_parse_messages (channel.c:4656)
==20482==    by 0x22DFB9: parse_queued_messages (getchar.c:2188)
==20482==    by 0x38850B: inchar_loop (ui.c:290)
==20482==    by 0x2B40C5: mch_inchar (os_unix.c:388)
==20482==    by 0x38844C: ui_inchar (ui.c:224)
==20482==    by 0x22FF72: inchar (getchar.c:3514)
==20482==    by 0x22FB57: vgetorpeek (getchar.c:3293)
==20482==    by 0x22D4D3: vgetc (getchar.c:1687)
==20482==    by 0x36F39A: term_vgetc (terminal.c:2028)
==20482==    by 0x36FE96: terminal_loop (terminal.c:2476)
==20482==    by 0x413476: main_loop (main.c:1499)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482==  Address 0xa032968 is 8 bytes before a block of size 196 alloc'd
==20482==    at 0x4C2FECB: malloc (vg_replace_malloc.c:307)
==20482==    by 0x27AB76: lalloc (misc2.c:925)
==20482==    by 0x30C724: screenalloc (screen.c:2642)
==20482==    by 0x30D518: screenclear (screen.c:2897)
==20482==    by 0x3661F5: set_shellsize (term.c:3461)
==20482==    by 0x3646FC: set_termname (term.c:2143)
==20482==    by 0x364D9E: termcapinit (term.c:2519)
==20482==    by 0x411EB5: main (main.c:378)
==20482== 
==20482== Invalid read of size 4
==20482==    at 0x308279: screen_line (screen.c:437)
==20482==    by 0x37245D: term_update_window (terminal.c:3751)
==20482==    by 0x1B5F40: win_update (drawscreen.c:1465)
==20482==    by 0x1B35AD: update_screen (drawscreen.c:310)
==20482==    by 0x36D29C: write_to_term (terminal.c:1167)
==20482==    by 0x3FC5E4: may_invoke_callback (channel.c:2964)
==20482==    by 0x3FF4B4: channel_parse_messages (channel.c:4656)
==20482==    by 0x22DFB9: parse_queued_messages (getchar.c:2188)
==20482==    by 0x38850B: inchar_loop (ui.c:290)
==20482==    by 0x2B40C5: mch_inchar (os_unix.c:388)
==20482==    by 0x38844C: ui_inchar (ui.c:224)
==20482==    by 0x22FF72: inchar (getchar.c:3514)
==20482==    by 0x22FB57: vgetorpeek (getchar.c:3293)
==20482==    by 0x22D4D3: vgetc (getchar.c:1687)
==20482==    by 0x36F39A: term_vgetc (terminal.c:2028)
==20482==    by 0x36FE96: terminal_loop (terminal.c:2476)
==20482==    by 0x413476: main_loop (main.c:1499)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482==  Address 0xa032968 is 8 bytes before a block of size 196 alloc'd
==20482==    at 0x4C2FECB: malloc (vg_replace_malloc.c:307)
==20482==    by 0x27AB76: lalloc (misc2.c:925)
==20482==    by 0x30C724: screenalloc (screen.c:2642)
==20482==    by 0x30D518: screenclear (screen.c:2897)
==20482==    by 0x3661F5: set_shellsize (term.c:3461)
==20482==    by 0x3646FC: set_termname (term.c:2143)
==20482==    by 0x364D9E: termcapinit (term.c:2519)
==20482==    by 0x411EB5: main (main.c:378)
==20482== 
==20482== Invalid write of size 1
==20482==    at 0x308BE8: screen_line (screen.c:784)
==20482==    by 0x37245D: term_update_window (terminal.c:3751)
==20482==    by 0x1B5F40: win_update (drawscreen.c:1465)
==20482==    by 0x1B35AD: update_screen (drawscreen.c:310)
==20482==    by 0x36D29C: write_to_term (terminal.c:1167)
==20482==    by 0x3FC5E4: may_invoke_callback (channel.c:2964)
==20482==    by 0x3FF4B4: channel_parse_messages (channel.c:4656)
==20482==    by 0x22DFB9: parse_queued_messages (getchar.c:2188)
==20482==    by 0x38850B: inchar_loop (ui.c:290)
==20482==    by 0x2B40C5: mch_inchar (os_unix.c:388)
==20482==    by 0x38844C: ui_inchar (ui.c:224)
==20482==    by 0x22FF72: inchar (getchar.c:3514)
==20482==    by 0x22FB57: vgetorpeek (getchar.c:3293)
==20482==    by 0x22D4D3: vgetc (getchar.c:1687)
==20482==    by 0x36F39A: term_vgetc (terminal.c:2028)
==20482==    by 0x36FE96: terminal_loop (terminal.c:2476)
==20482==    by 0x413476: main_loop (main.c:1499)
==20482==    by 0x412830: vim_main2 (main.c:898)
==20482==    by 0x412013: main (main.c:442)
==20482==  Address 0xa032a7e is 2 bytes before a block of size 49 alloc'd
==20482==    at 0x4C2FECB: malloc (vg_replace_malloc.c:307)
==20482==    by 0x27AB76: lalloc (misc2.c:925)
==20482==    by 0x30C73C: screenalloc (screen.c:2643)
==20482==    by 0x30D518: screenclear (screen.c:2897)
==20482==    by 0x3661F5: set_shellsize (term.c:3461)
==20482==    by 0x3646FC: set_termname (term.c:2143)
==20482==    by 0x364D9E: termcapinit (term.c:2519)
==20482==    by 0x411EB5: main (main.c:378)
==20482== 
==20482== 
==20482== HEAP SUMMARY:
==20482==     in use at exit: 97,038 bytes in 1,657 blocks
==20482==   total heap usage: 61,222 allocs, 59,565 frees, 27,880,880 bytes allocated
==20482== 
==20482== LEAK SUMMARY:
==20482==    definitely lost: 520 bytes in 1 blocks
==20482==    indirectly lost: 132 bytes in 6 blocks
==20482==      possibly lost: 0 bytes in 0 blocks
==20482==    still reachable: 96,386 bytes in 1,650 blocks
==20482==         suppressed: 0 bytes in 0 blocks
==20482== Rerun with --leak-check=full to see details of leaked memory
==20482== 
==20482== For lists of detected and suppressed errors, rerun with: -s
==20482== ERROR SUMMARY: 9 errors from 6 contexts (suppressed: 0 from 0)
```
Address sanitizer report:
```
=================================================================
==21214==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x608000006c98 at pc 0x5576be09a59d bp 0x7fffae6f4c90 sp 0x7fffae6f4c80
READ of size 1 at 0x608000006c98 thread T0
    #0 0x5576be09a59c in on_csi libvterm/src/state.c:1166
    #1 0x5576be07fbfc in do_csi libvterm/src/parser.c:36
    #2 0x5576be0813f0 in vterm_input_write libvterm/src/parser.c:240
    #3 0x5576bdf7d297 in term_write_job_output /home/pel/sb/vim/src/terminal.c:1075
    #4 0x5576bdf7d65a in write_to_term /home/pel/sb/vim/src/terminal.c:1146
    #5 0x5576be0ee917 in may_invoke_callback /home/pel/sb/vim/src/channel.c:2964
    #6 0x5576be0f4998 in channel_parse_messages /home/pel/sb/vim/src/channel.c:4656
    #7 0x5576bdc50515 in parse_queued_messages /home/pel/sb/vim/src/getchar.c:2188
    #8 0x5576bdfc639d in inchar_loop /home/pel/sb/vim/src/ui.c:290
    #9 0x5576bddbff97 in mch_inchar /home/pel/sb/vim/src/os_unix.c:388
    #10 0x5576bdfc616b in ui_inchar /home/pel/sb/vim/src/ui.c:224
    #11 0x5576bdc578f0 in inchar /home/pel/sb/vim/src/getchar.c:3514
    #12 0x5576bdc569ea in vgetorpeek /home/pel/sb/vim/src/getchar.c:3293
    #13 0x5576bdc4e605 in vgetc /home/pel/sb/vim/src/getchar.c:1687
    #14 0x5576bdf824d4 in term_vgetc /home/pel/sb/vim/src/terminal.c:2028
    #15 0x5576bdf84141 in terminal_loop /home/pel/sb/vim/src/terminal.c:2476
    #16 0x5576be124d83 in main_loop /home/pel/sb/vim/src/main.c:1499
    #17 0x5576be123a39 in vim_main2 /home/pel/sb/vim/src/main.c:898
    #18 0x5576be12308c in main /home/pel/sb/vim/src/main.c:442
    #19 0x7f883408eb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #20 0x5576bda4ae69 in _start (/home/pel/sb/vim/src/vim+0x15ae69)

0x608000006c98 is located 8 bytes to the left of 92-byte region [0x608000006ca0,0x608000006cfc)
allocated by thread T0 here:
    #0 0x7f8836c8fb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x5576bdd0c35f in lalloc /home/pel/sb/vim/src/misc2.c:925
    #2 0x5576bdd0c1f9 in alloc_clear /home/pel/sb/vim/src/misc2.c:852
    #3 0x5576bdf8eb98 in vterm_malloc /home/pel/sb/vim/src/terminal.c:4349
    #4 0x5576be0a4b1d in vterm_allocator_malloc libvterm/src/vterm.c:97
    #5 0x5576be0a15d0 in on_resize libvterm/src/state.c:1819
    #6 0x5576be0a4e55 in vterm_set_size libvterm/src/vterm.c:123
    #7 0x5576bdf8aec0 in term_update_window /home/pel/sb/vim/src/terminal.c:3724
    #8 0x5576bdb0c0db in win_update /home/pel/sb/vim/src/drawscreen.c:1465
    #9 0x5576bdb03b13 in update_screen /home/pel/sb/vim/src/drawscreen.c:310
    #10 0x5576be124ac3 in main_loop /home/pel/sb/vim/src/main.c:1398
    #11 0x5576be123a39 in vim_main2 /home/pel/sb/vim/src/main.c:898
    #12 0x5576be12308c in main /home/pel/sb/vim/src/main.c:442
    #13 0x7f883408eb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: heap-buffer-overflow libvterm/src/state.c:1166 in on_csi
Shadow bytes around the buggy address:
  0x0c107fff8d40: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c107fff8d50: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff8d60: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c107fff8d70: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c107fff8d80: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
=>0x0c107fff8d90: fa fa fa[fa]00 00 00 00 00 00 00 00 00 00 00 04
  0x0c107fff8da0: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 04
  0x0c107fff8db0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8dc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8dd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8de0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21214==ABORTING
```
It looks like the same bug as https://github.com/vim/vim/issues/6273 which is closed yet I could still reproduce with:
```
$ vim --clean -cter -c'call feedkeys("\<c-w>\<c-w>", "tx")' -c'sleep 200m' -cresize
```

**Comment by ghost** [comment]
Just confirmed. Issue fixed in new build. Closing. Thank you!
