### ISSUE TITLE
Python3 triggers symbol not found error when using stripped vim binary, but OK with non-stripped one

### ISSUE THREAD

**Issue by inyeollee** [vim/vim#7551]
**Describe the bug**

Compiled Vim 8.2.2117 from source. If running the command below:
```
$ vim --cmd 'py3 import struct'
```
It throws an exception:
```
Error detected while processing pre-vimrc command line:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/inyeol/util/lib/python3.9/struct.py", line 13, in <module>
    from _struct import *
ImportError: dlopen(/Users/inyeol/util/lib/python3.9/lib-dynload/_struct.cpython-39-darwin.so, 2): Symbol not found: _PyByteArray_Type
  Referenced from: /Users/inyeol/util/lib/python3.9/lib-dynload/_struct.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/inyeol/util/lib/python3.9/lib-dynload/_struct.cpython-39-darwin.so
Press ENTER or type command to continue
```
There were similar reports: #3629 and #5509, and the workaround was to add *LDFLAGS="-rdynamic"* for configure script, but it didn't work for me (shows the same exception). The workaround I found was not to strip the vim binary during installation. Here is the build flow I used, including the workaround:
```
$ ./configure  --prefix=$HOME/util  --enable-gui=no  --enable-python3interp  --with-python3-config-dir=$HOME/util/lib/python3.9/config-3.9-darwin   --with-features=huge
$ make
## Test passes without error.
$ make test
## Install strips vim binary.
$ make install
$ vim --cmd 'py3 import struct'
   ... (error message described above)
## Replace stripped binary with non-stripped one.
$ cp __vim_compilation_directory__/vim $HOME/util/bin
## With non-stripped binary, this line doesn't trigger error any more.
$ vim --cmd 'py3 import struct'
$
```

**Environment (please complete the following information):**
- Vim version: 8.2.2117
- OS: macOS 11.1
- Python version: 3.9.1
- Terminal: macOS Terminal

**Additional context**
Python 3.9.1 embedded in vim is also compiled from the source with:
```
./configure --prefix=$HOME/util --with-openssl=$HOME/util --enable-optimizations
```
It ran the test suite without any unexpected failure.

**Comment by hepyu** [comment]
I had the same problem. how to solve it ?
my vim version is: 8.2.2232

**Comment by XonqNopp** [comment]
I have the same problem on Debian with py3.10... @inyeollee How did you solve this?

**Comment by chrisbra** [comment]
I suppose the workaround is to not-strip the binary. See https://github.com/vim/vim/blob/master/src/Makefile#L1173-L1175
