### ISSUE TITLE
Vim9: crash when using list with a circular reference

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7979]
**Describe the bug**

In Vim9 script, creating a list with a circular reference might make Vim crash (actually, I'm not sure that's what really causes the crash...).

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9script
        var l = []
        var d = {a: 0}
        l = [d]
        l[0].e = {b: l}
        w:name = {f: {c: d}}
        getwininfo()->filter((_, v) => true)
    EOF
    )

Vim crashes.

**Expected behavior**

Vim doesn't crash.

**Environment**

 - Vim version: 8.2 Included patches: 1-2618
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Comment by lacygoill** [comment]
I don't have logs for now.  It took a looong time to get this MWE.  Loading the core in gdb gives this:

    Reading symbols from ./src/vim...
    [New LWP 14200]
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    Core was generated by `./src/vim -Nu NONE -S /proc/self/fd/11'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x000000000066ef10 in typval2type_int (
        tv=<error reading variable: Cannot access memory at address 0x7ffe7f789fc8>,
        type_gap=<error reading variable: Cannot access memory at address 0x7ffe7f789fc0>) at vim9type.c:258
    258     {
    #1  0x000000000066f347 in typval2type (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #2  0x000000000066efe0 in typval2type_int (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:281
    #3  0x000000000066f347 in typval2type (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #4  0x000000000066f0c2 in typval2type_int (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:300
    #5  0x000000000066f347 in typval2type (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #6  0x000000000066f0df in typval2type_int (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:302
    #7  0x000000000066f347 in typval2type (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #8  0x000000000066efe0 in typval2type_int (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:281
    #9  0x000000000066f347 in typval2type (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #10 0x000000000066f0c2 in typval2type_int (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:300
    #11 0x000000000066f347 in typval2type (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #12 0x000000000066f0df in typval2type_int (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:302
    #13 0x000000000066f347 in typval2type (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #14 0x000000000066efe0 in typval2type_int (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:281
    #15 0x000000000066f347 in typval2type (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #16 0x000000000066f0c2 in typval2type_int (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:300
    #17 0x000000000066f347 in typval2type (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #18 0x000000000066f0df in typval2type_int (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:302
    #19 0x000000000066f347 in typval2type (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #20 0x000000000066efe0 in typval2type_int (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:281
    #21 0x000000000066f347 in typval2type (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #22 0x000000000066f0c2 in typval2type_int (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:300
    #23 0x000000000066f347 in typval2type (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #24 0x000000000066f0df in typval2type_int (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:302
    #25 0x000000000066f347 in typval2type (tv=0x1f275c0, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #26 0x000000000066efe0 in typval2type_int (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:281
    #27 0x000000000066f347 in typval2type (tv=0x1f27640, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    #28 0x000000000066f0c2 in typval2type_int (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:300
    #29 0x000000000066f347 in typval2type (tv=0x1f27660, type_gap=0x7ffe7ff828f0) at vim9type.c:377
    ...
