### ISSUE TITLE
Vim9: parse error with nested multiline lambda

### ISSUE THREAD

**Issue by lilydjwg** [vim/vim#8575]
**Describe the bug**

**To Reproduce**
Detailed steps to reproduce the behavior:
1. `vim --clean`
2. Source the script:
```vim
vim9script

echo range(3)->mapnew((_, v) => range(v)->mapnew((_, s) => string(s)))

echo range(4)
  ->mapnew((_, v) => {
    return range(v)
      ->mapnew((_, s) => {
        return string(s)
      })
  })
```
3. The first nested lambda works, but not the latter one
```
[[], ['0'], ['0', '1']]                                                                                                                                                               
Error detected while compiling /home/lilydjwg/tmpfs/b.vim[10]..function <lambda>24:                                                                                                   
第    2 行:                                                                                                                                                                           
E1171: Missing } after inline function                                                                                                                                                
处理 /home/lilydjwg/tmpfs/b.vim 时发生错误:                                                                                                                                           
第   10 行:                                                                                                                                                                           
E116: 函式 mapnew((_, v) => { 的引數不正確                                                                                                                                            
```

**Expected behavior**
Multiline lambdas should be parsed successfully.

**Environment (please complete the following information):**
 - Vim version 8.2.3159
 - OS: Arch Linux
 - Terminal: GNOME Terminal

**Comment by lilydjwg** [comment]
I even get Vim crashes with the following script:

```vim
vim9script

def s:func()
  range(10)
    ->mapnew((_, _) => ({
      key: range(10)->mapnew((_, _) => {
        return ' '
      }),
    }))
enddef

defc
```

(Source multiple times until it crashes.)

```backtrace
#0  0x00007f5857a9001b in kill () at /usr/lib/libc.so.6
#1  0x00005652a87f88d4 in may_core_dump () at os_unix.c:3456
#2  may_core_dump () at os_unix.c:3451
#3  mch_exit (r=1) at os_unix.c:3422
#4  0x00007f5857c32870 in <signal handler called> () at /usr/lib/libpthread.so.0
#5  skipwhite (q=q@entry=0x5652a9688896 <error: Cannot access memory at address 0x5652a9688896>) at charset.c:1469
#6  0x00005652a88d6230 in compile_subscript (ppconst=0x7ffe9a4106f0, end_leader=0x7ffe9a410378, start_leader=<optimized out>, cctx=0x7ffe9a411520, arg=0x7ffe9a410a98)
    at vim9compile.c:4186
#7  compile_expr7 (ppconst=0x5652a9688896, cctx=0x7ffe9a411520, arg=0x7ffe9a411520) at vim9compile.c:4703
#8  compile_expr7t (arg=arg@entry=0x7ffe9a410a98, cctx=cctx@entry=0x7ffe9a411520, ppconst=ppconst@entry=0x7ffe9a4106f0) at vim9compile.c:4760
#9  0x00005652a88d7903 in compile_expr6 (arg=arg@entry=0x7ffe9a410a98, cctx=cctx@entry=0x7ffe9a411520, ppconst=ppconst@entry=0x7ffe9a4106f0) at vim9compile.c:4796
#10 0x00005652a88d7bc8 in compile_expr5 (arg=arg@entry=0x7ffe9a410a98, cctx=cctx@entry=0x7ffe9a411520, ppconst=ppconst@entry=0x7ffe9a4106f0) at vim9compile.c:4875
```
