### ISSUE TITLE
SIGSEGV in vim at ex_getln.c:630

### ISSUE THREAD

**Issue by irfanariq** [vim/vim#8953]
Hello,

We are currently working on fuzz testing feature, and we found a **SIGSEGV** on `vim`.

The stack traces are as follow:
```st
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff6e6957c in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
#2  0x000055555582061e in may_adjust_incsearch_highlighting (firstc=47, count=1, is_state=0x7fffffffd750, c=20) at ex_getln.c:630
#3  0x0000555555827f99 in getcmdline_int (firstc=47, count=1, indent=0, clear_ccline=1) at ex_getln.c:2261
#4  0x0000555555824adb in getcmdline (firstc=47, count=1, indent=0, do_concat=1) at ex_getln.c:1556
#5  0x00005555559903a5 in nv_search (cap=0x7fffffffda40) at normal.c:4337
#6  0x000055555597c684 in normal_cmd (oap=0x7fffffffdb80, toplevel=1) at normal.c:1099
#7  0x0000555555da04b2 in main_loop (cmdwin=0, noexmode=0) at main.c:1501
#8  0x0000555555d9f249 in vim_main2 () at main.c:878
#9  0x0000555555d9e90d in main (argc=10, argv=0x7fffffffddc8) at main.c:425
```
Here is the full stack trace : [full_stacktrace_poc_1.zip](https://github.com/vim/vim/files/7279435/full_stacktrace_poc_1.zip)

**Step to reproduce**

We configured `vim` using `CFLAGS="-g -O0 -fsanitize=address" CXXFLAGS="-g -O0 -fsanitize=address" LDFLAGS="-g -O0 -fsanitize=address" ./configure --prefix=$(pwd)/` and build it using `make -j10`, and run it with:

```
./vim -u NONE --cmd + -Z --clean -s <attached file> -C
```
Attachment: [input_vim_poc_1.zip](https://github.com/vim/vim/files/7279441/input_vim_poc_1.zip)

**Environment**
- OS: Ubuntu 18.04.5 LTS
- GCC version: gcc 7.5.0
- vim version: latest commit (50c56893) of master branch in github ([link]([https://github.com/vim/vim/tree/50c56893423eb6ad2154a4151e67f7097f52efb6]))

Thank you.

**Comment by brammool** [comment]
A fuzzer tends to use lots of text that doesn't matter.
Please reduce the input to the absolute minimum.  Then we could use it as a regression test.

**Comment by dpelle** [comment]
@brammool  asked:

> Please reduce the input to the absolute minimum. 

I minimized it to this:
```
$ ./vim --clean -c 'call feedkeys("//\x14")'
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault (core dumped)
```

With gdb:
```
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00000000004b687c in may_adjust_incsearch_highlighting (firstc=47, count=1, 
    is_state=0x7fffffffd9a8, c=20) at ex_getln.c:630
#2  0x00000000004b0a48 in getcmdline_int (firstc=47, count=1, indent=0, clear_ccline=1)
    at ex_getln.c:2261
#3  0x00000000004af199 in getcmdline (firstc=47, count=1, indent=0, do_concat=1) at ex_getln.c:1556
#4  0x000000000054a25c in nv_search (cap=0x7fffffffdbd8) at normal.c:4337
#5  0x0000000000544710 in normal_cmd (oap=0x7fffffffdc60, toplevel=1) at normal.c:1099
#6  0x000000000070f5ab in main_loop (cmdwin=0, noexmode=0) at main.c:1501
#7  0x000000000070dd5a in vim_main2 () at main.c:878
#8  0x000000000070b5d8 in main (argc=4, argv=0x7fffffffde48) at main.c:425

(gdb) up
#1  0x00000000004b687c in may_adjust_incsearch_highlighting (firstc=47, count=1, 
    is_state=0x7fffffffd9a8, c=20) at ex_getln.c:630
630		patlen = (int)STRLEN(pat);

(gdb) list
625	
626	    if (search_delim == ccline.cmdbuff[skiplen])
627	    {
628		pat = last_search_pattern();
629		skiplen = 0;
630		patlen = (int)STRLEN(pat);
631	    }
632	    else
633		pat = ccline.cmdbuff + skiplen;
634	

(gdb) p pat
$1 = (char_u *) 0x0
```

So `pat` is NULL at line `ex_getln.c:630`.

**Comment by dpelle** [comment]
This minimization may be better:
```
$ ./vim --clean -c 'call feedkeys("//\<C-g>")'
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault (core dumped)
```

**Comment by dpelle** [comment]
All these commands crash in a similar way:
```
vim --clean -c 'call feedkeys("//\<C-g>")'
vim --clean -c 'call feedkeys("//\<C-t>")'
vim --clean -c 'call feedkeys("??\<C-g>")'
vim --clean -c 'call feedkeys("??\<C-t>")'
```
