### ISSUE TITLE
heap-buffer-overflow in vim at skip_string (src/cindent.c:94)

### ISSUE THREAD

**Issue by irfanariq** [vim/vim#8964]
Hello,

We are currently working on fuzz testing feature, and we found a **heap-buffer-overflow** on `vim`.

The stack traces are as follow:
```st
==25536==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000012900 at pc 0x562b81ffecf3 bp 0x7fff8f674610 sp 0x7fff8f674600
READ of size 1 at 0x621000012900 thread T0
    #0 0x562b81ffecf2 in skip_string .../vim-git/src/cindent.c:94
    #1 0x562b82003e96 in find_last_paren .../vim-git/src/cindent.c:1131
    #2 0x562b8201367e in get_c_indent .../vim-git/src/cindent.c:3713
    #3 0x562b821f94cf in op_reindent .../vim-git/src/indent.c:1060
    #4 0x562b822febd6 in do_pending_operator .../vim-git/src/ops.c:3998
    #5 0x562b822b5adf in normal_cmd .../vim-git/src/normal.c:1125
    #6 0x562b82144188 in exec_normal .../vim-git/src/ex_docmd.c:8574
    #7 0x562b82143f64 in exec_normal_cmd .../vim-git/src/ex_docmd.c:8537
    #8 0x562b82143805 in ex_normal .../vim-git/src/ex_docmd.c:8455
    #9 0x562b82121e30 in do_one_cmd .../vim-git/src/ex_docmd.c:2614
```
Here is the full stack trace : [full_stacktrace_poc_6.zip](https://github.com/vim/vim/files/7288148/full_stacktrace_poc_6.zip)

**Step to reproduce**

We configured `vim` using `CFLAGS="-g -O0 -fsanitize=address" CXXFLAGS="-g -O0 -fsanitize=address" LDFLAGS="-g -O0 -fsanitize=address" ./configure --prefix=$(pwd)/` and build it using `make -j10`, and run it with:

```
./vim -u NONE -X -Z -e -s -S <attached file> -c ':qa!'
```
Attachment: [input_vim_poc_6.zip](https://github.com/vim/vim/files/7288146/input_vim_poc_6.zip)

**Environment**
- OS: Ubuntu 18.04.5 LTS
- GCC version: gcc 7.5.0
- vim version: latest commit (f67d3fb7) of master branch in github ([link](https://github.com/vim/vim/tree/f67d3fb7363ebc9454f9bb582de3978609a4fd6b))

Thank you.

**Comment by dpelle** [comment]
I can reproduce it with the latest vim-8.2.3480 and minimized it to an obscure 2-line script:
```
$ cat bug.vim
exe "norm v>O'\\\<C-m>-"
exe "norm \<C-q>="
```
```
$ valgrind ./vim --clean -e -s -S bug.vim -c'q!'
==11501== Memcheck, a memory error detector
==11501== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11501== Using Valgrind-3.17.0.GIT and LibVEX; rerun with -h for copyright info
==11501== Command: ./vim --clean -e -s -S bug.vim -cq!
==11501== 
==11501== Invalid read of size 1
==11501==    at 0x423FCA: skip_string (cindent.c:94)
==11501==    by 0x429CF4: find_last_paren (cindent.c:1131)
==11501==    by 0x427D72: get_c_indent (cindent.c:3713)
==11501==    by 0x4F6AA4: op_reindent (indent.c:1060)
==11501==    by 0x55AE8E: do_pending_operator (ops.c:3998)
==11501==    by 0x5448FB: normal_cmd (normal.c:1125)
==11501==    by 0x4A4E3A: exec_normal (ex_docmd.c:8574)
==11501==    by 0x4A4CE3: exec_normal_cmd (ex_docmd.c:8537)
==11501==    by 0x4A4C09: ex_normal (ex_docmd.c:8455)
==11501==    by 0x49C664: do_one_cmd (ex_docmd.c:2614)
==11501==    by 0x49978F: do_cmdline (ex_docmd.c:1000)
==11501==    by 0x46C110: ex_execute (eval.c:6250)
==11501==  Address 0xa4395a0 is 0 bytes after a block of size 4,096 alloc'd
==11501==    at 0x4C32FB5: malloc (vg_replace_malloc.c:380)
==11501==    by 0x406636: lalloc (alloc.c:244)
==11501==    by 0x4065D9: alloc (alloc.c:151)
==11501==    by 0x71162D: mf_alloc_bhdr (memfile.c:884)
==11501==    by 0x71129A: mf_new (memfile.c:376)
==11501==    by 0x51EEA0: ml_new_data (memline.c:4068)
==11501==    by 0x51E990: ml_open (memline.c:394)
==11501==    by 0x40F82F: open_buffer (buffer.c:190)
==11501==    by 0x70E286: create_windows (main.c:2851)
==11501==    by 0x70DAD3: vim_main2 (main.c:704)
==11501==    by 0x70B727: main (main.c:425)
==11501== 
==11501== 
==11501== HEAP SUMMARY:
==11501==     in use at exit: 2,061,571 bytes in 17,219 blocks
==11501==   total heap usage: 31,280 allocs, 14,061 frees, 17,157,897 bytes allocated
==11501== 
==11501== LEAK SUMMARY:
==11501==    definitely lost: 0 bytes in 0 blocks
==11501==    indirectly lost: 0 bytes in 0 blocks
==11501==      possibly lost: 3,759 bytes in 67 blocks
==11501==    still reachable: 2,057,812 bytes in 17,152 blocks
==11501==         suppressed: 0 bytes in 0 blocks
==11501== Rerun with --leak-check=full to see details of leaked memory
==11501== 
==11501== For lists of detected and suppressed errors, rerun with: -s
==11501== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```
