### ISSUE TITLE
heap-buffer-overflow in vim at vim_strncpy (src/strings.c:509)

### ISSUE THREAD

**Issue by irfanariq** [vim/vim#8965]
Hello,

We are currently working on fuzz testing feature, and we found a **heap-buffer-overflow** on `vim`.

The stack traces are as follow:
```st
==25575==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000058936 at pc 0x7fd83c27e806 bp 0x7ffc875a9740 sp 0x7ffc875a8ee8
READ of size 1 at 0x602000058936 thread T0
    #0 0x7fd83c27e805 in __interceptor_strncpy (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x94805)
    #1 0x55f2497160d1 in vim_strncpy .../vim-git/src/strings.c:509
    #2 0x55f24970f2aa in check_suggestions .../vim-git/src/spellsuggest.c:3620
    #3 0x55f2496fb99f in spell_suggest_intern .../vim-git/src/spellsuggest.c:1055
    #4 0x55f2496faa38 in spell_find_suggest .../vim-git/src/spellsuggest.c:870
    #5 0x55f2496f7e08 in spell_suggest .../vim-git/src/spellsuggest.c:545
    #6 0x55f24951c890 in nv_zet .../vim-git/src/normal.c:3218
    #7 0x55f24950f93b in normal_cmd .../vim-git/src/normal.c:1099
```
Here is the full stack trace : [full_stacktrace_poc_7.zip](https://github.com/vim/vim/files/7288158/full_stacktrace_poc_7.zip)

**Step to reproduce**

We configured `vim` using `CFLAGS="-g -O0 -fsanitize=address" CXXFLAGS="-g -O0 -fsanitize=address" LDFLAGS="-g -O0 -fsanitize=address" ./configure --prefix=$(pwd)/` and build it using `make -j10`, and run it with:

```
./vim -u NONE -X -Z -e -s -S <attached file> -c ':qa!'
```
Attachment: [input_vim_poc_7.zip](https://github.com/vim/vim/files/7288160/input_vim_poc_7.zip)

**Environment**
- OS: Ubuntu 18.04.5 LTS
- GCC version: gcc 7.5.0
- vim version: latest commit (f67d3fb7) of master branch in github ([link](https://github.com/vim/vim/tree/f67d3fb7363ebc9454f9bb582de3978609a4fd6b))

Thank you.

**Comment by dpelle** [comment]
I can reproduce.
But I could only minimize to an obscure yet short `input_vim_poc_7_minimized` which I attach.

[input_vim_poc_7_minimized.gz](https://github.com/vim/vim/files/7289121/input_vim_poc_7_minimized.gz)

With an asan build of Vim-8.2.3481:
```
$ gzip -d input_vim_poc_7_minimized.gz
$ ./vim --clean -e -s -S input_vim_poc_7_minimized
=================================================================
==525==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200006c6b5 at pc 0x7f62aab21806 bp 0x7ffdf7145640 sp 0x7ffdf7144de8
READ of size 1 at 0x60200006c6b5 thread T0
    #0 0x7f62aab21805 in __interceptor_strncpy (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x94805)
    #1 0x555ef4ae860c in vim_strncpy /home/pel/sb/vim/src/strings.c:509
    #2 0x555ef4ae17e5 in check_suggestions /home/pel/sb/vim/src/spellsuggest.c:3620
    #3 0x555ef4acdeda in spell_suggest_intern /home/pel/sb/vim/src/spellsuggest.c:1055
    #4 0x555ef4accf73 in spell_find_suggest /home/pel/sb/vim/src/spellsuggest.c:870
    #5 0x555ef4aca343 in spell_suggest /home/pel/sb/vim/src/spellsuggest.c:545
    #6 0x555ef48e729b in nv_zet /home/pel/sb/vim/src/normal.c:3218
    #7 0x555ef48da053 in normal_cmd /home/pel/sb/vim/src/normal.c:1099
    #8 0x555ef4761d74 in exec_normal /home/pel/sb/vim/src/ex_docmd.c:8574
    #9 0x555ef4761b50 in exec_normal_cmd /home/pel/sb/vim/src/ex_docmd.c:8537
    #10 0x555ef47613f1 in ex_normal /home/pel/sb/vim/src/ex_docmd.c:8455
    #11 0x555ef473f9e8 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2614
    #12 0x555ef4736997 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:1000
    #13 0x555ef46d1bc1 in ex_execute /home/pel/sb/vim/src/eval.c:6250
    #14 0x555ef473f9e8 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2614
    #15 0x555ef4736997 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:1000
    #16 0x555ef4a56710 in do_source /home/pel/sb/vim/src/scriptfile.c:1406
    #17 0x555ef4a54725 in cmd_source /home/pel/sb/vim/src/scriptfile.c:971
    #18 0x555ef4a54792 in ex_source /home/pel/sb/vim/src/scriptfile.c:997
    #19 0x555ef473f9e8 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2614
    #20 0x555ef4736997 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:1000
    #21 0x555ef4734d86 in do_cmdline_cmd /home/pel/sb/vim/src/ex_docmd.c:594
    #22 0x555ef4d0c312 in exe_commands /home/pel/sb/vim/src/main.c:3081
    #23 0x555ef4d04f43 in vim_main2 /home/pel/sb/vim/src/main.c:773
    #24 0x555ef4d047cc in main /home/pel/sb/vim/src/main.c:425
    #25 0x7f62a8a94bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #26 0x555ef45bfbe9 in _start (/home/pel/sb/vim/src/vim+0x12bbe9)

0x60200006c6b5 is located 0 bytes to the right of 5-byte region [0x60200006c6b0,0x60200006c6b5)
allocated by thread T0 here:
    #0 0x7f62aab6bb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x555ef45c0037 in lalloc /home/pel/sb/vim/src/alloc.c:244
    #2 0x555ef45bfe34 in alloc /home/pel/sb/vim/src/alloc.c:151
    #3 0x555ef4ae6696 in vim_strsave /home/pel/sb/vim/src/strings.c:27
    #4 0x555ef4aca23b in spell_suggest /home/pel/sb/vim/src/spellsuggest.c:535
    #5 0x555ef48e729b in nv_zet /home/pel/sb/vim/src/normal.c:3218
    #6 0x555ef48da053 in normal_cmd /home/pel/sb/vim/src/normal.c:1099
    #7 0x555ef4761d74 in exec_normal /home/pel/sb/vim/src/ex_docmd.c:8574
    #8 0x555ef4761b50 in exec_normal_cmd /home/pel/sb/vim/src/ex_docmd.c:8537
    #9 0x555ef47613f1 in ex_normal /home/pel/sb/vim/src/ex_docmd.c:8455
    #10 0x555ef473f9e8 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2614
    #11 0x555ef4736997 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:1000
    #12 0x555ef46d1bc1 in ex_execute /home/pel/sb/vim/src/eval.c:6250
    #13 0x555ef473f9e8 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2614
    #14 0x555ef4736997 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:1000
    #15 0x555ef4a56710 in do_source /home/pel/sb/vim/src/scriptfile.c:1406
    #16 0x555ef4a54725 in cmd_source /home/pel/sb/vim/src/scriptfile.c:971
    #17 0x555ef4a54792 in ex_source /home/pel/sb/vim/src/scriptfile.c:997
    #18 0x555ef473f9e8 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2614
    #19 0x555ef4736997 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:1000
    #20 0x555ef4734d86 in do_cmdline_cmd /home/pel/sb/vim/src/ex_docmd.c:594
    #21 0x555ef4d0c312 in exe_commands /home/pel/sb/vim/src/main.c:3081
    #22 0x555ef4d04f43 in vim_main2 /home/pel/sb/vim/src/main.c:773
    #23 0x555ef4d047cc in main /home/pel/sb/vim/src/main.c:425
    #24 0x7f62a8a94bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x94805) in __interceptor_strncpy
Shadow bytes around the buggy address:
  0x0c0480005880: fa fa 04 fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c0480005890: fa fa fd fa fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c04800058a0: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c04800058b0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 02 fa
  0x0c04800058c0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa 00 fa
=>0x0c04800058d0: fa fa 02 fa fa fa[05]fa fa fa 04 fa fa fa 04 fa
  0x0c04800058e0: fa fa 05 fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c04800058f0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c0480005900: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c0480005910: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c0480005920: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==525==ABORTING
ASAN:DEADLYSIGNAL
=================================================================
==525==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/asan/asan_report.cc:211 "((current_error_.kind)) == ((kErrorKindInvalid))" (0xe, 0x0)
ASAN:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```
