### ISSUE TITLE
stack-buffer-overflow in vim at leave_block (src/ex_eval.c:970)

### ISSUE THREAD

**Issue by irfanariq** [vim/vim#8966]
Hello,

We are currently working on fuzz testing feature, and we found a **stack-buffer-overflow** on `vim`.

The stack traces are as follow:
```st
==25686==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffcabdcd36e at pc 0x5593bdb08020 bp 0x7ffcabdccd90 sp 0x7ffcabdccd80
READ of size 2 at 0x7ffcabdcd36e thread T0
    #0 0x5593bdb0801f in leave_block .../vim-git/src/ex_eval.c:970
    #1 0x5593bdb0e735 in ex_endtry .../vim-git/src/ex_eval.c:2108
    #2 0x5593bdadce30 in do_one_cmd .../vim-git/src/ex_docmd.c:2614
    #3 0x5593bdad3cf8 in do_cmdline .../vim-git/src/ex_docmd.c:1000
    #4 0x5593bdde5e2d in do_source .../vim-git/src/scriptfile.c:1406
    #5 0x5593bdde3e42 in cmd_source .../vim-git/src/scriptfile.c:971
    #6 0x5593bdde3eaf in ex_source .../vim-git/src/scriptfile.c:997
```
Here is the full stack trace : [full_stacktrace_poc_8.zip](https://github.com/vim/vim/files/7288171/full_stacktrace_poc_8.zip)
 
**Step to reproduce**

We configured `vim` using `CFLAGS="-g -O0 -fsanitize=address" CXXFLAGS="-g -O0 -fsanitize=address" LDFLAGS="-g -O0 -fsanitize=address" ./configure --prefix=$(pwd)/` and build it using `make -j10`, and run it with:

```
./vim -u NONE -X -Z -e -s -S <attached file> -c ':qa!'
```
Attachment: [input_vim_poc_8.zip](https://github.com/vim/vim/files/7288167/input_vim_poc_8.zip)

**Environment**
- OS: Ubuntu 18.04.5 LTS
- GCC version: gcc 7.5.0
- vim version: latest commit (f67d3fb7) of master branch in github ([link](https://github.com/vim/vim/tree/f67d3fb7363ebc9454f9bb582de3978609a4fd6b))

Thank you.

**Comment by dpelle** [comment]
I can't reproduce this bug so far.  Unclear what I'm missing.
I'm using vim-8.2.3481 on xubuntu-18.04.6 with clang-12.
Shooting in the dark: @irfanariq what is your locale?  (output of the `locale` command).

**Comment by dpelle** [comment]
> I can't reproduce this bug so far.

Never mind, I can reproduce it after all with vim-8.2.3481.
I was trying with valgrind, but since it's an overflow in stack variable, only asan finds the bug.

I minimized it to this silly looking script:
```
$ cat bug.vim
vim9script
try #
for x in []
if
endwhile
if
endtry
```
Even if the script is not valid, Vim should not access invalid memory.
```
$ ./vim --clean -e -s -S bug.vim 
=================================================================
==31188==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffb241402e at pc 0x556e62828c8d bp 0x7fffb2413a50 sp 0x7fffb2413a40
READ of size 2 at 0x7fffb241402e thread T0
    #0 0x556e62828c8c in leave_block /home/pel/sb/vim/src/ex_eval.c:970
    #1 0x556e6282f3a2 in ex_endtry /home/pel/sb/vim/src/ex_eval.c:2108
    #2 0x556e627fd9e8 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2614
    #3 0x556e627f4997 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:1000
    #4 0x556e62b14710 in do_source /home/pel/sb/vim/src/scriptfile.c:1406
    #5 0x556e62b12725 in cmd_source /home/pel/sb/vim/src/scriptfile.c:971
    #6 0x556e62b12792 in ex_source /home/pel/sb/vim/src/scriptfile.c:997
    #7 0x556e627fd9e8 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2614
    #8 0x556e627f4997 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:1000
    #9 0x556e627f2d86 in do_cmdline_cmd /home/pel/sb/vim/src/ex_docmd.c:594
    #10 0x556e62dca312 in exe_commands /home/pel/sb/vim/src/main.c:3081
    #11 0x556e62dc2f43 in vim_main2 /home/pel/sb/vim/src/main.c:773
    #12 0x556e62dc27cc in main /home/pel/sb/vim/src/main.c:425
    #13 0x7f20c6ec2bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #14 0x556e6267dbe9 in _start (/home/pel/sb/vim/src/vim+0x12bbe9)

Address 0x7fffb241402e is located in stack of thread T0 at offset 382 in frame
    #0 0x556e627f2dc1 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:634

  This frame has 6 object(s):
    [32, 40) 'cmdline_copy'
    [96, 104) 'private_msg_list'
    [160, 184) 'lines_ga'
    [224, 256) 'cmd_loop_cookie'
    [288, 352) 'debug_saved'
    [384, 1968) 'cstack' <== Memory access at offset 382 underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/pel/sb/vim/src/ex_eval.c:970 in leave_block
Shadow bytes around the buggy address:
  0x10007647a7b0: 00 00 00 00 f2 f2 00 00 00 00 00 00 00 00 00 00
  0x10007647a7c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007647a7d0: 00 00 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2 f2 f2
  0x10007647a7e0: f2 f2 00 f2 f2 f2 f2 f2 f2 f2 00 00 00 f2 f2 f2
  0x10007647a7f0: f2 f2 00 00 00 00 f2 f2 f2 f2 00 00 00 00 00 00
=>0x10007647a800: 00 00 f2 f2 f2[f2]00 00 00 00 00 00 00 00 00 00
  0x10007647a810: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007647a820: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007647a830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007647a840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007647a850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==31188==ABORTING
Aborted (core dumped)
```

With gdb:
```
$ gdb --args ./vim --clean -e -s -S bug.vim
(gdb) run
(gdb) up
#1  0x00007ffff4e3e921 in __GI_abort () at abort.c:79
79	abort.c: No such file or directory.
(gdb) 
#2  0x00007ffff6f1872e in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
(gdb) 
#3  0x00007ffff6f20518 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
(gdb) 
#4  0x00007ffff6f01515 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.4
(gdb) 
#5  0x00007ffff6f020f7 in __asan_report_load2 () from /usr/lib/x86_64-linux-gnu/libasan.so.4
(gdb) 
#6  0x000055555582ac8d in leave_block (cstack=0x7fffffffc6a0) at ex_eval.c:970
970				       cstack->cs_flags[cstack->cs_idx] & CSF_FUNC_DEF;
(gdb) list
965	    if (in_vim9script() && SCRIPT_ID_VALID(current_sctx.sc_sid))
966	    {
967		scriptitem_T	*si = SCRIPT_ITEM(current_sctx.sc_sid);
968		int		i;
969		int		func_defined =
970				       cstack->cs_flags[cstack->cs_idx] & CSF_FUNC_DEF;
971	
972		for (i = cstack->cs_script_var_len[cstack->cs_idx];
973						       i < si->sn_var_vals.ga_len; ++i)
974		{
(gdb) p cstack->cs_idx
$1 = -1
```
`cstack->cs_idx` is `-1` so `cs_flags[cstack->cs_idx]` at line `ex_eval.c:970` accesses invalid memory in stack.
