### ISSUE TITLE
[Python] Environment variables are not inherited

### ISSUE THREAD

**Issue by char101** [vim/vim#9120]
### Steps to reproduce

Hi,

I just noticed that environment variables set in vim is not accessible/inherited by python:

For example

1. `:let $ABC='def'`
2. `:py3 import os; print(os.environ['ABC'])`

results in

`KeyError: 'ABC'`

Is this behavior by design?

### Expected behaviour

`def`

### Operating system

Windows 10

### Version of Vim

8.2.3582

### Logs and stack traces

```shell
KeyError: 'ABC'
```

**Comment by k-takata** [comment]
I confirmed that this works on Linux.

This occurs when Vim and Python use different versions or types of the C runtime libraries, because each CRT has its own storage for the environment variables.
The binaries from vim-win32-installer are linked against VC 2015's static link library, but Python 3.9 is linked against VC 2019's dynamic link library. If both used the same version of the dynamic library, that would work.

**Comment by char101** [comment]
I tried it in Arch linux and it shows the same result:

![2021-11-11 18_30_04-Window](https://user-images.githubusercontent.com/71255/141290917-84efad01-eec9-4495-abee-3ecc7bf9d6a7.png)

**Comment by k-takata** [comment]
How about this on Linux? `py3 import os | let $ABC='def' | py3 print(os.environ['ABC'])`

Did you compile with `USE_MSVCRT=yes` on Windows?

**Comment by mattn** [comment]
I confirmed that it works as charm with msys2/mingw64 compiler.

**Comment by mattn** [comment]
I guess that this is caused by the difference between the runtime library when Vim is built and the Python dll runtime.

**Comment by char101** [comment]
> How about this on Linux? `py3 import os | let $ABC='def' | py3 print(os.environ['ABC'])`

`:exe ":py3 import os" | let $ABC='def' | py3 print(os.environ['ABC'])`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'ABC'
```

> Did you compile with `USE_MSVCRT=yes` on Windows?

Yes

The runtime library is the same. This is the output of `ldd.exe` from msys:

```
gvim.exe: PE32+ executable (GUI) x86-64, for MS Windows
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fff2df50000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fff2d380000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fff2b6d0000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7fff2ca30000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fff2cc20000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fff2c6c0000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fff2d440000)
        SHELL32.dll => /c/WINDOWS/System32/SHELL32.dll (0x7fff2d740000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7fff2bad0000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fff2b9d0000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7fff2ccc0000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7fff2bf70000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7fff2dee0000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7fff2bc70000)
        SHLWAPI.dll => /c/WINDOWS/System32/SHLWAPI.dll (0x7fff2de80000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7fff2c9c0000)
        COMCTL32.dll => /c/WINDOWS/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e/COMCTL32.dll (0x7fff15a30000)
        NETAPI32.dll => /c/WINDOWS/SYSTEM32/NETAPI32.dll (0x7fff1a090000)
        VERSION.dll => /c/WINDOWS/SYSTEM32/VERSION.dll (0x7fff21800000)
        lua51.dll => /c/Apps/Editor/vim/lua51.dll (0x7fff19fa0000)
        WSOCK32.dll => /c/WINDOWS/SYSTEM32/WSOCK32.dll (0x7fff10b60000)
        VCRUNTIME140.dll => /c/WINDOWS/SYSTEM32/VCRUNTIME140.dll (0x7fff272c0000)
        SAMCLI.DLL => /c/WINDOWS/SYSTEM32/SAMCLI.DLL (0x7fff190b0000)
        NETUTILS.DLL => /c/WINDOWS/SYSTEM32/NETUTILS.DLL (0x7fff2abd0000)
```

```
python310.dll: PE32+ executable (DLL) (GUI) x86-64, for MS Windows
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fff2df50000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fff2d380000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fff2b6d0000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7fff2c9c0000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fff2d440000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7fff2ca30000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fff2cc20000)
        VERSION.dll => /c/WINDOWS/SYSTEM32/VERSION.dll (0x7fff21800000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7fff2c6c0000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fff2b9d0000)
        VCRUNTIME140.dll => /c/WINDOWS/SYSTEM32/VCRUNTIME140.dll (0x7fff272c0000)
```

![2021-11-11 19_02_52-Window](https://user-images.githubusercontent.com/71255/141294924-a3120dbb-0d2c-4990-ae27-b157b930010a.png)

**Comment by char101** [comment]
For comparison, in debian where vim is statically linked (not statically compiled) with python.so, the command works

```sh
# ldd /usr/bin/vim
        linux-vdso.so.1 =>  (0x00007ffd3e3e5000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0163b88000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f016395f000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f016373d000)
        libacl.so.1 => /lib/x86_64-linux-gnu/libacl.so.1 (0x00007f0163535000)
        libgpm.so.2 => /usr/lib/x86_64-linux-gnu/libgpm.so.2 (0x00007f016332e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f016312a000)
        libpython3.5m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0 (0x00007f0162aa3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0162886000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f01624bc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f01642f1000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f016224c000)
        libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 (0x00007f0162047000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f0161e1e000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0161c04000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0161a01000)
```

```
:version | let $ABC='def' | py3 import os; print(os.environ['ABC'])
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 13 2020 16:04:38)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +channel         +comments        +diff            +extra_search    +fork()          +keymap          -lua             +mouse_gpm       +multi_byte      +persistent_undo +reltime         +statusline      +terminfo        +vertsplit       +wildmenu        -xterm_clipboard
+arabic          +cindent         +conceal         +digraphs        +farsi           +gettext         +langmap         +menu            -mouse_jsbterm   +multi_lang      +postscript      +rightleft       -sun_workshop    +termresponse    +virtualedit     +windows         -xterm_save
+autocmd         -clientserver    +cryptv          -dnd             +file_in_path    -hangul_input    +libcall         +mksession       +mouse_netterm   -mzscheme        +printer         -ruby            +syntax          +textobjects     +visual          +writebackup     -xpm
-balloon_eval    -clipboard       +cscope          -ebcdic          +find_in_path    +iconv           +linebreak       +modify_fname    +mouse_sgr       +netbeans_intg   +profile         +scrollbind      +tag_binary      +timers          +visualextra     -X11
-browse          +cmdline_compl   +cursorbind      +emacs_tags      +float           +insert_expand   +lispindent      +mouse           -mouse_sysmouse  +packages        -python          +signs           +tag_old_static  +title           +viminfo         -xfontset
++builtin_terms  +cmdline_hist    +cursorshape     +eval            +folding         +job             +listcmds        -mouseshape      +mouse_urxvt     +path_extra      +python3         +smartindent     -tag_any_white   -toolbar         +vreplace        -xim
+byte_offset     +cmdline_info    +dialog_con      +ex_extra        -footer          +jumplist        +localmap        +mouse_dec       +mouse_xterm     -perl            +quickfix        +startuptime     -tcl             +user_commands   +wildignore      -xsmp
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm
def
Press ENTER or type command to continue
```

**Comment by char101** [comment]
The reverse command works though in GVim:

```
exe "py3 import os; os.environ['ABC'] = 'def'" | echo $ABC
```

```
def
```

**Comment by char101** [comment]
`win32api.GetEnvironmentVariable` works so I think this is caused by python caching `os.environ` when the `os` module is loaded and does not pick environment change afterwards.

```
let $ABC='def' | py3 import os, win32api; print(os.environ.get('ABC'), win32api.GetEnvironmentVariable('ABC'))
```

```
None def
```

I will close this issue for now, feel free to reopen it if necessary. Thanks.

**Comment by k-takata** [comment]
https://docs.python.org/3/library/os.html#os.environ
> This mapping is captured the first time the os module is imported, typically during Python startup as part of processing site.py. Changes to the environment made after this time are not reflected in os.environ, except for changes made by modifying os.environ directly.
