### ISSUE TITLE
possible strncpy-param-overlap in src/quickfix.c (v8.2.3595)

### ISSUE THREAD

**Issue by easylyou** [vim/vim#9214]
### Steps to reproduce

Hi!
We are using improved fuzzing technology with fault injection. These are possible strncpy-param-overlap issues, where the dest and src of strncpy are the same buffer.

Different from traditional fuzzing, fault injection can test error-handling codes while the errors happen in some extreme conditions. (such as malloc() return NULL when out of memory). So it is hard to reproduce without our fault injection environment. I try to analysis the related codes to find the cause but not sure, needing your helps. I'm glad to provide more details if you need.

I try to find the cause but not very sure ... What's more, I am not sure the analysis below is the only casue..
Example:
```c
// in src/memline.c:2600
    char_u  *
ml_get_buf(...)
{
// in src/memline.c:2620
errorret:
	STRCPY(IObuff, "???");
	buf->b_ml.ml_line_len = 4;
	return IObuff; // it is possble return `IObuff`.
}
```
```c
// in src/quickfix.c:728
    static int
qf_get_next_buf_line(qfstate_T *state)
{
    //It is possible that `p_buf` = `IObuff`;
    p_buf = ml_get_buf(state->buf, state->buflnum, FALSE);

    if (len > IOSIZE - 2)
    else
    {
	state->linebuf = IObuff;
    }
    // so it is possible that `state->linebuf` === `IObuff` === `p_buf`
    vim_strncpy(state->linebuf, p_buf, state->linelen);

    return QF_OK;
}
```

### Expected behaviour

no asan report.

### Operating system

Ubuntu 20.04 LTS

### Version of Vim

v8.2.3595

### Logs and stack traces
logs with faultinject: means the error point is triggered. Then the error point's backtracks print as follow.
```
faultinject: error actived 1! name: malloc, file: alloc.c, line: 244
??:?
/home/r1/src_git/mfuzz-project/wrapper/mfuzzrt/faultinject.c:44
/home/r1/vim/vim/src/alloc.c:244
/home/r1/vim/vim/src/alloc.c:151
/home/r1/vim/vim/src/memline.c:4780
/home/r1/vim/vim/src/memline.c:792
/home/r1/vim/vim/src/memline.c:846
/home/r1/vim/vim/src/fileio.c:603
/home/r1/vim/vim/src/buffer.c:253
/home/r1/vim/vim/src/main.c:2851
/home/r1/vim/vim/src/main.c:704
/home/r1/vim/vim/src/main.c:425
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f963c65a0b3]
??:?
faultinject: error actived 2! name: malloc, file: alloc.c, line: 244
??:?
/home/r1/src_git/mfuzz-project/wrapper/mfuzzrt/faultinject.c:44
/home/r1/vim/vim/src/alloc.c:244
/home/r1/vim/vim/src/alloc.c:151
/home/r1/vim/vim/src/memline.c:4780
/home/r1/vim/vim/src/memline.c:792
/home/r1/vim/vim/src/memline.c:846
/home/r1/vim/vim/src/fileio.c:603
/home/r1/vim/vim/src/buffer.c:253
/home/r1/vim/vim/src/main.c:2851
/home/r1/vim/vim/src/main.c:704
/home/r1/vim/vim/src/main.c:425
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f963c65a0b3]
??:?
faultinject: error actived 1! name: malloc, file: alloc.c, line: 244
??:?
/home/r1/src_git/mfuzz-project/wrapper/mfuzzrt/faultinject.c:44
/home/r1/vim/vim/src/alloc.c:244
/home/r1/vim/vim/src/alloc.c:151
/home/r1/vim/vim/src/strings.c:27
/home/r1/vim/vim/src/quickfix.c:1729
/home/r1/vim/vim/src/quickfix.c:7883
/home/r1/vim/vim/src/ex_docmd.c:2614
/home/r1/vim/vim/src/ex_docmd.c:1000
/home/r1/vim/vim/src/scriptfile.c:1406
/home/r1/vim/vim/src/scriptfile.c:971
/home/r1/vim/vim/src/scriptfile.c:997
/home/r1/vim/vim/src/ex_docmd.c:2614
/home/r1/vim/vim/src/ex_docmd.c:1000
/home/r1/vim/vim/src/ex_docmd.c:594
/home/r1/vim/vim/src/main.c:3081
/home/r1/vim/vim/src/main.c:773
/home/r1/vim/vim/src/main.c:425
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f963c65a0b3]
??:?
=================================================================
==484355==ERROR: AddressSanitizer: strncpy-param-overlap: memory ranges [0x619000000a80,0x619000000a83) and [0x619000000a80, 0x619000000a83) overlap
    #0 0x483eb6 in strncpy (/home/r1/vim/vim/src/vim+0x483eb6)
    #1 0x11a8798 in vim_strncpy /home/r1/vim/vim/src/strings.c:509:5
    #2 0xe83a54 in qf_get_next_buf_line /home/r1/vim/vim/src/quickfix.c:753:5
    #3 0xe7f46c in qf_get_nextline /home/r1/vim/vim/src/quickfix.c:876:15
    #4 0xe7a219 in qf_init_process_nextline /home/r1/vim/vim/src/quickfix.c:1622:14
    #5 0xe4b690 in qf_init_ext /home/r1/vim/vim/src/quickfix.c:1743:11
    #6 0xe70798 in ex_cbuffer /home/r1/vim/vim/src/quickfix.c:7883:11
    #7 0x881a17 in do_one_cmd /home/r1/vim/vim/src/ex_docmd.c:2614:2
    #8 0x86c3d2 in do_cmdline /home/r1/vim/vim/src/ex_docmd.c:1000:17
    #9 0x102f5c5 in do_source /home/r1/vim/vim/src/scriptfile.c:1406:5
    #10 0x102a89c in cmd_source /home/r1/vim/vim/src/scriptfile.c:971:14
    #11 0x102a37a in ex_source /home/r1/vim/vim/src/scriptfile.c:997:2
    #12 0x881a17 in do_one_cmd /home/r1/vim/vim/src/ex_docmd.c:2614:2
    #13 0x86c3d2 in do_cmdline /home/r1/vim/vim/src/ex_docmd.c:1000:17
    #14 0x871cbd in do_cmdline_cmd /home/r1/vim/vim/src/ex_docmd.c:594:12
    #15 0x171a60e in exe_commands /home/r1/vim/vim/src/main.c:3081:2
    #16 0x1714bcc in vim_main2 /home/r1/vim/vim/src/main.c:773:2
    #17 0x1706804 in main /home/r1/vim/vim/src/main.c:425:12
    #18 0x7f963c65a0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #19 0x41ef7d in _start (/home/r1/vim/vim/src/vim+0x41ef7d)

0x619000000a80 is located 0 bytes inside of 1025-byte region [0x619000000a80,0x619000000e81)
allocated by thread T0 here:
    #0 0x4976bd in malloc (/home/r1/vim/vim/src/vim+0x4976bd)
    #1 0x4c768a in lalloc /home/r1/vim/vim/src/alloc.c:244:11
    #2 0x4c7453 in alloc /home/r1/vim/vim/src/alloc.c:151:12
    #3 0x17069f6 in common_init /home/r1/vim/vim/src/main.c:910:19
    #4 0x1705599 in main /home/r1/vim/vim/src/main.c:179:5
    #5 0x7f963c65a0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

0x619000000a80 is located 0 bytes inside of 1025-byte region [0x619000000a80,0x619000000e81)
allocated by thread T0 here:
    #0 0x4976bd in malloc (/home/r1/vim/vim/src/vim+0x4976bd)
    #1 0x4c768a in lalloc /home/r1/vim/vim/src/alloc.c:244:11
    #2 0x4c7453 in alloc /home/r1/vim/vim/src/alloc.c:151:12
    #3 0x17069f6 in common_init /home/r1/vim/vim/src/main.c:910:19
    #4 0x1705599 in main /home/r1/vim/vim/src/main.c:179:5
    #5 0x7f963c65a0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
```

**Comment by DominiquePelle-TomTom** [comment]
Glancing at the code, in quickfix.c:
```
 728     static int
 729 qf_get_next_buf_line(qfstate_T *state)
 ....
 753     vim_strncpy(state->linebuf, p_buf, state->linelen);
```

Both `state->linebuf` and `p_buf` could be equal to `IOBuff` (if an error happens inside `ml_get_buf()`, in which case `strncpy` is indeed called with overlapping strings which is undefined behavior.

**Comment by dpelle** [comment]
Glancing at the code, in quickfix.c:
```
 728     static int
 729 qf_get_next_buf_line(qfstate_T *state)
 ....
 753     vim_strncpy(state->linebuf, p_buf, state->linelen);
```
Both `state->linebuf` and `p_buf` could be equal to `IOBuff` if an error happens inside `ml_get_buf()`, in which case `strncpy` is indeed called with overlapping strings which is undefined behavior.
