### ISSUE TITLE
Vim segfaults at startup when the terminal has only <=2 lines

### ISSUE THREAD

**Issue by dpelle** [vim/vim#9488]
### Steps to reproduce

Vim 8.2.4028 and earlier segfaults on startup if the terminal has
only 2 lines or fewer:

1) open a terminal and resize it to have 2 lines only

2) start `vim --clean` and it will segfault.
```
$ vim --clean
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault (core dumped)
```

### Expected behaviour

No segfault. I suppose it should show an error if the terminal is too small.

### Version of Vim

vim-8.2.4028

### Environment

xubuntu-18.04.6

### Logs and stack traces

```shell
With a asan (address sanitizer) build:

=================================================================
==29073==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000004c78 at pc 0x562e582a13cb bp 0x7ffedd0dff80 sp 0x7ffedd0dff70
READ of size 4 at 0x602000004c78 thread T0
    #0 0x562e582a13ca in line_was_clobbered /home/pel/sb/vim/src/screen.c:3028
    #1 0x562e5845fb1d in check_terminal_behavior /home/pel/sb/vim/src/term.c:3834
    #2 0x562e587dd136 in vim_main2 /home/pel/sb/vim/src/main.c:781
    #3 0x562e587dc843 in main /home/pel/sb/vim/src/main.c:426
    #4 0x7f180edd3bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #5 0x562e57a915c9 in _start (/home/pel/sb/vim/src/vim+0x119e5c9)

0x602000004c78 is located 0 bytes to the right of 8-byte region [0x602000004c70,0x602000004c78)
allocated by thread T0 here:
    #0 0x7f18119ecdd7 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb2dd7)
    #1 0x562e57a91a7f in lalloc /home/pel/sb/vim/src/alloc.c:244
    #2 0x562e5829c951 in screenalloc /home/pel/sb/vim/src/screen.c:2679
    #3 0x562e582a070e in screenclear /home/pel/sb/vim/src/screen.c:2934
    #4 0x562e5845ebc8 in set_shellsize /home/pel/sb/vim/src/term.c:3499
    #5 0x562e58458ca0 in set_termname /home/pel/sb/vim/src/term.c:2141
    #6 0x562e5845a2a4 in termcapinit /home/pel/sb/vim/src/term.c:2539
    #7 0x562e587dc691 in main /home/pel/sb/vim/src/main.c:362
    #8 0x7f180edd3bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/pel/sb/vim/src/screen.c:3028 in line_was_clobbered
Shadow bytes around the buggy address:
  0x0c047fff8930: fa fa 07 fa fa fa 07 fa fa fa 00 02 fa fa fd fd
  0x0c047fff8940: fa fa 00 07 fa fa fd fa fa fa fd fa fa fa fd fd
  0x0c047fff8950: fa fa fd fa fa fa 00 fa fa fa fd fa fa fa 07 fa
  0x0c047fff8960: fa fa 07 fa fa fa 07 fa fa fa 07 fa fa fa fd fa
  0x0c047fff8970: fa fa 05 fa fa fa 04 fa fa fa 02 fa fa fa 06 fa
=>0x0c047fff8980: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 00[fa]
  0x0c047fff8990: fa fa 02 fa fa fa fd fd fa fa fd fa fa fa fd fd
  0x0c047fff89a0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff89b0: fa fa fd fa fa fa fd fa fa fa 04 fa fa fa fd fa
  0x0c047fff89c0: fa fa fd fa fa fa 06 fa fa fa fd fd fa fa fd fa
  0x0c047fff89d0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==29073==ABORTING
```
From the stack, I see that `term.c:3834` calls
`line_was_clobbered(2)`, but Line number 2 does not exist
if the terminal has <= 2 lines.
```

**Comment by dpelle** [comment]
The segfault is a regression introduced by patch 8.2.1164:
```
commit 96916ac67ad9ed5d79ce87b099f9d01aa4c13745 (tag: v8.2.1164)
Author: Bram Moolenaar <Bram@vim.org>
Date:   Wed Jul 8 23:09:28 2020 +0200

    patch 8.2.1164: text cleared by checking terminal properties not redrawn
    
    Problem:    Text cleared by checking terminal properties not redrawn. (Alexey
                Radkov)
    Solution:   Mark the screen characters as invalid. (closes #6422)
```
