### ISSUE TITLE
gvim gtk3 crashes/freezes when a file with many lines is opened in its own tab while the window is in fullscreen.

### ISSUE THREAD

**Issue by archy3** [vim/vim#9540]
### Steps to reproduce

Open a file with many lines:
`awk 'BEGIN{for (i=0; i<1000; i++) {printf "\n"}}' | vim -gNu NONE -`

Make the window manager view gvim in full screen (maximized won't cut it).

Type `:vsp`
Type `:wincmd T`
Scroll up and down with `CTRL-E`/`CTRL-Y`/`CTRL-F`/`CTRL-B` until is crashes or freezes. If it doesn't crash/freeze quickly, exit and try again.

From testing in virtual machines, it seems the more verticle pixels the screen resolution has, the higher the chance gvim will crash or freeze from the steps above.

### Expected behaviour

gvim should not crash/freeze.

### Version of Vim

8.2.4103 (compiled from source, not distro package)

### Environment

OS: Debian 12: Bookworm (Testing) VM guest
Terminal: xterm 370
$TERM: screen-256color (using tmux 3.2a)
Shell: bash 5.1.16(1)
Xorg (not Wayland)

### Logs and stack traces

The error message displayed in the terminal when this happens are not very consistent, but they have included the following lines:
`double free or corruption (!prev)`
`Vim: Caught deadly signal SEGV`
`corrupted size vs. prev_size`
`malloc(): unaligned tcache chunk detected`

In gvim 8.2.2434 packaged with Debian 11, I have also seen these error messages:
`corrupted size vs. prev_size in fastbins`
`munmap_chunk(): invalid pointer`

**Comment by lacygoill** [comment]
It would help if you could get a backtrace, and/or a log obtained with an asan-enabled Vim, and/or a log obtained with valgrind.

See [the Vim's wiki](https://github.com/vim/vim/wiki/Debugging-Vim-Bugs), and [mine](https://github.com/lacygoill/wiki/blob/master/vim/debug.md#im-writing-a-bug-report-for).

**Comment by dpelle** [comment]
I just reproduced it after many attempts with vim-8.2.4103 (huge, gtk3).

I used the same steps as reporter except that:

* I had a asan build vim
* and I used this command with `-f` to run vim in foreground and redirect asan output:
```
$ awk 'BEGIN{for (i=0; i<1000; i++) {printf "\n"}}' | ./vim -fgNu NONE - 2> asan.log
```

Just after starting vim (before even attempting to scroll), I could already see that the output was slightly corrupted  and then I pressed the Page-Up key and Vim immediately crashed.  It does not happen all the time, I needed to try maybe 20 times or so.

Here is the asan output:
```
=================================================================
==12889==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61e00000cbb3 at pc 0x557e9832b009 bp 0x7ffcbf658100 sp 0x7ffcbf6580f0
WRITE of size 1 at 0x61e00000cbb3 thread T0
    #0 0x557e9832b008 in win_update /home/pel/sb/vim/src/drawscreen.c:2476
    #1 0x557e9830b2af in update_screen /home/pel/sb/vim/src/drawscreen.c:317
    #2 0x557e99024131 in main_loop /home/pel/sb/vim/src/main.c:1403
    #3 0x557e99022292 in vim_main2 /home/pel/sb/vim/src/main.c:879
    #4 0x557e990212f3 in main /home/pel/sb/vim/src/main.c:426
    #5 0x7fa365782bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #6 0x557e981a13d9 in _start (/home/pel/sb/vim/src/vim+0x138f3d9)

0x61e00000cbb3 is located 11 bytes to the right of 2856-byte region [0x61e00000c080,0x61e00000cba8)
allocated by thread T0 here:
    #0 0x7fa36b9e0dd7 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.6+0xb2dd7)
    #1 0x557e981a188f in lalloc /home/pel/sb/vim/src/alloc.c:248
    #2 0x557e981a16df in alloc_clear /home/pel/sb/vim/src/alloc.c:177
    #3 0x557e98e0660f in win_alloc_lines /home/pel/sb/vim/src/window.c:5335
    #4 0x557e989d5f8d in screenalloc /home/pel/sb/vim/src/screen.c:2690
    #5 0x557e989d4c00 in screen_valid /home/pel/sb/vim/src/screen.c:2559
    #6 0x557e9871cd05 in update_topline /home/pel/sb/vim/src/move.c:197
    #7 0x557e98e01166 in win_enter_ext /home/pel/sb/vim/src/window.c:4834
    #8 0x557e98dfd004 in enter_tabpage /home/pel/sb/vim/src/window.c:4224
    #9 0x557e98dfdebb in goto_tabpage_tp /home/pel/sb/vim/src/window.c:4377
    #10 0x557e98dd7031 in do_window /home/pel/sb/vim/src/window.c:367
    #11 0x557e98489482 in ex_wincmd /home/pel/sb/vim/src/ex_docmd.c:7692
    #12 0x557e98451920 in do_one_cmd /home/pel/sb/vim/src/ex_docmd.c:2573
    #13 0x557e98444b51 in do_cmdline /home/pel/sb/vim/src/ex_docmd.c:993
    #14 0x557e98763c87 in nv_colon /home/pel/sb/vim/src/normal.c:3469
    #15 0x557e9874cde5 in normal_cmd /home/pel/sb/vim/src/normal.c:1120
    #16 0x557e99024491 in main_loop /home/pel/sb/vim/src/main.c:1511
    #17 0x557e99022292 in vim_main2 /home/pel/sb/vim/src/main.c:879
    #18 0x557e990212f3 in main /home/pel/sb/vim/src/main.c:426
    #19 0x7fa365782bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/pel/sb/vim/src/drawscreen.c:2476 in win_update
Shadow bytes around the buggy address:
  0x0c3c7fff9920: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c7fff9930: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c7fff9940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c7fff9950: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c7fff9960: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3c7fff9970: 00 00 00 00 00 fa[fa]fa fa fa fa fa fa fa fa fa
  0x0c3c7fff9980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c7fff9990: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c7fff99a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c7fff99b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c7fff99c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==12889==ABORTING
```
I'll try to reproduce again to check that the stack is always the same or not.

**Comment by dpelle** [comment]
I reproduced it again, so it's reasonably reproducible for me, but it takes some perseverance to try many times.

Same asan stack, I did not observe a corrupted screen before the crash this time.

I use xubuntu-18.04.6.

Next step is for me to add some printf to find how many screen lines were allocated and what is the index value of the line being accessed.

**Comment by dpelle** [comment]
I also reproduced with valgrind which gives the same information as asan. First reported valgrind error being:
```
==16353== Invalid write of size 1
==16353==    at 0x1F12F1: win_update (drawscreen.c:2476)
==16353==    by 0x1EBF12: update_screen (drawscreen.c:317)
==16353==    by 0x4CE4F3: main_loop (main.c:1403)
==16353==    by 0x4CD9FE: vim_main2 (main.c:879)
==16353==    by 0x4CD093: main (main.c:426)
==16353==  Address 0x1455a803 is 11 bytes after a block of size 2,808 alloc'd
==16353==    at 0x4C32FB5: malloc (vg_replace_malloc.c:380)
==16353==    by 0x1A23AB: lalloc (alloc.c:248)
==16353==    by 0x1A22B6: alloc_clear (alloc.c:177)
==16353==    by 0x453C14: win_alloc_lines (window.c:5335)
==16353==    by 0x36DF3E: screenalloc (screen.c:2690)
==16353==    by 0x36DA90: screen_valid (screen.c:2559)
==16353==    by 0x2D41AB: update_topline (move.c:197)
==16353==    by 0x45592F: win_new_width (window.c:6410)
==16353==    by 0x450A47: frame_new_width (window.c:3361)
==16353==    by 0x44E2EE: win_equal_rec (window.c:1942)
==16353==    by 0x44E1FA: win_equal (window.c:1899)
==16353==    by 0x44F7E1: win_close (window.c:2659)
```
I also has some debug `printf` that showed:
* `idx=117` at drawscreen.c:2477` where valgrind error is detected
* and the previous `win_alloc_lines` allocated `wp->lines` with `Rows` being 117.

**Comment by brammool** [comment]
Looks like "idx" in the big loop in win_update() goes over "Rows".  That can be caused by some miscalculation of wl_size.
Very hard to find the actual cause of that.  Simple solution is to bail out when "idx" is "Rows" or higher.
I'll make a patch for that.  It should avoid the crash, but there might still be wrong text displayed, hopefully that helps locating the cause of the problem.

**Comment by dpelle** [comment]
I see that `wp->w_lines_valid` is also 117.

Code in `drawscreen.c` looks like this:
```
  2443             if (idx < wp->w_lines_valid
  2444                     && wp->w_lines[idx].wl_valid
  2445                     && wp->w_lines[idx].wl_lnum == lnum
  2446                     && lnum > wp->w_topline
  2447                     && !(dy_flags & (DY_LASTLINE | DY_TRUNCATE))
  2448                     && !WIN_IS_POPUP(wp)
  2449                     && srow + wp->w_lines[idx].wl_size > wp->w_height
  2450 #ifdef FEAT_DIFF                                                                                                                                                 
  2451                     && diff_check_fill(wp, lnum) == 0
  2452 #endif
  2453                     )
  2454             {
  2455                 // This line is not going to fit.  Don't draw anything here,
  2456                 // will draw "@  " lines below.
  2457                 row = wp->w_height + 1;
  2458             }
  2459             else
  2460             {
  2461 #ifdef FEAT_SEARCH_EXTRA
  2462                 prepare_search_hl(wp, &screen_search_hl, lnum);
  2463 #endif
  2464 #ifdef FEAT_SYN_HL
  2465                 // Let the syntax stuff know we skipped a few lines.
  2466                 if (syntax_last_parsed != 0 && syntax_last_parsed + 1 < lnum
  2467                                                        && syntax_present(wp))
  2468                     syntax_end_parsing(syntax_last_parsed + 1);
  2469 #endif
  2470 
  2471                 // Display one line.
  2472                 row = win_line(wp, lnum, srow, wp->w_height,
  2473                                                           mod_top == 0, FALSE);
  2474 
  2475 #ifdef FEAT_FOLDING
  2476                 fprintf(stderr, "*** [%s:%d]: idx=%d wo->w_lines_valid=%d\n", __FUNCTION__, __LINE__, idx, wp->w_lines_valid); wp->w_lines[idx].wl_folded = FALSE;
  2477                 wp->w_lines[idx].wl_lastlnum = lnum;
  ...
```

We enter the `else` block at line 2459 because the condition `idx < wp->w_lines_valid` is false.
But then we should probably not use `idx` in the else block if it's not valid.

The function is long and difficult to understand unfortunately.

**Comment by brammool** [comment]
If idx goes over wp->w_lines_valid this means we get to an area of the scrreen that probably needs to be redrawn, since we don't know how many screen lines the buffer line occupies.  It doesn't always mean "idx" is invalid.
We already used w_lines[idx] at this point anyway, thus only when idx is incremented it might go over the end of w_lines.
That is only near the end of the for loop, I put the extra check there.

So either wp->w_lines_valid has  value that's too high, or there is an entry where wl_size is too low (probably zero).

**Comment by dpelle** [comment]
I saw patch 8.2.4106, but it does not fix it.
The stack is different at 8.2.4105 and 8.2.4106 but they both show errors with valgrind and both crash.

Valgrind output (+ debug printf) with vim-8.2.4105:
```
*** [win_update:2476]: idx=116 wo->w_lines_valid=0 
*** [win_update:2476]: idx=117 wo->w_lines_valid=117                            
==22791== Invalid write of size 1 
==22791==    at 0x1F130D: win_update (drawscreen.c:2476) 
==22791==    by 0x1EBF12: update_screen (drawscreen.c:317) 
==22791==    by 0x4CE50F: main_loop (main.c:1403) 
==22791==    by 0x4CDA1A: vim_main2 (main.c:879) 
==22791==    by 0x4CD0AF: main (main.c:426) 
==22791==  Address 0x147d6a73 is 11 bytes after a block of size 2,808 alloc'd 
==22791==    at 0x4C32FB5: malloc (vg_replace_malloc.c:380) 
==22791==    by 0x1A23AB: lalloc (alloc.c:248) 
==22791==    by 0x1A22B6: alloc_clear (alloc.c:177) 
==22791==    by 0x453C30: win_alloc_lines (window.c:5335) 
==22791==    by 0x36DF5A: screenalloc (screen.c:2690) 
==22791==    by 0x36DAAC: screen_valid (screen.c:2559) 
==22791==    by 0x2D41C7: update_topline (move.c:197) 
==22791==    by 0x45594B: win_new_width (window.c:6410) 
==22791==    by 0x450A63: frame_new_width (window.c:3361) 
==22791==    by 0x44E30A: win_equal_rec (window.c:1942) 
==22791==    by 0x44E216: win_equal (window.c:1899) 
==22791==    by 0x44F7FD: win_close (window.c:2659) 
==22791==    by 0x44B3F7: do_window (window.c:369) 
==22791==    by 0x2409C2: ex_wincmd (ex_docmd.c:7692) 
==22791==    by 0x2368CE: do_one_cmd (ex_docmd.c:2573) 
==22791==    by 0x233844: do_cmdline (ex_docmd.c:993) 
==22791==    by 0x2DF351: nv_colon (normal.c:3469) 
==22791==    by 0x2DB0CC: normal_cmd (normal.c:1120) 
==22791==    by 0x4CE766: main_loop (main.c:1511) 
==22791==    by 0x4CDA1A: vim_main2 (main.c:879) 
==22791==    by 0x4CD0AF: main (main.c:426) 
==22791== 
```

Valgrind output (+ debug printf) with vim-8.2.4106:
```
*** [win_update:2476]: idx=115 wo->w_lines_valid=0
*** [win_update:2476]: idx=116 wo->w_lines_valid=0
==23396== Invalid read of size 4                                                                                                                                 
==23396==    at 0x370AF4: screen_del_lines (screen.c:4017)
==23396==    by 0x36FF5D: win_do_lines (screen.c:3578)
==23396==    by 0x36FC1D: win_del_lines (screen.c:3479)
==23396==    by 0x1EF933: win_update (drawscreen.c:1854)
==23396==    by 0x1F1DE9: win_update (drawscreen.c:2733)
==23396==    by 0x1EBF12: update_screen (drawscreen.c:317)
==23396==    by 0x4CE528: main_loop (main.c:1403)
==23396==    by 0x4CDA33: vim_main2 (main.c:879)
==23396==    by 0x4CD0C8: main (main.c:426)
==23396==  Address 0x12683244 is 0 bytes after a block of size 468 alloc'd
==23396==    at 0x4C32FB5: malloc (vg_replace_malloc.c:380)
==23396==    by 0x1A23AB: lalloc (alloc.c:248)
==23396==    by 0x36DE8A: screenalloc (screen.c:2679)
==23396==    by 0x36DAC5: screen_valid (screen.c:2559)
==23396==    by 0x2D41E0: update_topline (move.c:197)
==23396==    by 0x455964: win_new_width (window.c:6410)
==23396==    by 0x450A7C: frame_new_width (window.c:3361)
==23396==    by 0x44E323: win_equal_rec (window.c:1942)
==23396==    by 0x44E22F: win_equal (window.c:1899)
==23396==    by 0x44F816: win_close (window.c:2659)
==23396==    by 0x44B410: do_window (window.c:369)
==23396==    by 0x2409DB: ex_wincmd (ex_docmd.c:7692)
==23396==    by 0x2368E7: do_one_cmd (ex_docmd.c:2573)
==23396==    by 0x23385D: do_cmdline (ex_docmd.c:993)
==23396==    by 0x2DF36A: nv_colon (normal.c:3469)
==23396==    by 0x2DB0E5: normal_cmd (normal.c:1120)
==23396==    by 0x4CE77F: main_loop (main.c:1511)
==23396==    by 0x4CDA33: vim_main2 (main.c:879)
==23396==    by 0x4CD0C8: main (main.c:426)
==23396==
```

The bug seems to be much easier to reproduce with valgrind than with asan, maybe because running with valgrind is slower than running with asan.

**Comment by brammool** [comment]
Dominique wrote:

> I saw patch 8.2.4106, but it does not fix it.
> The stack is different at 8.2.4105 and 8.2.4106 but they both show errors with valgrind and both crash.
> 
> Valgrind output (+ debug printf) with vim-8.2.4105:
> ```
> *** [win_update:2476]: idx=116 wo->w_lines_valid=0 
> *** [win_update:2476]: idx=117 wo->w_lines_valid=117                            
> ==22791== Invalid write of size 1 
> ==22791==    at 0x1F130D: win_update (drawscreen.c:2476) 
> ==22791==    by 0x1EBF12: update_screen (drawscreen.c:317) 
> ==22791==    by 0x4CE50F: main_loop (main.c:1403) 
> ==22791==    by 0x4CDA1A: vim_main2 (main.c:879) 
> ==22791==    by 0x4CD0AF: main (main.c:426) 
> ==22791==  Address 0x147d6a73 is 11 bytes after a block of size 2,808 alloc'd 
> ==22791==    at 0x4C32FB5: malloc (vg_replace_malloc.c:380) 
> ==22791==    by 0x1A23AB: lalloc (alloc.c:248) 
> ==22791==    by 0x1A22B6: alloc_clear (alloc.c:177) 
> ==22791==    by 0x453C30: win_alloc_lines (window.c:5335) 
> ==22791==    by 0x36DF5A: screenalloc (screen.c:2690) 
> ==22791==    by 0x36DAAC: screen_valid (screen.c:2559) 
> ==22791==    by 0x2D41C7: update_topline (move.c:197) 
> ==22791==    by 0x45594B: win_new_width (window.c:6410) 
> ==22791==    by 0x450A63: frame_new_width (window.c:3361) 
> ==22791==    by 0x44E30A: win_equal_rec (window.c:1942) 
> ==22791==    by 0x44E216: win_equal (window.c:1899) 
> ==22791==    by 0x44F7FD: win_close (window.c:2659) 
> ==22791==    by 0x44B3F7: do_window (window.c:369) 
> ==22791==    by 0x2409C2: ex_wincmd (ex_docmd.c:7692) 
> ==22791==    by 0x2368CE: do_one_cmd (ex_docmd.c:2573) 
> ==22791==    by 0x233844: do_cmdline (ex_docmd.c:993) 
> ==22791==    by 0x2DF351: nv_colon (normal.c:3469) 
> ==22791==    by 0x2DB0CC: normal_cmd (normal.c:1120) 
> ==22791==    by 0x4CE766: main_loop (main.c:1511) 
> ==22791==    by 0x4CDA1A: vim_main2 (main.c:879) 
> ==22791==    by 0x4CD0AF: main (main.c:426) 
> ==22791== 
> ```
> 
> Valgrind output (+ debug printf) with vim-8.2.4106:
> ```
> *** [win_update:2476]: idx=115 wo->w_lines_valid=0
> *** [win_update:2476]: idx=116 wo->w_lines_valid=0
> ==23396== Invalid read of size 4                                                                                                                                 
> ==23396==    at 0x370AF4: screen_del_lines (screen.c:4017)
> ==23396==    by 0x36FF5D: win_do_lines (screen.c:3578)
> ==23396==    by 0x36FC1D: win_del_lines (screen.c:3479)
> ==23396==    by 0x1EF933: win_update (drawscreen.c:1854)
> ==23396==    by 0x1F1DE9: win_update (drawscreen.c:2733)
> ==23396==    by 0x1EBF12: update_screen (drawscreen.c:317)
> ==23396==    by 0x4CE528: main_loop (main.c:1403)
> ==23396==    by 0x4CDA33: vim_main2 (main.c:879)
> ==23396==    by 0x4CD0C8: main (main.c:426)
> ==23396==  Address 0x12683244 is 0 bytes after a block of size 468 alloc'd
> ==23396==    at 0x4C32FB5: malloc (vg_replace_malloc.c:380)
> ==23396==    by 0x1A23AB: lalloc (alloc.c:248)
> ==23396==    by 0x36DE8A: screenalloc (screen.c:2679)
> ==23396==    by 0x36DAC5: screen_valid (screen.c:2559)
> ==23396==    by 0x2D41E0: update_topline (move.c:197)
> ==23396==    by 0x455964: win_new_width (window.c:6410)
> ==23396==    by 0x450A7C: frame_new_width (window.c:3361)
> ==23396==    by 0x44E323: win_equal_rec (window.c:1942)
> ==23396==    by 0x44E22F: win_equal (window.c:1899)
> ==23396==    by 0x44F816: win_close (window.c:2659)
> ==23396==    by 0x44B410: do_window (window.c:369)
> ==23396==    by 0x2409DB: ex_wincmd (ex_docmd.c:7692)
> ==23396==    by 0x2368E7: do_one_cmd (ex_docmd.c:2573)
> ==23396==    by 0x23385D: do_cmdline (ex_docmd.c:993)
> ==23396==    by 0x2DF36A: nv_colon (normal.c:3469)
> ==23396==    by 0x2DB0E5: normal_cmd (normal.c:1120)
> ==23396==    by 0x4CE77F: main_loop (main.c:1511)
> ==23396==    by 0x4CDA33: vim_main2 (main.c:879)
> ==23396==    by 0x4CD0C8: main (main.c:426)
> ==23396==
> ```

Another place where the index is checked against wp->w_lines_valid.
Should be the same cause.  Again, I can add a check for not going over
Rows, but that is just working around the cause of the problem.

> The bug seems to be much easier to reproduce with valgrind than with
> asan, maybe because running with valgrind is slower than running with
> asan.

In the past this kind of problem was caused by resize events handled at
an unexpected moment.  Since it has to do with a window closing, that
might be related to a scrollbar appearing or disappearing.

I think we should both find all places that rely on values that might be
wrong, and then find the root cause and fix that.  May need to revert
the safety checks to find the root cause.

-- 
GUARD #2:  Wait a minute -- supposing two swallows carried it together?
GUARD #1:  No, they'd have to have it on a line.
GUARD #2:  Well, simple!  They'd just use a standard creeper!
GUARD #1:  What, held under the dorsal guiding feathers?
GUARD #2:  Well, why not?
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
The bug is not specific to GTK3 GUI.  
I can also reproduce it with at least the GTK2 and Motif GUIs (at version 8.2.4114).
I did not see the bug with the Athena GUI.
